CREATE TABLE [SS].[SS_BookingMaster] (
    [BookingId]                     INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [BookingRefId]                  VARCHAR (50)    NULL,
    [CorrelationId]                 VARCHAR (MAX)   NULL,
    [ProviderConfirmationNumber]    VARCHAR (50)    NULL,
    [TripStartDate]                 DATETIME        NULL,
    [TripEndDate]                   DATETIME        NULL,
    [ChannelId]                     VARCHAR (50)    NULL,
    [accountId]                     VARCHAR (50)    NULL,
    [providerName]                  VARCHAR (50)    NULL,
    [providerId]                    VARCHAR (50)    NULL,
    [ProviderCancellationNumber]    VARCHAR (50)    NULL,
    [creationDate]                  DATETIME        NULL,
    [modifiedDate]                  DATETIME        NULL,
    [SupplierRate]                  FLOAT (53)      NULL,
    [SupplierCurrency]              VARCHAR (50)    NULL,
    [BookingRate]                   FLOAT (53)      NULL,
    [BookingCurrency]               VARCHAR (50)    NULL,
    [AgentID]                       INT             NULL,
    [MainAgentID]                   INT             NULL,
    [SubMainAgntId]                 INT             NULL,
    [PaymentMode]                   INT             NULL,
    [CityName]                      VARCHAR (50)    NULL,
    [PassengerEmail]                VARCHAR (50)    NULL,
    [PassengerPhone]                VARCHAR (20)    NULL,
    [Cust_Id]                       VARCHAR (50)    NULL,
    [BookingStatus]                 VARCHAR (50)    NULL,
    [ClientBookingId]               INT             NULL,
    [AmountBeforePgCommission]      FLOAT (53)      NULL,
    [AmountAfterPgCommision]        FLOAT (53)      NULL,
    [RateId]                        VARCHAR (50)    NULL,
    [PGStatus]                      VARCHAR (50)    NULL,
    [VoucherUrl]                    VARCHAR (MAX)   NULL,
    [RefName]                       VARCHAR (50)    NULL,
    [Email]                         VARCHAR (50)    NULL,
    [OBTCNumber]                    VARCHAR (50)    NULL,
    [ReversalStatus]                BIT             NULL,
    [MakePaymentReversalFlag]       VARCHAR (200)   NULL,
    [MakePaymentReversalStatus]     VARCHAR (200)   NULL,
    [MakePaymentReversalMessage]    VARCHAR (MAX)   NULL,
    [CancellationDate]              DATETIME        NULL,
    [Titel]                         VARCHAR (10)    NULL,
    [Name]                          VARCHAR (50)    NULL,
    [Surname]                       VARCHAR (50)    NULL,
    [Age]                           VARCHAR (50)    NULL,
    [CancellationDeadline]          DATETIME        NULL,
    [SupplierCancellationDate]      DATETIME        NULL,
    [CityCode]                      VARCHAR (50)    NULL,
    [CountryCode]                   VARCHAR (50)    NULL,
    [ROEValue]                      FLOAT (53)      NULL,
    [Markup]                        VARCHAR (50)    NULL,
    [Pendingcancellation]           BIT             NULL,
    [AgentCanxCharges]              DECIMAL (18, 2) NULL,
    [SupplierCanxCharges]           DECIMAL (18, 2) NULL,
    [CancellationRemark]            VARCHAR (400)   NULL,
    [CancellationPolicyText]        TEXT            NULL,
    [totalPax]                      INT             CONSTRAINT [DF__SS_Bookin__total__191B61C5] DEFAULT ((0)) NULL,
    [ProviderInfo]                  VARCHAR (200)   NULL,
    [SupplierCanxAgentChrge]        DECIMAL (18, 2) NULL,
    [PostCancellationCharges]       VARCHAR (100)   NULL,
    [FinalROE]                      FLOAT (53)      NULL,
    [ServiceCharges]                FLOAT (53)      NULL,
    [TotalServiceCharges]           FLOAT (53)      NULL,
    [SupplierChargesPer]            FLOAT (53)      NULL,
    [SupplierCharges]               FLOAT (53)      NULL,
    [ModeOfCancellation]            VARCHAR (50)    NULL,
    [CancelledBy]                   VARCHAR (50)    NULL,
    [GSTAmountOnServiceCharges]     FLOAT (53)      NULL,
    [GSTOnServiceCharges]           FLOAT (53)      NULL,
    [FinalRoeMarkup]                VARCHAR (50)    NULL,
    [FileNo]                        VARCHAR (50)    NULL,
    [OBTCNo]                        VARCHAR (50)    NULL,
    [InquiryNo]                     VARCHAR (50)    NULL,
    [AccRemark]                     VARCHAR (50)    NULL,
    [OpsRemark]                     VARCHAR (50)    NULL,
    [SubAgentId]                    INT             NULL,
    [RiyaSubUserId]                 INT             NULL,
    [BookingSource]                 VARCHAR (50)    NULL,
    [TotalAdult]                    INT             NULL,
    [TotalChildren]                 INT             NULL,
    [ProviderContactNumber]         VARCHAR (20)    NULL,
    [LocalProviderName]             VARCHAR (50)    NULL,
    [SightSeeing_ERPResponseID]     VARCHAR (MAX)   NULL,
    [SightSeeing_ERPPushStatus]     BIT             NULL,
    [BillingSettledBy]              VARCHAR (50)    NULL,
    [CorporatePANVerificatioStatus] VARCHAR (50)    NULL,
    [DocumentURL]                   VARCHAR (MAX)   NULL,
    [SightSeeing_ERPCanResponseID]  VARCHAR (MAX)   NULL,
    [SightSeeing_ERPCanPushStatus]  BIT             NULL,
    [ClientIP]                      VARCHAR (100)   NULL,
    [RequestForCancelled]           VARCHAR (50)    NULL,
    [AdditionalBillingSettledBy]    VARCHAR (50)    NULL,
    CONSTRAINT [PK_SS_BookingMaster] PRIMARY KEY CLUSTERED ([BookingId] ASC)
);

