                                                  
CREATE Procedure Proc_InsertBookingDetailInMaster                                                                                                                                  
@LeaderTitle varchar(100)=null,                                                                                                                                  
@LeaderFirstName varchar(200)=null,                                                                                                                    
--@LeaderMiddleName varchar(200)=null,                                                                                                                    
@LeaderLastName varchar(200)=null,                                                                                                                                  
@CurrencyCode varchar(50)=null,                                                                                                                                  
@HotelName varchar(800)=null,                                                                                                                                  
@CountryName varchar(100)=null,                                                                                                                          
@BookingCountry varchar(100)=null,                                                                                                                       
@HotelAddress1 varchar(500)=null,                                                                                                                                  
@CurrentStatus varchar(100)=null,                                                                                                                                  
@TotalAdults int=0,                                                                                                                                  
@TotalChildren int=0,                                                                                                                                  
@TotalRooms int=0,                                                                                                                                  
@CheckInDate datetime=null,                                                                                                                                  
@CheckOutDate datetime=null,                                                                                                                                  
@HotelRating varchar(30)=null,                                                                                                                                  
@SelectedNights int=0,                                                                                                                                  
@PassengerPhone varchar(50)=null,                                                                                                                                  
@PassengerEmail varchar(200)=null,                                                                                                                                  
@inserteddate datetime=null,                                                                                                                                  
@cityName varchar(50)=null,                                                                                                                                  
@SupplierName varchar(80)=null,                                                                                                                                  
@B2BPaymentMode int=0,                                                                                                                                  
@DisplayDiscountRate nvarchar(1000)=null,             
@MainAgentID bigint=null,            
@Meal varchar(300)=null,                            
@TotalRoomAmount  varchar(80)=null,                                       
@TotalSummaryAmount varchar(80)=null,                                                                          
@AlertEmail varchar(200)=null,                                  
@SearchApiId varchar(300),                                        
@HotelId varchar(60),                                                                                                 
@OrderId varchar(60),                                                                                    
@ExpectedPrize FLOAT(50),                                                                   
@SectionUniqueId varchar(20),                                            
@AgentId bigint=null,                                                                                 
@BookingReference varchar(50)=null,                                               
@TotalCharges FLOAT(50),                                                                                  
--@HotelCityId int,                                            
@HotelCityId varchar(100)=null,                                           
@AgentRate FLOAT(50),                                                                                                                        
@FullRefund bit=null,                                                                                                                                  
@SpecialRemark varchar(600)=null,                                                                            
@MethodName varchar(100)=null  ,                                                                                          
@SupplierId varchar(50)=null,                                                                                               
@SupplierRate FLOAT(50)=0,                                                                                           
@ReferenceName varchar(100)=null,                                                                                          
@OBTCNumber varchar(100)=null,                                                                                
@CancellationDeadLine varchar(100)=null,                                                                                                                        
@IsPANMandatory varchar(50)=null,                                                                                                                          
@IsGSTRequired varchar(50)=null,                                                                                                                  
@MarkupCurrency varchar(50)=null,                                                                                                    
@CheckinTime varchar(50)=null,                                                                                                              
@CheckOutTime varchar(50)=null,                                                                                                            
@AmountAfterPgCommision float=0,                                                                                                            
@AmountBeforePgCommission float=0,                                                                                                          
@PayAtHotel bit=null,                                                                                                        
@HotelTaxes float=0,                                                                                                        
@HotelTotalGross float=0,                                                                                                     
@AgentCommission float=0,                                                                                                    
@HotelTDS float=0,                                                                                                  
@HotelPhone varchar(100)=null,                                                                                                
@CancellationPolicy varchar(MAX)=null,                                                                                                
@RiyaPNR varchar(50)=null,                                                                                      
@ChannelId varchar(100)=null,                                                       
@AccountId varchar(100)=null,                          
@SupplierCurrency varchar(100)=null,                                                                                  
@SubAgentId int=0 ,                                    
@RiyaSubUserId int = 0,                                                                      
@HotelTotalPaybleAmountOld float=null,                                                               
@SupplierBookingPaymentDate varchar(100)=null,                                                                
@GstOnServiceCharges float=0,                                                                  
@ServiceCharges float=0,                                                                  
@TotalServiceCharges float=0,                                                                  
@GstAmountOnServiceChagres float=0,                                                              
@lat float=0,                                                             
@lang  float=0,                                                            
@Nationalty varchar(100)=null,                                                          
@IsPriceChange int=0,                                                        
@SPublishedBaseRate float=0,                                                   
@SPublishedRate float=0,                                                        
@STotalRate float=0,                                                        
@SBaseRate float=0,                                                        
@SComission float=0,                                                        
@SCurrency varchar(50)=null,                                                    
@SupplierChargesPer float=0,                                                    
@SupplierCharges float=0,                                                    
@VccPer float=0,                                                    
@VccValue float=0,                                            
@SINRCommissionAmount float=0,                                        
@SCommissionDiscription varchar(500)=null,                                        
@HotelIncludes varchar(500)=null,                                      
@MembershipNumber varchar(150)=null,                                    
@ChainName varchar(150)=null,                                  
@DocumentUrl varchar(500)=null,                                
@AgentServiceFee float=0,                                 
@AgentServiceFeeRealTime float=0,                            
@CorporatePanReq varchar(10)=null,                          
@CorporatePANVerificatioStatus varchar(50)=null,                        
@BookingRateType varchar(100)=null,                      
@HotelPostalCode varchar(100)=null,                    
@HotelBookStateName varchar(100)=null,                    
@HotelBookCountryName varchar(100)=null,                    
@HotelBookCountryCode varchar(50)=null,                  
@HotelAdditionalInformation varchar(max)=null,                
@RiyaUserRealTimeServiceFee float=0,                
@GSTOnRiyaUsereRealTimeServiceFee float=0,              
@HotelDiscount float=0,            
@HotelInformation varchar(max)=null,          
@clientIP varchar(100)='',        
@LoginSessionId varchar(600)='',      
@ServiceChargesPercent float=0,    
@HotelEmails varchar(1000)='',    
@HotelFax varchar(100)='',  
@HotelOffsetGMT varchar(100)='0',
@BookingSearchType varchar(100)=''
As                                                                                                                                  
Begin                                                                                                               
declare @book_pk_id BIGINT=0;                                                   
--set @RiyaSubUserId =@SubAgentId;                         
                                                                  
declare @SupplierPkId int=0                                                                  
                                            
Set @SupplierPkId=(Select Id from B2BHotelSupplierMaster where RhSupplierId=@SupplierId)                                                    
 Insert into Hotel_BookMaster(LeaderTitle,                                                                             
 LeaderFirstName,                                                                                                                       
 --LeaderMiddleName,                                                                                       
 LeaderLastName,                                                           
 CurrencyCode,                                                                                                                                  
 HotelName,                                                                                  
 CountryName,                                                                                                                       
 BookingCountry,                                                       
 HotelAddress1,                                                                                                     
 CurrentStatus,                                                                                               
 TotalAdults,                                                                                                              
 TotalChildren,                                          
 TotalRooms,                                                                                                                  
 CheckInDate,                                                                                                                                  
 CheckOutDate,                                                                         
 HotelRating,                                                                                                                                  
 SelectedNights,                                                                   
PassengerPhone,                                                                                                 
 PassengerEmail,                                                                                                                                  
 inserteddate,                                                                                            
 cityName,                                                                                                                  
 SupplierName,                             
 B2BPaymentMode,                                                                                                                                  
 DisplayDiscountRate,                                                                                                                                  
 MainAgentID,                                                                                                   
 Meal,                                                                      
 TotalRoomAmount,                                                                                               
 TotalSummaryAmount,                                                                                                                                  
 AlertEmail,                                   
 searchApiId,                                                                                                              
 hotelId,                            
 orderId,                                                                                                                                  
 expected_prize,                                                                                                
 section_unique_id,                                                                                                                               
 RiyaAgentID,                                                                             
 BookingReference,                                                                                                                        
 TotalCharges,                                                                                                                         
 CityId,                               
 AgentRate,                                                                                                                                  
 FullRefund,                                                                                                                                  
 SpecialRemark,                                                                                                                               
 SupplierUsername,                                                                                                          
 SupplierRate,                                                                                          
 AgentRefNo,                                                        
 OBTCNo,                                                         
 CancellationDeadLine,                                                                                                                          
 IsPANCardRequired,                                                                                      
 IsGSTRequired,                                                                                                      
 MarkupCurrency,                                      
 CheckInTime,                                                                                                              
 CheckOutTime,                                                                                                            
 AmountAfterPgCommision,                                                                                      
 AmountBeforePgCommission,                                                                                                          
 PayAtHotel,                                                                                                        
 HotelTaxes,                                             
 HotelTotalGross,                                                                                                    
 AgentCommission,                                                                                                    
 HotelTDS,                                                                                                  
 HotelPhone,                                                                               
 CancellationPolicy,                                                                                                
 riyaPNR,                                                                       
 BookingPortal,                                                                                      
 AccountId,                                                                                      
 ChannelId,                                                                                 
 SupplierCurrencyCode,                                                                                  
 SubAgentId,                                     
 SuBMainAgentID,                                                                         
 ExpirationDate,                                                                      
 PaybleAmountOld,                         
 SupplierBookingPaymentDate,                                                                  
 SupplierPkId,                                                                
 GstOnServiceCharges,                                             
 ServiceCharges,                                                                  
 TotalServiceCharges,                                                      
 GstAmountOnServiceChagres,                                                              
 Lat,                                                              
 Lang,                                                            
 Nationalty,                                                          
 ispricechange,                                                        
 SPublishedBaseRate,                                
 SPublishedRate,                                                        
 STotalRate,                                                        
 SBaseRate,            
 SComission,                                   
 SCurrency,                                                      
 Refundable,                                                    
 SupplierChargesPer,                                                    
 SupplierCharges,                                                    
 VccPer,                                                    
 VccValue,                                            
 SINRCommissionAmount,                                              
 SCommissionDiscription,                                        
 HotelIncludes,                                      
 MembershipNumber,                                    
 ChainName,                                  
 PanCardURL,                           
 AgentServiceFee,                                
 AgentServiceFeeRealTime,                            
 CorporatePanReq,                          
 CorporatePANVerificatioStatus,                        
 BookingRateType,                      
 HotelPostalCode,                    
 HotelBookStateName,                    
 HotelBookCountryName,                    
 HotelBookCountryCode,                  
 HotelAdditionalInformation,                
 RiyaUserRealTimeServiceFee,                
 GSTOnRiyaUsereRealTimeServiceFee,              
 HotelDiscount,            
 HotelInformation,          
 ClientIP,        
 LoginSessionId,      
 ServiceChargesPercent,    
 HotelEmails,    
 HotelFax,  
 HotelOffsetGMT,
 BookingSearchType)                                                                                                                                  
 values(@LeaderTitle,                                                                                                          
 @LeaderFirstName,                                                                                               
 --@LeaderMiddleName,                                                                                                                    
 @LeaderLastName,                                                                                                   
 @CurrencyCode,                                                    
 @HotelName,                                                                                                                                  
 @CountryName,                                                                                                                          
 @BookingCountry,                                                                                                                      
@HotelAddress1,                                                                                                      
 @CurrentStatus,                                                                                                                                  
 @TotalAdults,                                                                                                       
 @TotalChildren,          
 @TotalRooms,                                                                                       
 @CheckInDate,                                                                                                                
 @CheckOutDate,                                                                                                                                  
 @HotelRating,                                                                           
 @SelectedNights,                                                                                                                     
 @PassengerPhone,                                                                                                      
 @PassengerEmail,                                                                                   
 GETDATE(),                                                                                                              
 @cityName,                              
 @SupplierName,                                                                                                                            
 @B2BPaymentMode,                                                 
 @DisplayDiscountRate,                
 @MainAgentID,                                                                                                                                  
 @Meal,                                                     
 @TotalRoomAmount,                                                                                                       
 @TotalSummaryAmount,                                                     
 @AlertEmail,                                                                                          
 @SearchApiId,                                                                                                               
 @HotelId,                                      
 @OrderId,                                                                                                                                  
 @ExpectedPrize,                            
 @SectionUniqueId,                                                                                  
 @AgentId,                                                                       
 @BookingReference,                                                                                                                                  
 @TotalCharges,                                     
 @HotelCityId,                                                                                                                
 --@AgentRate,                                                                         
 @ExpectedPrize,                                                                        
 @FullRefund,                                                                                              
 @SpecialRemark,                                                         
 @SupplierId,                                                                                                                              
 --@SupplierRate,                                                                         
 @ExpectedPrize,                                                                        
 @ReferenceName,                                                   
@OBTCNumber,                                                                             
 @CancellationDeadLine,                                                                                                                          
 @IsPANMandatory,                                                                                                                          
 @IsGSTRequired,                                                                                                                  
 @MarkupCurrency,                                                                 
 @CheckinTime,                                           
 @CheckOutTime,                                                                                                            
 @AmountAfterPgCommision,                                                                                                            
 @AmountBeforePgCommission,                                                                                                          
 @PayAtHotel,                                                       
 @HotelTaxes,                                                
 @HotelTotalGross,                                                                                                    
 @AgentCommission,                                                                                                 
 @HotelTDS,                                                                                                  
 @HotelPhone,                                                                                                
 @CancellationPolicy,                                           
 @RiyaPNR,                
 'TNH',                                                                                      
 @AccountId,                                                                                      
 @ChannelId,                                                                                    
 @SupplierCurrency,                                                         
 @SubAgentId,                                                                                  
 @RiyaSubUserId,                                                                          
 @CancellationDeadLine,                                                                 
 @HotelTotalPaybleAmountOld,                            
 @SupplierBookingPaymentDate,                                                                  
 @SupplierPkId,                                                                
 @GstOnServiceCharges,                      
 @ServiceCharges,                                                                  
 @TotalServiceCharges,                                                                  
 @GstAmountOnServiceChagres,                                                              
 @lat,                                                              
 @lang,                                                            
 @Nationalty,                                                        
 @IsPriceChange,                                                        
 @SPublishedBaseRate,                                                        
@SPublishedRate,                                                        
@STotalRate,                                                        
@SBaseRate,                                                        
@SComission,                                                        
@SCurrency,                                        
@FullRefund,                                                    
@SupplierChargesPer,                                                    
@SupplierCharges,                                                    
@VccPer,                                                    
@VccValue,                                            
@SINRCommissionAmount,                                              
@SCommissionDiscription,                                        
@HotelIncludes,                                      
@MembershipNumber,                                    
@ChainName,                                  
@DocumentUrl,                                
@AgentServiceFee,                                
@AgentServiceFeeRealTime,                            
@CorporatePanReq,                          
@CorporatePANVerificatioStatus,                        
@BookingRateType,                      
@HotelPostalCode,                    
@HotelBookStateName,                    
@HotelBookCountryName,                    
@HotelBookCountryCode,                  
@HotelAdditionalInformation,                
@RiyaUserRealTimeServiceFee,                
@GSTOnRiyaUsereRealTimeServiceFee,              
@HotelDiscount,            
@HotelInformation,          
@clientIP,        
@LoginSessionId,      
@ServiceChargesPercent,    
@HotelEmails,    
@HotelFax,  
@HotelOffsetGMT,
@BookingSearchType)                                                                                                      
 set @book_pk_id  =(select  SCOPE_IDENTITY())                                                                                                                        
                                                                                                                        
  insert into Hotel_Status_History                                                                                                                                                                        
    (                                                                                                                                    
     FKHotelBookingId                                                                                                 
    ,FkStatusId                                                                                                                                     
    ,CreateDate                                     
    ,CreatedBy                                                                                                                                          
    ,ModifiedDate                                                                                                                                                                   
    ,IsActive      
 ,MainAgentId                                                                                    
 ,MethodName                                                                                                                       
    )                                                                                                                                                                        
    values                                                                                                                                                                        
    (                                                                                                
     @book_pk_id                                                                                       
    ,'9'                                                                                
    ,SYSDATETIME()                                                                                                                                                                        
    ,@AgentId                                                                                                               
    ,null                                                                                                                                      
    ,1                                                                          
   ,@MainAgentID                                                                                                                                 
  ,@MethodName                                                                                                               
    )                                                                          
      select @book_pk_id;                                                     
                                                     
 insert into Hotel_UpdatedHistory                                                             
  (fkbookid,FieldName ,FieldValue,InsertedDate,InsertedBy,UpdatedType)                                                   
  select @book_pk_id,'InProcess','Proc_InsertBookingDetailInMaster',GETDATE(),coalesce(@MainAgentid,@AgentId,@RiyaSubUserId),'BookingStatus' from Hotel_Status_History where FKHotelBookingId = @book_pk_id                                                   
  
      SELECT SCOPE_IDENTITY();                                                    
                                                          
End 