CREATE procedure Proc_InsertRetrvePNRDetailsInMaster            
@LeaderTitle varchar(100)=null,                                                                                                              
@LeaderFirstName varchar(200)=null,                                                                                                
--@LeaderMiddleName varchar(200)=null,                                                                                                
@LeaderLastName varchar(200)=null,                                                                                                              
@CurrencyCode varchar(50)=null,                                                                                                              
@HotelName varchar(800)=null,                                                                                                              
@CountryName varchar(100)=null,                                                                                                      
@BookingCountry varchar(100)=null,                                                                                                   
@HotelAddress1 varchar(500)=null,                                                                                                              
@CurrentStatus varchar(100)=null,                                                                                                              
@TotalAdults int=0,                                                                                                              
@TotalChildren int=0,                                                                                                              
@TotalRooms int=0,                                                                                                              
@CheckInDate datetime=null,                                                                                                              
@CheckOutDate datetime=null,                                                                                                              
@HotelRating varchar(30)=null,                                                                                                              
@SelectedNights int=0,                                                                                                              
@PassengerPhone varchar(50)=null,                                                                                                              
@PassengerEmail varchar(200)=null,                                                                                                              
@inserteddate datetime=null,                                                                                                              
@cityName varchar(50)=null,                                                                                                              
@SupplierName varchar(80)=null,                                                                                                              
@B2BPaymentMode int=0,                                                                                                              
@DisplayDiscountRate nvarchar(1000)=null,                                                                                                              
@MainAgentID bigint=null,                                                                                                              
@Meal varchar(300)=null,                                                                                                              
@TotalRoomAmount  varchar(80)=null,                                                                                                              
@TotalSummaryAmount varchar(80)=null,                                                                                                              
@AlertEmail varchar(200)=null,           
@SearchApiId varchar(300),                     
@HotelId varchar(60),                                                       
@OrderId varchar(60),                                                                
@ExpectedPrize FLOAT(50),                                               
@SectionUniqueId varchar(20),                        
@AgentId bigint=null,                                                             
@BookingReference varchar(50)=null,                           
@TotalCharges FLOAT(50),                                                              
--@HotelCityId int,                        
@HotelCityId varchar(100)=null,                       
@AgentRate FLOAT(50),                                                                                                    
@FullRefund bit=null,                                                                                                              
@SpecialRemark varchar(600)=null,                                                        
@MethodName varchar(100)=null  ,                                                                      
@SupplierId varchar(50)=null,                                                                           
@SupplierRate FLOAT(50)=0,                                                                       
@ReferenceName varchar(100)=null,                                                                      
@OBTCNumber varchar(100)=null,                                                            
@CancellationDeadLine varchar(100)=null,                                                                                                    
@IsPANMandatory varchar(50)=null,                                                                                                      
@IsGSTRequired varchar(50)=null,                                                                                              
@MarkupCurrency varchar(50)=null,                                                                                
@CheckinTime varchar(50)=null,                                                                                          
@CheckOutTime varchar(50)=null,                                                                                        
@AmountAfterPgCommision float=0,                                                                                        
@AmountBeforePgCommission float=0,                                                                                      
@PayAtHotel bit=null,                                                                                    
@HotelTaxes float=0,                                                                                    
@HotelTotalGross float=0,                                                                                 
@AgentCommission float=0,                                                                                
@HotelTDS float=0,                                                                              
@HotelPhone varchar(100)=null,                                                                            
@CancellationPolicy varchar(MAX)=null,                                                                            
@RiyaPNR varchar(50)=null,                                                                  
@ChannelId varchar(100)=null,                                                                  
@AccountId varchar(100)=null,                                                                
@SupplierCurrency varchar(100)=null,                                                              
@SubAgentId int=0 ,                                                          
@RiyaSubUserId int = 0,                                                  
@HotelTotalPaybleAmountOld float=null,                                                
@SupplierBookingPaymentDate varchar(100)=null,                                            
@GstOnServiceCharges float=0,                                              
@ServiceCharges float=0,                                              
@TotalServiceCharges float=0,                                              
@GstAmountOnServiceChagres float=0,                                          
@lat float=0,                                          
@lang  float=0,                                       
@Nationalty varchar(100)=null,                                      
@IsPriceChange int=0,                  
@SPublishedBaseRate float=0,                                    
@SPublishedRate float=0,                                    
@STotalRate float=0,                                    
@SBaseRate float=0,                                    
@SComission float=0,                                    
@SCurrency varchar(50)=null,                                
@SupplierChargesPer float=0,                                
@SupplierCharges float=0,                                
@VccPer float=0,                                
@VccValue float=0,                        
@SINRCommissionAmount float=0,                    
@SCommissionDiscription varchar(500)=null,                    
@HotelIncludes varchar(500)=null,                  
@MembershipNumber varchar(150)=null,                
@ChainName varchar(150)=null,              
@DocumentUrl varchar(500)=null,            
@providerConfirmationNumber varchar(150)=null,       
@PNRofficeId varchar(50)=null,  
@PNRRateType  varchar(100)=null,
@FreeTextPNRInclusion varchar(300)=null,
@FreeTextPNRRoomCategory  varchar(300)=null
As            
Begin            
declare @book_pk_id BIGINT=0;             
declare @SupplierPkId int=0               
 If NOT Exists(Select  providerConfirmationNumber from Hotel_BookMaster where providerConfirmationNumber=@providerConfirmationNumber)            
 Begin            
  Insert into Hotel_BookMaster            
  (LeaderTitle,                                                                                                              
  LeaderFirstName,                                                                                                                                                                                       
  LeaderLastName,                                                                                                       
  CurrencyCode,                                                                                                              
  HotelName,                                                                                          
  CountryName,                                                                                                   
  BookingCountry,                                                                                                  
  HotelAddress1,                                                                                 
  CurrentStatus,                                                                                                              
  TotalAdults,                                                                                          
  TotalChildren,                                                                                                              
  TotalRooms,                                                                                              
  CheckInDate,                                                                                                              
  CheckOutDate,                                                                                               
  HotelRating,                                                                                                              
  SelectedNights,                                               
  PassengerPhone,                                                                                                              
  PassengerEmail,                                                                                                              
  inserteddate,                                                                        
  cityName,                                             
  SupplierName,                                                                                                              
  B2BPaymentMode,                                                                                                              
  DisplayDiscountRate,                                                                                                              
  MainAgentID,                                                                                     
  Meal,                                                  
  TotalRoomAmount,                                                                                            
  TotalSummaryAmount,                                                                                                              
  AlertEmail,               
  searchApiId,                                                                                          
  hotelId,                                                                                             
  orderId,                                                        
  expected_prize,                                                                            
  section_unique_id,                                                                                                              
  RiyaAgentID,                                                         
  BookingReference,                                                                                                    
  TotalCharges,                                                                                                              
  CityId,                                                            
  AgentRate,                                                                                                              
  FullRefund,                                                                                                              
  SpecialRemark,                                                                                                           
  SupplierUsername,                                                                                                          
  SupplierRate,                                                                      
  AgentRefNo,                                                                                                        
  OBTCNo,                                     
  CancellationDeadLine,                                                                                                      
  IsPANCardRequired,                                                                                                      
  IsGSTRequired,                                                                                  
  MarkupCurrency,                                                               
  CheckInTime,                                                                                          
  CheckOutTime,                                                                                        
  AmountAfterPgCommision,                                                                                        
  AmountBeforePgCommission,                                                                                      
  PayAtHotel,                                                                                    
  HotelTaxes,                                                                                    
  HotelTotalGross,                                                                                
  AgentCommission,                                                                                
  HotelTDS,                                                                              
  HotelPhone,                                                                            
  CancellationPolicy,                                                                            
  riyaPNR,                                                   
  BookingPortal,                                                                  
  AccountId,                                                                  
  ChannelId,                            
  SupplierCurrencyCode,                                                              
  SubAgentId,                                                              
  SuBMainAgentID,                                                     
  ExpirationDate,                                                  
  PaybleAmountOld,                                       
  SupplierBookingPaymentDate,                                              
  SupplierPkId,                                            
  GstOnServiceCharges,                                              
  ServiceCharges,                                            
  TotalServiceCharges,                                              
  GstAmountOnServiceChagres,                                          
  Lat,                                          
  Lang,                                        
  Nationalty,                                      
  ispricechange,                        
  SPublishedBaseRate,                                    
  SPublishedRate,                                    
  STotalRate,                                    
  SBaseRate,                                    
  SComission,               
  SCurrency,                                  
  Refundable,                                
  SupplierChargesPer,                 
  SupplierCharges,                                
  VccPer,                                
  VccValue,                        
  SINRCommissionAmount,                          
  SCommissionDiscription,                    
  HotelIncludes,                  
  MembershipNumber,                
  ChainName,              
  PanCardURL,            
  providerConfirmationNumber,    
  PNRofficeId,  
  PNRRateType,
  FreeTextPNRInclusion,
  FreeTextPNRRoomCategory)            
  Values(@LeaderTitle,                                                                                      
  @LeaderFirstName,                                                                                                                                                                                         
  @LeaderLastName,                                                                               
  @CurrencyCode,                                                                                            
  @HotelName,                                                                                                              
  @CountryName,                                                                                                      
  @BookingCountry,                                                                                                  
  @HotelAddress1,                                                                                  
  @CurrentStatus,                                                                                                              
  @TotalAdults,                                                                                   
  @TotalChildren,                                      
  @TotalRooms,                                                                   
  @CheckInDate,                                                                                                              
  @CheckOutDate,                                                                                                              
  @HotelRating,                                                       
  @SelectedNights,                                                                                                              
  @PassengerPhone,                                                                                                              
  @PassengerEmail,                                                               
  GETDATE(),                                                                        
  @cityName,                                                                                                              
  @SupplierName,                                                                                                        
  @B2BPaymentMode,                              
  @DisplayDiscountRate,                                                     
  @MainAgentID,                                                                                                              
  @Meal,                                                                                                              
  @TotalRoomAmount,                                                                                   
  @TotalSummaryAmount,          
  @AlertEmail,                                                                      
  @SearchApiId,                                                                                                              
  @HotelId,                                                                                                              
  @OrderId,                                                                                             
  @ExpectedPrize,                                                                             
  @SectionUniqueId,                                                              
  @AgentId,                                                                                                              
  @BookingReference,                                                                                 
  @TotalCharges,                                                                                                              
  @HotelCityId,                                                                                                                                     
  @ExpectedPrize,                                                    
  @FullRefund,                                                                          
  @SpecialRemark,                                                                                 
  @SupplierId,                                                                                                                                                  
  @ExpectedPrize,                                                    
  @ReferenceName,                                                                                                    
  @OBTCNumber,                                                         
  @CancellationDeadLine,                                                                                                      
  @IsPANMandatory,                                                                                                      
  @IsGSTRequired,                                                                                              
  @MarkupCurrency,                                                   
  @CheckinTime,                                                                                          
  @CheckOutTime,                                                                                        
  @AmountAfterPgCommision,                                                                                        
  @AmountBeforePgCommission,                                                                                      
  @PayAtHotel,                                                                                    
  @HotelTaxes,                            
  @HotelTotalGross,                                                                                
  @AgentCommission,                                                                             
  @HotelTDS,                                                                              
  @HotelPhone,                                                                            
  @CancellationPolicy,               
  @RiyaPNR,                                                    
  'RetrivePNR',                                                                  
  @AccountId,                                                                  
  @ChannelId,                                                                
  @SupplierCurrency,                                                              
  @RiyaSubUserId,                               
  @RiyaSubUserId,                                                      
  @CancellationDeadLine,                                             
  @HotelTotalPaybleAmountOld,                                                
  @SupplierBookingPaymentDate,                                              
  @SupplierPkId,                                            
  @GstOnServiceCharges,                                              
  @ServiceCharges,                                              
  @TotalServiceCharges,                                          
  @GstAmountOnServiceChagres,                                          
  @lat,                                          
  @lang,                                        
  @Nationalty,                                      
  @IsPriceChange,                                    
  @SPublishedBaseRate,                                    
  @SPublishedRate,                                    
  @STotalRate,          
  @SBaseRate,                                    
  @SComission,                                    
  @SCurrency,                                  
  @FullRefund,                                
  @SupplierChargesPer,                                
  @SupplierCharges,                                
  @VccPer,                                
  @VccValue,                        
  @SINRCommissionAmount,                          
  @SCommissionDiscription,                    
  @HotelIncludes,                  
  @MembershipNumber,                
  @ChainName,              
  @DocumentUrl,            
  @providerConfirmationNumber,    
  @PNRofficeId,  
  @PNRRateType,
  @FreeTextPNRInclusion,
  @FreeTextPNRRoomCategory)            
  set @book_pk_id  =(select  SCOPE_IDENTITY())            
  insert into Hotel_Status_History                                                                                                                   
    (                           
     FKHotelBookingId                                                       
    ,FkStatusId                                                                                                                    
    ,CreateDate                                                                        
    ,CreatedBy                                                                                                              
    ,ModifiedDate                                                                         
    ,IsActive                                                                 
    ,MainAgentId                              
 ,MethodName                                                                                                      
    )                                                                                                                                            
    values                                                                                                                                            
    (                                               
     @book_pk_id                                       
    ,'9'                                                                                                        
    ,SYSDATETIME()                                                                                                                                   
    ,@AgentId                                                                                     
    ,null                                                                                          
    ,1                  
   ,@MainAgentID                                                                    
  ,@MethodName                                                         
    )                                                                                                                                      
      select @book_pk_id;              
 End            
 Else            
 Begin         
 update Hotel_BookMaster Set BookingReference=@BookingReference where providerConfirmationNumber=@providerConfirmationNumber           
 Select  pkId from Hotel_BookMaster where providerConfirmationNumber=@providerConfirmationNumber            
 End            
END