CREATE Procedure Proc_InsertRetrivePNRRoomDetails                        
@roomtypeDescription varchar(100)='',                        
@NumberOfRoom varchar(10)='',                            
@book_fk_id bigint=0,                         
@RoomId  varchar(100)=0,                      
@numOfAdults bigint=0,                      
@numOfChildren bigint=0,                      
@RoomMealBasis varchar(500)='',                    
@rateid varchar(100)='',                    
@RoomRate float=0,                    
@RoomNo bigint=0,                  
@Supplierid varchar(200)='',                  
@publishedBaseRate float=0,                   
@publishedRate float=0,                   
@supplierCurrency varchar(50)='',                  
@totalRate float=0,                   
@baseRate float=0,              
@SupplierCommission float=0,            
@RpublishedRate   float=0,              
@RbaseRate   float=0,             
@Rfees   float=0,             
@Rdiscounts   float=0,               
@RFinalPrice   float=0,               
@Rmarkup   float=0,              
@Staxes   float=0,          
@GstOnServiceCharges float=0,          
@ServiceCharges float=0,          
@TotalServiceCharges float=0,          
@GstAmountOnServiceChagres float=0,        
@SupplierRateInBookingCurrency float=0        
As                        
Begin   
If NOT Exists(Select room_no, * from Hotel_Room_master where book_fk_id=@book_fk_id)      
 Begin      
	Insert into Hotel_Room_master                         
 (RoomTypeDescription,                        
 NumberOfRoom,                        
 book_fk_id,                        
 inserteddate,                        
 room_class_id,                     
 room_no,                    
 numOfAdults,                      
 numOfChildren,                      
 RoomMealBasis,                    
 RateId,                    
 RoomRate,                  
 Supplierid,                  
 publishedBaseRate,                  
 publishedRate,                  
 supplierCurrency,                  
 totalRate,                  
 baseRate,              
 SupplierCommission,            
 RpublishedRate,            
 RbaseRate,            
 Rfees,            
 Rdiscounts,            
 RFinalPrice,            
 Rmarkup,            
 Staxes,          
 GstOnServiceCharges,          
 ServiceCharges,          
 TotalServiceCharges,          
 GstAmountOnServiceChagres,        
 SupplierRateInBookingCurrency)              
 values                        
 (@roomtypeDescription,                        
 @NumberOfRoom,                        
 @book_fk_id,                        
 Getdate(),                      
 @RoomId,                    
 @RoomNo,                      
 @numOfAdults,                      
 @numOfChildren,                      
 @RoomMealBasis,                    
 @rateid,                    
 @RoomRate,                  
 @Supplierid,                  
 @publishedBaseRate,                  
 @publishedRate,                  
 @supplierCurrency,                  
 @totalRate,                  
 @baseRate,              
 @SupplierCommission,            
 @RpublishedRate,            
 @RbaseRate,            
 @Rfees,            
 @Rdiscounts,            
 @RFinalPrice,            
 @Rmarkup,            
 @Staxes,          
 @GstOnServiceCharges,          
 @ServiceCharges,          
 @TotalServiceCharges,          
 @GstAmountOnServiceChagres,        
 @SupplierRateInBookingCurrency)                        
	select   SCOPE_IDENTITY() 
  END
  Else
  Begin
	Select room_no, * from Hotel_Room_master where book_fk_id=@book_fk_id
  End
End 