CREATE PROCEDURE [dbo].[RTTBilling_GetAllPNR]
	@PNRType Varchar(10)
AS
BEGIN
	SET NOCOUNT ON;

    IF (@PNRType = 'LCC')
	BEGIN
		SELECT PNRNo FROM LCC WHERE IsPush IS NULL GROUP BY PNRNo
	END
	ELSE IF (@PNRType = 'FSC')
	BEGIN
		SELECT PNRNo FROM FSC WHERE IsPush IS NULL GROUP BY PNRNo
	END

END