CREATE proc [dbo].[SP_InsertAgentDiscount_FM] 
@MarketPoint VARCHAR(30),   
@AirportType VARCHAR(50),   
@AirLineCode VARCHAR(30),   
@TravelValidity_From datetime,   
@TravelValidity_To datetime,   
@SalesValidity_From datetime,   
@SalesValidity_To datetime,   
@RBD bit,   
@RBDValue VARCHAR(max)= NULL,   
@FareBasis bit,   
@FareBasisValue VARCHAR(max)= NULL,   
@AgentCategory VARCHAR(max)= NULL,   
@AgencyNames VARCHAR(max)= NULL,   
@AgencyId VARCHAR(max)= NULL,   
@Origin bit,   
@OriginValue VARCHAR(max)= NULL,   
@Destination bit,   
@DestinationValue VARCHAR(max)= NULL,   
@FlightSeries bit,   
@FlightSeriesValue VARCHAR(max)= NULL,   
@Remark VARCHAR(100)= NULL,   
@FlightNo VARCHAR(max),   
@Cabin VARCHAR(max),   
@PricingCode VARCHAR(max)= NULL,   
@TourCode VARCHAR(max)= NULL,   
@Commission DECIMAL(18, 2)= NULL,   
@IATADealtype nvarchar(10)= NULL,   
@IATADealPercent DECIMAL(18, 2)= NULL,   
@PLBDealType nvarchar(10)= NULL,   
@PLBDealPercent DECIMAL(18, 2)= NULL,   
@CRSType VARCHAR(max)= NULL,   
@AvailabilityPCC VARCHAR(max)= NULL,   
@PNRCreationPCC VARCHAR(max)= NULL,   
@TicketingPCC VARCHAR(max)= NULL,   
@IATADiscountType INT = NULL,   
@PLBDiscountType INT = NULL,   
@CardMapping1 INT = NULL,   
@CardMapping2 INT = NULL,   
@CardMapping3 INT = NULL,   
@CardMapping4 INT = NULL,   
@CardMapping5 INT = NULL,   
@Endorsementline VARCHAR(50)= NULL,   
@FlightNoCheck bit,   
@UserType VARCHAR (50)= NULL,   
@UserID INT,   
@AircodeList VARCHAR(max),   
@FareType VARCHAR(max)= NULL,   
@MarkupType INT = NULL,   
@MarkupAmount DECIMAL(18, 2)= NULL,   
@MarkupDealType nvarchar(10)= NULL,   
@PaxType VARCHAR(100)= NULL,   
@DropNetCommission DECIMAL(18, 2)= NULL,   
@LoginId VARCHAR (max)= NULL,   
@GST decimal(18, 2)=NULL,       
@TDS decimal(18, 2)=NULL,     
@GDSDiscountType int=null,    
@GDSDealType int=null, 
@GDSCommission decimal(18, 2)=null,  
@NetRemitCode varchar(30)=null,
@EmailId varchar(max)=null,
@Queueno varchar(500)=null,
@TktAccess bit,
@OTP varchar(30)=null,
@OriginCountry VARCHAR(MAX)=NULL,
@DestinationCountry VARCHAR(MAX)=NULL,
@ERROR VARCHAR(50) OUT 
AS 

--if  exists(select id from Flight_Commission where AgentCategory=@AgentCategory and MarketPoint=@MarketPoint and userType=@userType) and (@AgentCategory !='') --begin -- set @ERROR=  'Category already exist' --end -- ELSE IF EXISTS (  
  
  --Commented by bhavika
 -- SELECT id  FROM flight_commission WHERE marketpoint = @MarketPoint AND usertype = @userType --       and @TravelValidity_From between TravelValidityFrom and TravelValidityTo and @TravelValidity_To between TravelValidityFrom and TravelValidityTO --    AND @SalesValidity_From between SaleValidityFrom and SaleValidityTo
 --AND @SalesValidity_To between SaleValidityFrom and SaleValidityTo --    and airlinetype in( select DATA from sample_split(@AircodeList,',')) and FareType=@FareType)  --BEGIN --  
 -- SET   
 --   @ERROR = 'Record already exist' --END 
	
 begin   
 insert into Flight_Commission  
 ( MarketPoint, AirportType, AirlineType, UserType, TravelValidityFrom, TravelValidityTo, SaleValidityFrom, SaleValidityTo, RBD, RBDValue,
 FareBasis, FareBasisValue, Agencyid,   
 agencynames,   
    agentcategory,   
    origin,   
    originvalue,   
    destination,   
    destinationvalue,   
    flightseries,   
    flightseriesvalue,   
    inserteddate,   
    remark,   
    flag,   
    [FlightNovalue],   
    [Cabin],   
    pricingcode,   
    tourcode,   
    commission,   
    iatadealtype,   
    iatadealpercent,   
    plbdealtype,   
    plbdealpercent,   
    crstype,   
    availabilitypcc,   
    pnrcreationpcc,   
    ticketingpcc,   
    iatadiscounttype,   
    plbdiscounttype,   
    cardmapping1,   
    cardmapping2,   
    cardmapping3,   
    cardmapping4,   
    cardmapping5,   
    endorsementline,   
    flightno,   
    userid,   
    faretype,   
    markuptype,   
    markupamount,   
    markupdealtype,   
    paxtype,   
    dropnetcommission,   
    loginid,  
 GST,      
TDS,    
GDSDealType,    
GDSDiscountType,
GDSCommission,
NetRemitCode,
Queueno,
EmailId,
TicketingAccess,
OTP,OriginCountry,DestinationCountry
)   
VALUES   
  (  
    @MarketPoint,   
    @AirportType,   
    @AircodeList,   
    @UserType,   
    @TravelValidity_From,   
    dateadd(s, 86399, @TravelValidity_To),   
    @SalesValidity_From,   
    dateadd(s, 86399, @SalesValidity_To),   
    @RBD ,   
    @RBDValue,   
    @FareBasis,   
    @FareBasisValue,   
    @AgencyId,   
    @AgencyNames,   
    @AgentCategory,   
    @Origin ,   
    @OriginValue,   
    @Destination,   
    @DestinationValue,   
    @FlightSeries,   
    @FlightSeriesValue,   
    getdate(),   
    @Remark,   
    1,   
    @FlightNo,   
    @Cabin,   
    @PricingCode,   
    @TourCode,   
    @Commission,   
    @IATADealType,   
    @IATADealPercent,   
    @PLBDealType,   
    @PLBDealPercent,   
    @CRSType,   
    @AvailabilityPCC,   
    @PNRCreationPCC,   
    @TicketingPCC,   
    @IATADiscountType,   
    @PLBDiscountType,   
    @CardMapping1,   
    @CardMapping2,   
    @CardMapping3,   
    @CardMapping4,   
    @CardMapping5,   
    @Endorsementline,   
    @FlightNoCheck,   
    @UserID,   
    @FareType,   
    @MarkupType,   
    @MarkupAmount,   
    @MarkupDealType,   
    @PaxType,   
    @DropNetCommission,   
    @LoginId,  
 @GST,      
@TDS,    
@GDSDealType,    
@GDSDiscountType,
@GDSCommission,
@NetRemitCode,
@Queueno,
@EmailId,
@TktAccess,
@OTP,@OriginCountry,@DestinationCountry
  ) 
  end 

GO
GRANT VIEW DEFINITION
    ON OBJECT::[dbo].[SP_InsertAgentDiscount_FM] TO [rt_read]
    AS [dbo];

