CREATE proc [dbo].[SP_InsertAgentDiscount_MarkupType]
@MarketPoint varchar(30),
@AirportType varchar(50),
@AirLineCode varchar(30),
@PaxType varchar(50),
@Remark varchar(max),
@TravelValidity_From datetime,
@TravelValidity_To datetime,
@SalesValidity_From datetime,
@SalesValidity_To datetime,
@GroupType varchar(50),
@Name varchar(100),
@FareTypeRU varchar(50),
@CalTypeRU varchar(50),
@ValPErRU int=0,
@FareTypeRP varchar(50),
@CalTypeRP varchar(50),
@ValPErRP int=0,
@FareTypeM varchar(50),
@CalTypeM varchar(50),
@ValPErM int=0,
@RUMaxAmt numeric(18,2)=0,
@RPMaxAmt numeric(18,2)=0,
@MMaxAmt numeric(18,2)=0,
@DisplayTypeRP INT,
@DisplayTypeRU INT,
@DisplayTypeM int,
@BookingTypeRP INT,
@BookingTypeRU INT,
@BookingTypeM int,
@UserType varchar(50)=null,
@AgencyId varchar(MAX)=null,
@AgentCategory varchar(MAX)=null,
@AgencyNames varchar(MAX)=null,
@UserID int,
@AircodeList varchar(max),
@RBD  bit,
@RBDValue varchar(max)=null,
@FareBasis bit,
@FareBasisValue varchar(max)=null,
@Origin  bit,
@OriginValue varchar(max)=null,
@Destination bit,
@DestinationValue varchar(max)=null,
@FlightSeries bit,
@FlightSeriesValue varchar(max)=null,
@FlightNoCheck bit,
@FlightNo varchar(max),
@Cabin varchar(max),
@TransactionType varchar(50),
@CRSType  varchar(50), 
@AvailabilityPCC varchar(50),
@OriginCountry VARCHAR(MAX)=NULL,
@DestinationCountry VARCHAR(MAX)=NULL,
@ERROR VARCHAR(50) OUT 
as
begin

--if  exists(select id from Flight_MarkupType where AgentCategory=@AgentCategory and MarketPoint=@MarketPoint and userType=@userType) and (@AgentCategory !='')
--begin
--	set @ERROR=  'Category already exist'
--end
--ELSE if exists(select id from Flight_MarkupType where  MarketPoint=@MarketPoint and userType=@userType 
--	      and @TravelValidity_From between TravelValidityFrom and TravelValidityTo and @TravelValidity_To between TravelValidityFrom and TravelValidityTo 
--		  AND @SalesValidity_From between SaleValidityFrom and SaleValidityTo AND @SalesValidity_To between SaleValidityFrom and SaleValidityTo
--		  and airlinetype in( select DATA from sample_split(@AircodeList,','))) 
--BEGIN
--	set @ERROR=  'Record already exist'
--END 

insert into Flight_MarkupType 
				(
				MarketPoint,
				AirportType,
				AirlineType,
				PaxType,
				Remark,
				TravelValidityFrom,
				TravelValidityTo,
				SaleValidityFrom,
				SaleValidityTo,
				InsertedDate,
				GroupType,
				Name,
				Flag,
				FareTypeRU,
				CalculationTypeRU,
				ValPerRU,
				FareTypeRP,
				CalculationTypeRP,
				ValPerRP,
				RUMaxAmt,
				RPMaxAmt,
				DisplayTypeRP,
				DisplayTypeRU,				
				BookingTypeRP,
				BookingTypeRU,				
				UserType,
				AgencyId ,
				AgentCategory,
				AgencyNames,
				UserID,
				RBD,
				RBDValue,
				FareBasis,
				FareBasisValue,
				Origin,
				OriginValue,
				Destination,
				DestinationValue,
				FlightSeries,
				FlightSeriesValue,
				FlightNo,
				FlightNoValue,
				Cabin,				
				FareTypeM,
				CalculationTypeM,
				ValPerM,
				MmaxAmt,
				DisplayTypeM,
				BookingTypeM,
				 TransactionType,
	CRSType,
	AvailabilityPCC,OriginCountry,DestinationCountry
				)
				values
				(
				@MarketPoint,
				@AirportType,
				@AircodeList,
				@PaxType,
				@Remark,
				@TravelValidity_From,
				DATEADD(s, 86399,@TravelValidity_To),
				@SalesValidity_From,
				DATEADD(s, 86399,@SalesValidity_To),
				GETDATE(),
				@GroupType,
				@Name,
				1,
				@FareTypeRU,
				@CalTypeRU,
				@ValPErRU,
				@FareTypeRP,
				@CalTypeRP,
				@ValPErRP,
				@RUMaxAmt,
				@RPMaxAmt,
				@DisplayTypeRP,
				@DisplayTypeRU,
				@BookingTypeRP,
				@BookingTypeRU,
				@UserType,
				@AgencyId ,
				@AgentCategory,
				@AgencyNames,
				@UserID,
				@RBD,
				@RBDValue,
				@FareBasis,
				@FareBasisValue,
				@Origin,
				@OriginValue,
				@Destination,
				@DestinationValue,
				@FlightSeries,
				@FlightSeriesValue,
				@FlightNoCheck,
				@FlightNo,
				@Cabin, 
				@FareTypeM,
				@CalTypeM,
				@ValPErM,
				@MMaxAmt,
				@DisplayTypeM,
				@BookingTypeM,
				 @TransactionType,
	@CRSType, 
	@AvailabilityPCC,@OriginCountry,@DestinationCountry)

END

GO
GRANT VIEW DEFINITION
    ON OBJECT::[dbo].[SP_InsertAgentDiscount_MarkupType] TO [rt_read]
    AS [dbo];

