CREATE proc [dbo].[SP_InsertAgentDiscountFM]      
      
@MarketPoint varchar(30),      
@AirportType varchar(50),      
@AirLineCode varchar(30),      
@TravelValidity_From datetime,      
@TravelValidity_To datetime,      
@SalesValidity_From datetime,      
@SalesValidity_To datetime,      
@RBD  bit,      
@RBDValue varchar(max)=null,      
@FareBasis bit,      
@FareBasisValue varchar(max)=null,      
@AgentCategory varchar(max)=null,      
@AgencyNames varchar(max)=null,      
@AgencyId varchar(max)=null,      
@Origin  bit,      
@OriginValue varchar(max)=null,      
@Destination bit,      
@DestinationValue varchar(max)=null,      
@FlightSeries bit,      
@FlightSeriesValue varchar(max)=null,      
@Remark varchar(max)= null,      
@FlightNo varchar(max),      
@Cabin varchar(max),      
@PricingCode varchar(max)=NULL,      
@TourCode varchar(max)=NULL,      
@Commission decimal(18, 2)=null,      
@IATADealType NVARCHAR(10)=NULL,      
@IATADealPercent decimal(18, 2)=NULL,      
@PLBDealType NVARCHAR(10)=NULL,      
@PLBDealPercent decimal(18, 2)=NULL,      
@CRSType varchar(max)=NULL,      
@AvailabilityPCC varchar(max)=NULL,      
@PNRCreationPCC varchar(max)=NULL,      
@TicketingPCC varchar(max)=NULL,      
@IATADiscountType int=null,      
@PLBDiscountType int=null,      
@CardMapping1 int=null,      
@CardMapping2 int=null,      
@CardMapping3 int=null,      
@CardMapping4 int=null,      
@CardMapping5 int=null,      
@Endorsementline varchar(50)=null,      
@FlightNoCheck bit,      
@UserType varchar(50)=null,      
@UserID int,      
@AircodeList varchar(max),      
@FareType varchar(max)=null,      
@MarkupType int=null,      
@MarkupAmount decimal(18, 2)=NULL,      
@MarkupDealType NVARCHAR(10)=NULL,      
@PaxType varchar(100)=null,      
@DropNetCommission decimal(18,2)=null,      
@LoginId varchar(max)=null,      
@Paymode  VARCHAR(50)=null,      
@VCName VARCHAR(50)=null,     
@GST decimal(18, 2)=NULL,     
@TDS decimal(18, 2)=NULL,   
@GDSDiscountType int=null,  
@GDSDealType int=null, 
@GDSCommission decimal(18, 2)=null,
@AdditionalAmtType varchar(30)=null,
@AdditionalAmount decimal(18,2)=null,
@NetRemitCode varchar(30)=null,
@ConfigurationType varchar(200)=null,
@SOTO bit,
@Currency varchar(20)=null,
@Discounttype varchar(200)=null,
@Percentage decimal(18, 2)=null,
@LimitValue decimal(18, 2)=null,
@Hup_Amt decimal(18, 2)=null,
@Fromval decimal(18, 2)=null,
@Toval decimal(18, 2)=null,
@EmailId varchar(max)=null,
@Queueno varchar(500)=null,
@AutoTkt bit,
@TktAccess bit,
@OTP varchar(30)=null,
@OriginCountry VARCHAR(MAX)=NULL,
@DestinationCountry VARCHAR(MAX)=NULL,
@AgentLogin VARCHAR(100)=NULL,
@Password VARCHAR(100)=NULL,
@IATA VARCHAR(100)=NULL,
@AgentIdentifier VARCHAR(100)=NULL,
@ViaPoint BIT=0,
@ViaPointValue VARCHAR(MAX)=NULL,
@ERROR VARCHAR(50) OUT      
as      
Begin      
--if  exists(select id from Flight_Commission where AgentCategory=@AgentCategory and MarketPoint=@MarketPoint and userType=@userType) and (@AgentCategory !='')      
--begin      
-- set @ERROR=  'Category already exist'      
--end      
      
      
--ELSE      
      
--begin      
      
 insert into FlightCommission       
(      
MarketPoint,      
AirportType,      
AirlineType,      
UserType,      
TravelValidityFrom,      
TravelValidityTo,      
SaleValidityFrom,      
SaleValidityTo,      
RBD,      
RBDValue,      
FareBasis,      
FareBasisValue,      
AgencyId,      
AgencyNames,      
AgentCategory,      
Origin,      
OriginValue,      
Destination,      
DestinationValue,      
FlightSeries,      
FlightSeriesValue,      
InsertedDate,      
Remark,      
Flag,      
[FlightNovalue],      
[Cabin],      
PricingCode,      
TourCode,      
Commission,      
IATADealType,       
IATADealPercent,       
PLBDealType,       
PLBDealPercent,      
CRSType,      
AvailabilityPCC,      
PNRCreationPCC,      
TicketingPCC,      
IATADiscountType,      
PLBDiscountType,      
CardMapping1,      
CardMapping2,      
CardMapping3,      
CardMapping4,      
CardMapping5,      
Endorsementline,      
FlightNo,      
UserID,      
FareType,      
MarkupType,      
MarkupAmount,      
MarkupDealType,      
PaxType,      
DropnetCommission,      
LoginId,      
PayMode,      
VirtualCardName,    
GST,    
TDS,  
GDSDealType,  
GDSDiscountType,
gdscommission,
AdditionalAmount,
AdditionalAmtType,
NetRemitCode,
ConfigurationType,
SOTO,
[Discounttype]
      ,[Percentage]
      ,[LimitValue]
      ,[Currency]
      ,[HUP_Amount]
      ,[FromValue]
      ,[ToValue]
	 , AutoTicketing,
Queueno,
EmailId,
TicketingAccess,
OTP,OriginCountry,DestinationCountry,AgentLogin,Password,IATA,AgentIdentifier,ViaPoint,ViaPointValue
)      
Values      
(      
@MarketPoint ,      
@AirportType ,      
@AircodeList ,      
@UserType,      
@TravelValidity_From ,      
DATEADD(s,86399,@TravelValidity_To),      
@SalesValidity_From ,      
DATEADD(s,86399,@SalesValidity_To),      
@RBD  ,      
@RBDValue ,      
@FareBasis ,      
@FareBasisValue ,      
@AgencyId,      
@AgencyNames,      
@AgentCategory,      
@Origin  ,      
@OriginValue ,      
@Destination ,      
@DestinationValue ,      
@FlightSeries ,      
@FlightSeriesValue ,      
getdate(),      
@Remark,      
1,      
@FlightNo,      
@Cabin,    
@PricingCode,      
@TourCode,      
@Commission,      
@IATADealType,       
@IATADealPercent,       
@PLBDealType,       
@PLBDealPercent,      
@CRSType,      
@AvailabilityPCC,      
@PNRCreationPCC,      
@TicketingPCC,      
@IATADiscountType,      
@PLBDiscountType,      
@CardMapping1,      
@CardMapping2,      
@CardMapping3,      
@CardMapping4,      
@CardMapping5,      
@Endorsementline,      
@FlightNoCheck,      
@UserID,      
@FareType,      
@MarkupType,      
@MarkupAmount,      
@MarkupDealType,      
@PaxType,      
@DropNetCommission,      
@LoginId,      
@Paymode,      
@VCName,    
@GST,    
@TDS,  
@GDSDealType,  
@GDSDiscountType,
@GDSCommission,
@AdditionalAmount,
@AdditionalAmtType,
@NetRemitCode,
@ConfigurationType,
@SOTO,
@Discounttype
      ,@Percentage
      ,@LimitValue
      ,@Currency
      ,@Hup_Amt
      ,@Fromval
      ,@Toval
	 , @AutoTkt,
@Queueno,
@EmailId,
@TktAccess,
@OTP,@OriginCountry,@DestinationCountry,@AgentLogin,@Password,@IATA,@AgentIdentifier,@ViaPoint,@ViaPointValue
)      

	SET @ERROR=SCOPE_IDENTITY()
      
--end      
      
End 

GO
GRANT VIEW DEFINITION
    ON OBJECT::[dbo].[SP_InsertAgentDiscountFM] TO [rt_read]
    AS [dbo];

