CREATE proc [dbo].[Update_FM] 
@ID int,   
@MarketPoint varchar(30),   
@AirportType varchar(50),   
@AirLineCode varchar(max),   
@UserType varchar(50),   
@FlightNo bit,   
@FlightNoValue varchar(max),   
@TravelValidity_From datetime,   
@TravelValidity_To datetime,   
@SalesValidity_From datetime,   
@SalesValidity_To datetime,   
@RBD  bit,   
@RBDValue varchar(max)= null,   
@FareBasis bit,   
@FareBasisValue varchar(max),   
@Origin  bit,   
@OriginValue varchar(max)= null,   
@Destination bit,   
@DestinationValue varchar(max)= null,   
@FlightSeries bit,   
@AgentCategory varchar(max)= null,   
@AgencyNames varchar(max)= null,   
@AgencyId varchar(max)= null,   
@FlightSeriesValue varchar(max)= null,   
@Remark varchar(max)= null,   
@Cabin varchar(max),   
@PricingCode varchar(max)= NULL,   
@TourCode varchar(max)= NULL,   
@Commission decimal(18, 2)= null,   
@IATADealType NVARCHAR(10)= NULL,   
@IATADealPercent decimal(18, 2)= NULL,   
@PLBDealType NVARCHAR(10)= NULL,   
@PLBDealPercent decimal(18, 2)= NULL,   
@CRSType varchar(max)= NULL,   
@AvailabilityPCC varchar(max)= NULL,   
@PNRCreationPCC varchar(max)= NULL,   
@TicketingPCC varchar(max)= NULL,   
@IATADiscountType int = null,   
@PLBDiscountType int = null,   
@CardMapping1 int = null,   
@CardMapping2 int = null,   
@CardMapping3 int = null,   
@CardMapping4 int = null,   
@CardMapping5 int = null,   
@Endorsementline varchar(50)= null,   
@UserID int,   
@FareType varchar(max)= null,   
@MarkupType int = null,   
@MarkupAmount decimal(18, 2)= NULL,   
@MarkupDealType NVARCHAR(10)= NULL,   
@PaxType varchar(100)= null,   
@DropNetCommission decimal(18, 2)= NULL,   
@LoginId varchar(max)= null,  
@GST decimal(18,2)=null,      
@TDS decimal(18,2)=null,    
@GDSDiscountType int=null,    
@GDSDealType varchar(20)=null ,
@GDSCommission decimal(18,2)=null,
@NetRemitCode varchar(30)=null,
@EmailId varchar(max)=null,
@Queueno varchar(500)=null,
@OTP varchar(30)=null,
@OriginCountry VARCHAR(MAX)=NULL,
@DestinationCountry VARCHAR(MAX)=NULL,
@TktAccess bit
  
AS 
BEGIN 
insert into Flight_CommissionHistory (  
  ParentId,[Action], TravelValidityFrom,   
  TravelValidityTo, SaleValidityFrom,   
  SaleValidityTo, RBD, RBDValue, FareBasis,   
  FareBasisValue, AgencyNames, Origin,   
  OriginValue, Destination, DestinationValue,   
  FlightSeries, FlightSeriesValue,   
  Remark, Flag, [FlightNovalue], [Cabin],   
  PricingCode, TourCode, Commission,   
  IATADealType, IATADealPercent, PLBDealType,   
  PLBDealPercent, CRSType, AvailabilityPCC,   
  PNRCreationPCC, TicketingPCC, IATADiscountType,   
  PLBDiscountType, CardMapping1, CardMapping2,   
  CardMapping3, CardMapping4, CardMapping5,   
  Endorsementline, FlightNo, ModifiedBy,   
  FareType, MarkupType, MarkupAmount,   
  MarkupDealType, PaxType, DropnetCommission,   
  LoginId,  
  GST,      
TDS,    
GDSDiscountType,    
GDSDealType   ,
GDSCommission,
NetRemitCode,
Queueno,
EmailId,
TicketingAccess,
OTP,OriginCountry,DestinationCountry
)   
select   
  Id,   
  'Update',   
  TravelValidityFrom,   
  TravelValidityTo,   
  SaleValidityFrom,   
  SaleValidityTo,   
  RBD,   
  RBDValue,   
  FareBasis,   
  FareBasisValue,   
  AgencyNames,   
  Origin,   
  OriginValue,   
  Destination,   
  DestinationValue,   
  FlightSeries,   
  FlightSeriesValue,   
  Remark,   
  Flag,   
  [FlightNovalue],   
  [Cabin],   
  PricingCode,   
  TourCode,   
  Commission,   
  IATADealType,   
  IATADealPercent,   
  PLBDealType,   
  PLBDealPercent,   
  CRSType,   
  AvailabilityPCC,   
  PNRCreationPCC,   
  TicketingPCC,   
  IATADiscountType,   
  PLBDiscountType,   
  CardMapping1,   
  CardMapping2,   
  CardMapping3,   
  CardMapping4,   
  CardMapping5,   
  Endorsementline,   
  FlightNo,   
  @UserID,   
  FareType,   
  MarkupType,   
  MarkupAmount,   
  MarkupDealType,   
  PaxType,   
  DropnetCommission,   
  LoginId,  
  GST,      
TDS ,    
GDSDiscountType,    
GDSDealType    ,
@GDSCommission,
NetRemitCode,
Queueno,
EmailId,
TicketingAccess,
OTP,OriginCountry,DestinationCountry
from   
  Flight_Commission   
where   
  id = @ID   

update   
  Flight_Commission   
set   
  --MarketPoint= @MarketPoint, --AirportType=@AirportType,   
  AirlineType= @AirLineCode, UserType=@UserType, Remark=@Remark, TravelValidityFrom = @TravelValidity_From,   
  TravelValidityTo = DATEADD(s, 43199, @TravelValidity_To),   
  SaleValidityFrom = @SalesValidity_From,   
  SaleValidityTo = DATEADD(s, 43199, @SalesValidity_To),   
  RBD = @RBD,   
  RBDValue = @RBDValue,   
  FlightNo = @FlightNo,   
FlightNoValue = @FlightNoValue,   
  FareBasis = @FareBasis,   
  FareBasisValue = @FareBasisValue,   
  FlightSeries = @FlightSeries,   
  FlightSeriesValue = @FlightSeriesValue,   
  Origin = @Origin,   
  OriginValue = @OriginValue,   
  Destination = @Destination,   
  DestinationValue = @DestinationValue,   
  AgencyNames = @AgencyNames,   
  AgentCategory = @AgentCategory,   
  AgencyId = @AgencyId,   
  Cabin = @Cabin,   
  PricingCode = @PricingCode,   
  TourCode = @TourCode,   
  Commission = @Commission,   
  IATADealType = @IATADealType,   
  IATADealPercent = @IATADealPercent,   
  PLBDealType = @PLBDealType,   
  PLBDealPercent = @PLBDealPercent,   
  CRSType = @CRSType,   
  AvailabilityPCC = @AvailabilityPCC,   
  PNRCreationPCC = @PNRCreationPCC,   
  TicketingPCC = @TicketingPCC,   
  IATADiscountType = @IATADiscountType,   
  PLBDiscountType = @PLBDiscountType,   
  CardMapping1 = @CardMapping1,   
  CardMapping2 = @CardMapping2,   
  CardMapping3 = @CardMapping3,   
  CardMapping4 = CardMapping4,   
  CardMapping5 = @CardMapping5,   
  Endorsementline = @Endorsementline,   
  UserID = @UserID,   
  UpdatedDate = GETDATE(),   
  FareType = @FareType,   
  MarkupType = @MarkupType,   
  MarkupAmount = @MarkupAmount,   
  MarkupDealType = @MarkupDealType,   
  PaxType = @PaxType,   
  DropnetCommission = @DropNetCommission,   
  LoginId = @LoginId,  
  GST=@GST,      
TDS=@TDS,    
GDSDiscountType=@GDSDiscountType,    
GDSDealType=@GDSDealType ,
GDSCommission=@GDSCommission,
  NetRemitCode=@NetRemitCode,
  Queueno=@Queueno,
EmailId=@EmailId,
TicketingAccess=@TktAccess,
OTP=@OTP,OriginCountry=@OriginCountry,DestinationCountry=@DestinationCountry
where   
  ID = @ID 
  end 

GO
GRANT VIEW DEFINITION
    ON OBJECT::[dbo].[Update_FM] TO [rt_read]
    AS [dbo];

