CREATE proc [dbo].[Update_MarkupType]          
@ID int,          
@MarketPoint varchar(30),          
@AirportType varchar(50),          
@AirLineCode varchar(max),          
@PaxType varchar(50),          
@Remark varchar(max),          
@TravelValidity_From datetime,          
@TravelValidity_To datetime,          
@SalesValidity_From datetime,          
@SalesValidity_To datetime,          
@GroupType varchar(50),          
@Name varchar(100),          
@FareTypeRU varchar(50),          
@CalTypeRU varchar(50),          
@ValPErRU numeric(18, 2)=0,          
@FareTypeRP varchar(50),          
@CalTypeRP varchar(50),          
@ValPErRP numeric(18, 2)=0,          
@RUMaxAmt numeric(18, 2)=0,          
@RPMaxAmt numeric(18, 2)=0,          
@DisplayTypeRP INT,          
@DisplayTypeRU INT,          
@BookingTypeRP INT,          
@BookingTypeRU INT,          
@UserType varchar(50)=null,          
@AgencyId varchar(MAX)=null,          
@AgentCategory varchar(MAX)=null,          
@AgencyNames varchar(MAX)=null,          
@AircodeList varchar(max),          
@UserID int,          
@RBD  bit,          
@RBDValue varchar(max)=null,          
@FareBasis bit,          
@FareBasisValue varchar(max)=null,          
@Origin  bit,          
@OriginValue varchar(max)=null,          
@Destination bit,          
@DestinationValue varchar(max)=null,          
@FlightSeries bit,          
@FlightSeriesValue varchar(max)=null,          
@FlightNoCheck bit,          
@FlightNo varchar(max),          
@Cabin varchar(max),          
@FareTypeM varchar(50),          
@CalTypeM varchar(50),          
@ValPErM int=0,          
@MMaxAmt numeric(18,2)=0,          
@DisplayTypeM int,          
@BookingTypeM int,          
@TransactionType varchar(50),          
@CRSType  varchar(50),         
@OriginCountry VARCHAR(MAX)=NULL,        
@DestinationCountry VARCHAR(MAX)=NULL,        
@AvailabilityPCC  varchar(50)        
          
as          
begin          
      
INSERT INTO [dbo].[Flight_MarkupTypeHistory]      
           ([Action],  MarketPoint ,AirportType,          
AirlineType,PaxType,Remark,TravelValidityFrom,          
TravelValidityTo,          
SaleValidityFrom,          
SaleValidityTo,                  
GroupType,          
Name,          
FareTypeRU,          
CalculationTypeRU,          
ValPerRU,          
FareTypeRP,          
CalculationTypeRP,          
ValPerRP,          
RUMaxAmt,          
RPMaxAmt,          
DisplayTypeRP,          
DisplayTypeRU,          
BookingTypeRP,          
BookingTypeRU,          
UserType,          
AgencyId,          
AgentCategory,          
AgencyNames,          
UserID,          
UpdatedDate,          
RBD,          
RBDValue,          
FareBasis,          
FareBasisValue,          
Origin,          
OriginValue,          
Destination,          
DestinationValue,          
FlightSeries,          
FlightSeriesValue,          
FlightNo,          
FlightNoValue,          
Cabin,          
FareTypeM,          
CalculationTypeM,          
ValPerM,          
MmaxAmt,          
DisplayTypeM,          
BookingTypeM,          
TransactionType,        
CRSType,        
AvailabilityPCC,        
OriginCountry,        
DestinationCountry )      
      
     select 'Edit', MarketPoint ,          
AirportType,          
AirlineType,          
PaxType,          
Remark,          
TravelValidityFrom,          
TravelValidityTo,          
SaleValidityFrom,          
SaleValidityTo,                 
GroupType,          
Name,          
FareTypeRU,          
CalculationTypeRU,          
ValPerRU,          
FareTypeRP,          
CalculationTypeRP,          
ValPerRP,          
RUMaxAmt,          
RPMaxAmt,          
DisplayTypeRP,          
DisplayTypeRU,          
BookingTypeRP,          
BookingTypeRU,          
UserType,          
AgencyId,          
AgentCategory,          
AgencyNames,          
@UserID,          
getdate(),          
RBD,          
RBDValue,          
FareBasis,          
FareBasisValue,          
Origin,          
OriginValue,          
Destination,          
DestinationValue,          
FlightSeries,          
FlightSeriesValue,          
FlightNo,          
FlightNoValue,          
Cabin,          
FareTypeM,          
CalculationTypeM,          
ValPerM,          
MmaxAmt,          
DisplayTypeM,          
BookingTypeM,          
TransactionType,        
CRSType,        
AvailabilityPCC,        
OriginCountry,        
DestinationCountry  from Flight_MarkupType      
      where id=@ID      
          
Update Flight_MarkupType          
set              
      
MarketPoint = @MarketPoint,          
AirportType=@AirportType,          
AirlineType=@AircodeList,          
PaxType=@PaxType,          
Remark=@Remark,          
TravelValidityFrom = @TravelValidity_From,          
TravelValidityTo=DATEADD(s, 86399,@TravelValidity_To),          
SaleValidityFrom= @SalesValidity_From,          
SaleValidityTo= DATEADD(s, 86399,@SalesValidity_To),          
InsertedDate= GETDATE(),          
GroupType=@GroupType,          
Name= @Name,          
FareTypeRU =@FareTypeRU,          
CalculationTypeRU = @CalTypeRU,          
ValPerRU= @ValPErRU,          
FareTypeRP=@FareTypeRP,          
CalculationTypeRP= @CalTypeRP,          
ValPerRP=@ValPErRP,          
RUMaxAmt=@RUMaxAmt,          
RPMaxAmt=@RPMaxAmt,          
DisplayTypeRP=@DisplayTypeRP,          
DisplayTypeRU=@DisplayTypeRU,          
BookingTypeRP=@BookingTypeRP,          
BookingTypeRU=@BookingTypeRU,          
UserType=@UserType,          
AgencyId=@AgencyId,          
AgentCategory=@AgentCategory,          
AgencyNames=@AgencyNames,          
UserID=@UserID,          
UpdatedDate=GETDATE(),          
RBD=@RBD,          
RBDValue=@RBDValue,          
FareBasis=@FareBasis,          
FareBasisValue=@FareBasisValue,          
Origin=@Origin,          
OriginValue=@OriginValue,          
Destination=@Destination,          
DestinationValue=@DestinationValue,          
FlightSeries=@FlightSeries,          
FlightSeriesValue=@FlightSeriesValue,          
FlightNo=@FlightNoCheck,          
FlightNoValue=@FlightNo,          
Cabin=@Cabin ,          
FareTypeM=@FareTypeM,          
CalculationTypeM=@CalTypeM,          
ValPerM=@ValPErM,          
MmaxAmt=@MMaxAmt,          
DisplayTypeM=@DisplayTypeM,          
BookingTypeM=@BookingTypeM,          
TransactionType=@TransactionType,        
CRSType=@CRSType,        
AvailabilityPCC=@AvailabilityPCC,        
OriginCountry=@OriginCountry,        
DestinationCountry=@DestinationCountry        
where ID = @ID          
end 
GO
GRANT VIEW DEFINITION
    ON OBJECT::[dbo].[Update_MarkupType] TO [rt_read]
    AS [dbo];

