              
              
                
CREATE procedure [Hotel].[Api_Proc_InsertHotelTravelerDetails]                
@Salutation varchar(30)=null,                
@FirstName varchar(500)=null,                
@Middlename varchar(300)=null,                
@LastName varchar(300)=null,                
@PassengerType varchar(30)=null,                
@book_fk_id int=null,                
@orderId varchar(200)=null,                
@room_fk_id int=null,                
@Nationality int=null,                
@Contact varchar(50)=null,                
@Email varchar(300)=null,                
@RoomNo varchar(200)=null,                
@RoomType varchar(300)=null,                
@MealBasis varchar(300)=null,                
@PassportNo varchar(20)=null,                
@IssueDate datetime =null,                
@ExpiryDate datetime=null,                
@PancardNo varchar(30)=null,           
@PancardName varchar(200)=null,          
@IsLeadPax bit=null ,            
@PaxAge int = 0 ,    
@PassPortDOB datetime=null    
As                
Begin                
 insert into Hotel_Pax_master(                
 Salutation,                
 FirstName,                
 LastName,                
 PassengerType,                
 book_fk_id,                
 orderId,                
 room_fk_id,                
 Nationality,                
 Contact,                
 Email,                
 RoomNo,                
 RoomType,                
 MealBasis,                
 PassportNum,                
 IssueDate,                
 Expirydate,                
 Pancard,           
 PanCardName,          
 IsLeadPax,            
 Age,    
 inserteddate,    
 PassPortDOB)                
 values(                
 @Salutation,                
 @FirstName,                
 @LastName,                
 @PassengerType,                
 @book_fk_id,                
 @orderId,                
 @room_fk_id,                
 @Nationality,                
 @Contact,                
 @Email,                
 @RoomNo,                
 @RoomType,                
 @MealBasis,                
 @PassportNo,                
 @IssueDate,                
 @ExpiryDate,                
 @PancardNo,            
 @PancardName,          
 @IsLeadPax,            
 @PaxAge,    
 GETDATE(),    
 @PassPortDOB)                
 select  SCOPE_IDENTITY()                
END 