CREATE TABLE [dbo].[AgentLoginHistory] (
    [UserID]            BIGINT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [UserCode]          VARCHAR (10)    NULL,
    [UserName]          VARCHAR (500)   NOT NULL,
    [Password]          VARCHAR (300)   NULL,
    [FirstName]         VARCHAR (150)   NULL,
    [LastName]          VARCHAR (150)   NULL,
    [InsertedDate]      DATETIME        CONSTRAINT [DF_agentLogin_InsertedDate_hsitory] DEFAULT (getdate()) NOT NULL,
    [IsActive]          TINYINT         NULL,
    [MobileNumber]      VARCHAR (200)   NULL,
    [NewsLetter]        TINYINT         NULL,
    [Address]           VARCHAR (500)   NULL,
    [City]              VARCHAR (100)   NULL,
    [Country]           VARCHAR (100)   NULL,
    [Pincode]           VARCHAR (20)    NULL,
    [DrivingLicenceNo]  VARCHAR (20)    NULL,
    [HomeNo]            VARCHAR (20)    NULL,
    [IsB2BAgent]        BIT             NULL,
    [Province]          VARCHAR (50)    NULL,
    [BookingCountry]    VARCHAR (2)     NULL,
    [AgentApproved]     BIT             NULL,
    [SessionID]         VARCHAR (50)    NULL,
    [AgentBalance]      MONEY           NULL,
    [ParentAgentID]     BIGINT          NULL,
    [ResetPwdFlag]      BIT             CONSTRAINT [DF_agentLogin_ResetPwdFlag_hsitory] DEFAULT ((1)) NULL,
    [AccessFlag]        INT             NULL,
    [userTypeID]        INT             CONSTRAINT [DF_agentLogin_userTypeID_hsitory] DEFAULT ((2)) NULL,
    [BalanceUpdateDate] DATETIME        NULL,
    [FareType]          VARCHAR (MAX)   NULL,
    [NewCurrency]       VARCHAR (MAX)   NULL,
    [TicketFormate]     VARCHAR (10)    NULL,
    [AutoTicketing]     BIT             CONSTRAINT [DF_agentLogin_AutoTicketinghistory] DEFAULT ((0)) NULL,
    [ROE]               DECIMAL (18, 3) NULL,
    [ModifiedOn]        DATETIME2 (7)   NULL,
    [ModifiedBy]        INT             NULL,
    [GhostTrack]        BIT             CONSTRAINT [DF_agentLogin_GhostTrackhsitory] DEFAULT ((0)) NOT NULL,
    [NewSelfBalance]    BIT             CONSTRAINT [DF_agentLogin_NewSelfBalancehsitory] DEFAULT ((0)) NOT NULL,
    [modifyByAuto]      BIGINT          NULL,
    [modifyDateAuto]    DATETIME        NULL,
    [LoginFromCountry]  VARCHAR (MAX)   NULL,
    [OTPRequired]       BIT             NULL,
    [GroupId]           INT             NULL,
    [BalanceFetch]      VARCHAR (100)   NULL,
    CONSTRAINT [PK_UserIDhistory] PRIMARY KEY CLUSTERED ([UserID] ASC)
);

