CREATE TABLE [dbo].[B2BRegistrationHistory] (
    [PKID]                           INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [AgencyName]                     VARCHAR (800)   NULL,
    [CustomerCOde]                   VARCHAR (800)   NULL,
    [Dates]                          DATETIME2 (7)   NULL,
    [AddrAccountOpeningRequestFor]   VARCHAR (800)   NULL,
    [AddrAddressLocation]            VARCHAR (800)   NULL,
    [AddrCity]                       VARCHAR (800)   NULL,
    [AddrState]                      VARCHAR (800)   NULL,
    [AddrZipOrPostCode]              VARCHAR (800)   NULL,
    [AddrLandlineNo]                 VARCHAR (MAX)   NULL,
    [AddrMobileNo]                   VARCHAR (MAX)   NULL,
    [AddrFaxTelexNo]                 VARCHAR (MAX)   NULL,
    [AddrEmail]                      VARCHAR (MAX)   NULL,
    [AddrWebsite]                    VARCHAR (MAX)   NULL,
    [AddrPropDirectPartner]          VARCHAR (MAX)   NULL,
    [AddrContactNo]                  VARCHAR (MAX)   NULL,
    [ResiAddressLocation]            VARCHAR (MAX)   NULL,
    [ResiCity]                       VARCHAR (MAX)   NULL,
    [ResiState]                      VARCHAR (MAX)   NULL,
    [ResiZipPostCode]                VARCHAR (MAX)   NULL,
    [ProposBusinessItemsName]        VARCHAR (800)   NULL,
    [ProposBusinessOtherItem]        VARCHAR (MAX)   NULL,
    [LegalBusinessRegsitrNo]         VARCHAR (MAX)   NULL,
    [LegalCompNameOnBusinessRegsitr] VARCHAR (MAX)   NULL,
    [LegalGSTORHST]                  VARCHAR (800)   NULL,
    [LegalDOIncorporationRegistr]    DATETIME        NULL,
    [LegalDOCommencementBusiness]    DATETIME        NULL,
    [LegalDrivingLicens]             VARCHAR (MAX)   NULL,
    [LegalTaxIDNO]                   VARCHAR (MAX)   NULL,
    [LegalNamePrintedOnTaxID]        VARCHAR (MAX)   NULL,
    [CustomerTypeName]               VARCHAR (800)   NULL,
    [CustTypeIATANumber]             VARCHAR (MAX)   NULL,
    [CustTypePremises]               VARCHAR (MAX)   NULL,
    [LicenseInfoDoYouRequire]        VARCHAR (MAX)   NULL,
    [LicIfYesLicensNo]               VARCHAR (MAX)   NULL,
    [BnkDetBankName]                 VARCHAR (800)   NULL,
    [BnkDetBankAccNo]                NVARCHAR (200)  NULL,
    [BnkDetAccType]                  VARCHAR (800)   NULL,
    [BnkDetAddress]                  VARCHAR (800)   NULL,
    [InsertedDate]                   DATE            CONSTRAINT [DF_B2BRegistrationHistory_InsertedDate] DEFAULT (getdate()) NULL,
    [country]                        VARCHAR (500)   NULL,
    [LegalLicenseNoU]                VARCHAR (800)   NULL,
    [BSPARCCode]                     VARCHAR (MAX)   NULL,
    [UpdatedBy]                      VARCHAR (50)    NULL,
    [UpdatedDate]                    DATETIME        NULL,
    [Icast]                          VARCHAR (50)    NULL,
    [FKUserID]                       INT             NULL,
    [Status]                         INT             NULL,
    [CreditLimit]                    DECIMAL (18, 4) NULL,
    [SalesPersonName]                NVARCHAR (100)  NULL,
    [AutoTicketing]                  BIT             CONSTRAINT [DF_B2BRegistrationHistory_AutoTicketing] DEFAULT ((0)) NULL,
    [IssueTicket]                    BIT             NULL,
    [BranchCode]                     VARCHAR (MAX)   NULL,
    [LocationCode]                   VARCHAR (MAX)   NULL,
    [AmadeusCrypticCmd]              BIT             NULL,
    [SaberCrypticCmd]                BIT             NULL,
    [GST_No]                         VARCHAR (35)    NULL,
    [Currency]                       VARCHAR (10)    NULL,
    [CustPostingGroup]               VARCHAR (50)    NULL,
    [CustType]                       VARCHAR (25)    NULL,
    [Airline]                        BIT             NULL,
    [Hotel]                          BIT             NULL,
    [AirlineStartDate]               DATETIME        NULL,
    [AirlineCreditday]               INT             NULL,
    [HotelCreditDay]                 INT             NULL,
    [PANNo]                          VARCHAR (15)    NULL,
    [NameOnPANCard]                  VARCHAR (200)   NULL,
    [StateID]                        INT             NULL,
    [SalesRepCode]                   VARCHAR (10)    NULL,
    [PaymentMode]                    VARCHAR (50)    NULL,
    [PANNumber]                      VARCHAR (10)    NULL,
    [PANName]                        VARCHAR (100)   NULL,
    [PANPath]                        VARCHAR (100)   NULL,
    [GSTRegistered]                  VARCHAR (10)    NULL,
    [GSTINRegisteredUploadPath]      VARCHAR (1000)  NULL,
    [CompanyRegistrationDocPath]     VARCHAR (1000)  NULL,
    [EmpCodeMandate]                 BIT             CONSTRAINT [DF_B2BRegistrationHistory_EmpCodeMandate] DEFAULT ((0)) NULL,
    [OpenAccountWith]                NVARCHAR (100)  NULL,
    [PrimaryMarket]                  NVARCHAR (500)  NULL,
    [AdditionalInfo]                 NVARCHAR (500)  NULL,
    [AgentCRSid]                     NVARCHAR (50)   NULL,
    [PrimaryMarketCountry]           NVARCHAR (500)  NULL,
    [actionType]                     VARCHAR (20)    NULL,
    [modifyByAuto]                   BIGINT          NULL,
    [modifyDateAuto]                 DATETIME        NULL,
    [LoginFromCountry]               VARCHAR (MAX)   NULL,
    [EntityType]                     VARCHAR (MAX)   NULL,
    [EntityName]                     VARCHAR (500)   NULL,
    [BillingEntity]                  VARCHAR (500)   NULL,
    [BillingID]                      VARCHAR (500)   NULL,
    [EntityTypeID]                   INT             NULL,
    [EntityNameID]                   INT             NULL,
    [DivisionCode]                   VARCHAR (50)    NULL,
    [CustomerPostingGroup]           VARCHAR (100)   NULL,
    CONSTRAINT [PK_PKIDhistory] PRIMARY KEY CLUSTERED ([PKID] ASC)
);

