CREATE TABLE [dbo].[bkp_22072020_TblCity] (
    [ID]               INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CityName]         VARCHAR (MAX)  NULL,
    [CityAdjective]    NVARCHAR (MAX) NULL,
    [CountryName]      NVARCHAR (MAX) NULL,
    [Rate]             FLOAT (53)     NULL,
    [CityImage]        NVARCHAR (MAX) NULL,
    [AirportName]      NVARCHAR (MAX) NULL,
    [AirportImage]     NVARCHAR (MAX) NULL,
    [Routs]            NVARCHAR (MAX) NULL,
    [Price]            FLOAT (53)     NULL,
    [BannerImage]      NVARCHAR (MAX) NULL,
    [UrlStructure]     NVARCHAR (MAX) NULL,
    [MetaTitle]        NVARCHAR (MAX) NULL,
    [MetaDescription]  NVARCHAR (MAX) NULL,
    [Keywords]         NVARCHAR (MAX) NULL,
    [IsActive]         BIT            NULL,
    [GoogleAnalytics]  NVARCHAR (MAX) NULL,
    [IsTrendingCity]   BIT            NULL,
    [Inclusive]        BIT            NULL,
    [CurrentTimeStamp] DATETIME       NULL,
    [U_id]             INT            NULL,
    [Currency]         NVARCHAR (MAX) NULL,
    [Timezone]         NVARCHAR (MAX) NULL,
    [Temperature]      NVARCHAR (100) NULL,
    [Precipitaion]     NVARCHAR (MAX) NULL,
    [Description]      NVARCHAR (MAX) NULL,
    [LastModifiedDate] DATETIME       NULL,
    [ModifiedBy]       INT            NULL,
    [AltTag]           NVARCHAR (MAX) NULL,
    [DisplayOrder]     INT            NULL
);

