CREATE TABLE [dbo].[CMS_Packages] (
    [P_ID]               BIGINT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [P_fkgroupid]        VARCHAR (100) NULL,
    [p_fkcity]           VARCHAR (50)  NULL,
    [p_duration]         VARCHAR (50)  NULL,
    [P_image]            VARCHAR (MAX) NULL,
    [P_name]             VARCHAR (100) NULL,
    [P_Title]            VARCHAR (100) NULL,
    [P_TourCategory]     CHAR (1)      NULL,
    [P_Category]         CHAR (1)      NOT NULL,
    [P_DisplayPrice]     BIGINT        NULL,
    [P_CurrencyCode]     CHAR (3)      NULL,
    [P_ShortDesc]        VARCHAR (300) NULL,
    [P_itenary]          TEXT          NULL,
    [P_IsGroupPackage]   CHAR (1)      NULL,
    [P_IsWeekendPackage] CHAR (1)      NULL,
    [P_IsSpecialDeal]    CHAR (1)      NULL,
    [P_IsHolyLandPackge] CHAR (1)      NULL,
    [P_Inclusions]       TEXT          NULL,
    [P_Exclusions]       TEXT          NULL,
    [P_Tnc]              TEXT          NULL,
    [P_Hotels]           TEXT          NULL,
    [P_departure]        VARCHAR (100) NULL,
    [P_MetaTitle]        TEXT          NULL,
    [P_MetaDesc]         TEXT          NULL,
    [P_MetaKeywords]     TEXT          NULL,
    [P_StartDate]        DATE          NULL,
    [P_EndDate]          DATE          NULL,
    [P_EntryDate]        DATE          CONSTRAINT [DF_CMS_Packages_P_EntryDate] DEFAULT (getdate()) NULL,
    [P_LastUpdatedDate]  DATE          CONSTRAINT [DF_CMS_Packages_P_LastUpdatedDate] DEFAULT (getdate()) NULL,
    [P_status]           CHAR (1)      CONSTRAINT [DF_CMS_Packages_P_status] DEFAULT ('A') NULL,
    CONSTRAINT [PK_Packages] PRIMARY KEY CLUSTERED ([P_ID] ASC)
);

