CREATE TABLE [dbo].[Customermaster_UAE] (
    [Customer No#]                    NVARCHAR (255) NULL,
    [Code]                            NVARCHAR (255) NULL,
    [Name]                            NVARCHAR (255) NULL,
    [Division Code]                   NVARCHAR (255) NULL,
    [City]                            NVARCHAR (255) NULL,
    [E-Mail]                          NVARCHAR (255) NULL,
    [Customer Posting Group]          NVARCHAR (255) NULL,
    [Customer Type]                   NVARCHAR (255) NULL,
    [P#A#N# No#]                      FLOAT (53)     NULL,
    [Name As On PAN Card]             NVARCHAR (255) NULL,
    [Agent ID]                        NVARCHAR (255) NULL,
    [Surcharge Group]                 NVARCHAR (255) NULL,
    [TopUp]                           NVARCHAR (255) NULL,
    [BTA Customer]                    NVARCHAR (255) NULL,
    [Supplier Code]                   NVARCHAR (255) NULL,
    [Blocked]                         NVARCHAR (255) NULL,
    [State (Place of Supply)]         NVARCHAR (255) NULL,
    [Location Code]                   NVARCHAR (255) NULL,
    [Branch Code]                     NVARCHAR (255) NULL,
    [Sales Person Code]               NVARCHAR (255) NULL,
    [Old Customer No#]                NVARCHAR (255) NULL,
    [GST Registration No#]            NVARCHAR (255) NULL,
    [GST Customer Type]               NVARCHAR (255) NULL,
    [IATA Code]                       NVARCHAR (255) NULL,
    [Incl# Ser/Mgt Fee]               NVARCHAR (255) NULL,
    [Invoicing Method]                NVARCHAR (255) NULL,
    [GST Effective Date]              NVARCHAR (255) NULL,
    [Commision Post]                  NVARCHAR (255) NULL,
    [Actual Location RC]              NVARCHAR (255) NULL,
    [Account Handling Person]         NVARCHAR (255) NULL,
    [Currency Code]                   NVARCHAR (255) NULL,
    [SEZ]                             NVARCHAR (255) NULL,
    [SEZ with GST]                    NVARCHAR (255) NULL,
    [Balance]                         FLOAT (53)     NULL,
    [Balance (LCY)]                   FLOAT (53)     NULL,
    [Auto Billing]                    NVARCHAR (255) NULL,
    [Date of Joining]                 DATETIME       NULL,
    [<Credit Limit (LCY)>]            FLOAT (53)     NULL,
    [Auto Invoice For RC]             NVARCHAR (255) NULL,
    [Federal Virtual Acc No#  / IFSC] NVARCHAR (255) NULL,
    [AI Exp Agent Id]                 NVARCHAR (255) NULL,
    [<Remaining Credit Limit>]        FLOAT (53)     NULL
);

