CREATE TABLE [dbo].[customer_master_data] (
    [PKID]                    INT            IDENTITY (1, 1) NOT NULL,
    [customer_number]         NVARCHAR (255) NULL,
    [ship_to_code]            NVARCHAR (255) NULL,
    [name]                    NVARCHAR (255) NULL,
    [address]                 NVARCHAR (255) NULL,
    [address_2]               NVARCHAR (255) NULL,
    [city]                    NVARCHAR (255) NULL,
    [contact]                 NVARCHAR (255) NULL,
    [phone_number]            NVARCHAR (255) NULL,
    [telex_number]            NVARCHAR (255) NULL,
    [currency_code]           NVARCHAR (255) NULL,
    [payment_terms_code]      NVARCHAR (255) NULL,
    [country_code]            NVARCHAR (255) NULL,
    [location_code]           NVARCHAR (255) NULL,
    [vat_registration_number] NVARCHAR (255) NULL,
    [post_code]               NVARCHAR (255) NULL,
    [country]                 NVARCHAR (255) NULL,
    [email]                   NVARCHAR (255) NULL,
    [state_code]              NVARCHAR (255) NULL,
    [branch_code]             NVARCHAR (255) NULL,
    [division_code]           NVARCHAR (255) NULL,
    [customer_posting_group]  NVARCHAR (255) NULL,
    [account_handling_person] NVARCHAR (255) NULL,
    [mobile_number]           NVARCHAR (255) NULL,
    [sales_person_code]       NVARCHAR (255) NULL,
    CONSTRAINT [PK_customer_master_data] PRIMARY KEY CLUSTERED ([PKID] ASC)
);

