CREATE TABLE [dbo].[DiscountMaster] (
    [Pk_Id]           BIGINT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [AirCode]         VARCHAR (20)    NULL,
    [FareType]        VARCHAR (50)    NULL,
    [Iata_Percent]    DECIMAL (18, 1) NULL,
    [IsIATAOnBasic]   BIT             NULL,
    [Econ_PLB]        DECIMAL (10, 1) NULL,
    [Prem_PLB]        DECIMAL (10, 1) NULL,
    [Busn_PLB]        DECIMAL (10, 1) NULL,
    [First_PLB]       DECIMAL (10, 1) NULL,
    [IsPLBOnBasic]    BIT             NULL,
    [salesFrm_date]   DATE            NULL,
    [salesTo_date]    DATE            NULL,
    [travelFrm_date]  DATE            NULL,
    [travelTo_date]   DATE            NULL,
    [Issue_PCC]       VARCHAR (50)    NULL,
    [Remark]          VARCHAR (500)   NULL,
    [insertDate]      DATE            NULL,
    [userID]          BIGINT          NULL,
    [modifiedDate]    DATE            NULL,
    [ModifiedBy]      INT             NULL,
    [IsActive]        CHAR (10)       CONSTRAINT [DF_DiscountMaster_status] DEFAULT ((1)) NULL,
    [tour_code]       VARCHAR (20)    NULL,
    [FlatDiscount]    INT             NULL,
    [Rbd_exc_PLB]     VARCHAR (30)    NULL,
    [Soto_exc_PLB]    TINYINT         NULL,
    [Sector_exc_PLB]  VARCHAR (30)    NULL,
    [Rbd_exc_IATA]    VARCHAR (30)    NULL,
    [Soto_exc_IATA]   BIT             NULL,
    [Sector_exc_IATA] VARCHAR (30)    NULL,
    [CommissionType]  INT             NULL,
    [OfficeID]        INT             NULL,
    [AgentID]         VARCHAR (50)    NULL,
    CONSTRAINT [PK_DiscountMaster] PRIMARY KEY CLUSTERED ([Pk_Id] ASC)
);

