CREATE TABLE [dbo].[dummy_Booking Header Web] (
    [Document Type]               BIGINT        NOT NULL,
    [Document No_]                VARCHAR (30)  NULL,
    [Line No_]                    BIGINT        NULL,
    [PNR No_]                     VARCHAR (30)  NULL,
    [Passenger Type]              INT           NULL,
    [Passenger Name]              VARCHAR (101) NULL,
    [Ticket Type]                 INT           NULL,
    [Ticket No_]                  VARCHAR (200) NULL,
    [Airline Code]                VARCHAR (10)  NULL,
    [Airline Number]              VARCHAR (10)  NULL,
    [Issuance Date]               VARCHAR (50)  NULL,
    [Currency Code]               VARCHAR (3)   NOT NULL,
    [Currency Factor]             VARCHAR (1)   NOT NULL,
    [Base Amount]                 INT           NULL,
    [Tax Amount]                  INT           NULL,
    [YQ Tax Amount]               INT           NULL,
    [Service Charge]              INT           NULL,
    [Management Fee]              INT           NULL,
    [Fare Expiry Date]            INT           NULL,
    [Cust_ IATA Comm_ Amount]     INT           NULL,
    [Fare Basis Code]             INT           NULL,
    [Cost Amount]                 INT           NULL,
    [Penalty]                     INT           NULL,
    [Old Ticket No_]              INT           NULL,
    [Entry Type]                  VARCHAR (1)   NOT NULL,
    [Transaction No_]             INT           NULL,
    [Markup on Base Fare]         INT           NULL,
    [Markup on Tax Fare]          INT           NULL,
    [Loss Amount]                 INT           NULL,
    [Invoice_Credit Memo No_]     INT           NULL,
    [Location Code]               VARCHAR (3)   NOT NULL,
    [Global Dimension 2 Code]     VARCHAR (9)   NOT NULL,
    [Sector Name]                 VARCHAR (205) NULL,
    [IATA Code]                   INT           NULL,
    [CRS Code]                    INT           NULL,
    [VMPD No_]                    INT           NULL,
    [Travel Key No_]              INT           NULL,
    [Agent Id]                    INT           NULL,
    [Office Id]                   INT           NULL,
    [Cust_ PLB Amount]            INT           NULL,
    [Cust_ Add_ Comm_ Amount]     INT           NULL,
    [Cust_ Flown Inc_ Amount]     INT           NULL,
    [Cust_ Brd_ Inc_ Amount]      INT           NULL,
    [Q Tax Amount]                INT           NULL,
    [YR Tax Amount]               INT           NULL,
    [Exchange Rate]               INT           NULL,
    [Cancellation Date]           INT           NULL,
    [Departure Date]              INT           NULL,
    [Departure Time]              INT           NULL,
    [Round Trip]                  INT           NULL,
    [Vendor No_]                  INT           NULL,
    [Passport No_]                INT           NULL,
    [Surcharge %]                 INT           NULL,
    [Surcharge Amount]            INT           NULL,
    [Surcharge Type]              INT           NULL,
    [Fare Type Code]              INT           NULL,
    [Return Date]                 INT           NULL,
    [Return Time]                 INT           NULL,
    [Net Fare]                    INT           NULL,
    [Purch_ Due Date]             INT           NULL,
    [CRS IATA Comm_ Amount]       INT           NULL,
    [MCO Ticket]                  INT           NULL,
    [Markup On Cancellation]      INT           NULL,
    [Markup On Date Change]       INT           NULL,
    [Service Fee On Cancellation] INT           NULL,
    [Mgmt Fee On Cancellation]    INT           NULL,
    [Customer No_]                INT           NULL,
    [TopUpCredit]                 INT           NULL,
    [No Show Charge]              INT           NULL,
    [No Show Airline]             INT           NULL,
    [Cancellation TR_PO No_]      INT           NULL,
    [Additional Cxl Base]         INT           NULL,
    [Additional Cxl Tax]          INT           NULL,
    [Card No_]                    INT           NULL,
    [Card Association]            INT           NULL,
    [Expiry Month]                INT           NULL,
    [Expiry Year]                 INT           NULL,
    [CVV No_]                     INT           NULL,
    [UATP]                        INT           NULL,
    [UATP Ticket]                 INT           NULL,
    [Refund Type]                 INT           NULL,
    [Customer Name]               INT           NULL,
    [Vendor Name]                 INT           NULL,
    [Flight No_]                  INT           NULL,
    [Class]                       INT           NULL,
    [International]               INT           NULL,
    [Travel Dates]                INT           NULL,
    [OB Tax Amount]               INT           NULL,
    [Sale Currency Code]          INT           NULL,
    [Sale Currency Factor]        INT           NULL,
    [Sale Exchange Rate]          INT           NULL,
    [Add_ Fare Narration]         INT           NULL,
    [Client Location Code]        INT           NULL,
    [Client Department]           INT           NULL,
    [Chargeability]               INT           NULL,
    [Client Project code]         INT           NULL,
    [Emp code]                    INT           NULL,
    [Queued PCC]                  INT           NULL,
    [Queued Agent ID]             INT           NULL,
    [Ticketing Office ID]         INT           NULL,
    [Ticketing Agent ID]          INT           NULL,
    [Company ID]                  INT           NULL
);

