CREATE TABLE [dbo].[Flight_Flat] (
    [ID]                 INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [MarketPoint]        VARCHAR (30)    NULL,
    [AirportType]        VARCHAR (50)    NULL,
    [AirlineType]        VARCHAR (MAX)   NULL,
    [PaxType]            VARCHAR (50)    NULL,
    [Remark]             VARCHAR (MAX)   NULL,
    [Min]                NUMERIC (18, 2) NULL,
    [Max]                NUMERIC (18, 2) NULL,
    [Discount]           NUMERIC (18, 2) NULL,
    [InsertedDate]       DATETIME        NULL,
    [Flag]               BIT             NULL,
    [TravelFrom]         DATETIME        NULL,
    [TravelTo]           DATETIME        NULL,
    [SaleFrom]           DATETIME        NULL,
    [SaleTo]             DATETIME        NULL,
    [Origin]             BIT             NULL,
    [OriginValue]        VARCHAR (MAX)   NULL,
    [Destination]        BIT             NULL,
    [DestinationValue]   VARCHAR (MAX)   NULL,
    [Flightseries]       BIT             NULL,
    [FlightseriesValue]  VARCHAR (MAX)   NULL,
    [cabin]              VARCHAR (50)    NULL,
    [GroupType]          VARCHAR (50)    NULL,
    [Name]               VARCHAR (50)    NULL,
    [AirlineExclude]     VARCHAR (MAX)   NULL,
    [UserType]           VARCHAR (50)    NULL,
    [AgencyId]           VARCHAR (MAX)   NULL,
    [AgentCategory]      VARCHAR (MAX)   NULL,
    [AgencyNames]        VARCHAR (MAX)   NULL,
    [UserID]             INT             NULL,
    [UpdatedDate]        DATETIME        CONSTRAINT [DF_Flight_Flat_UpdatedDate] DEFAULT (getdate()) NULL,
    [OriginCountry]      VARCHAR (MAX)   NULL,
    [DestinationCountry] VARCHAR (MAX)   NULL,
    CONSTRAINT [PK_MstDiscount_Flat] PRIMARY KEY CLUSTERED ([ID] ASC)
);

