CREATE TABLE [dbo].[Flight_MarkupTypeHistory] (
    [ID]                 INT             IDENTITY (1, 1) NOT NULL,
    [MarketPoint]        VARCHAR (30)    NULL,
    [AirportType]        VARCHAR (50)    NULL,
    [AirlineType]        VARCHAR (MAX)   NULL,
    [PaxType]            VARCHAR (50)    NULL,
    [Remark]             VARCHAR (MAX)   NULL,
    [OnBasic]            NUMERIC (18, 2) NULL,
    [OnTax]              NUMERIC (18, 2) NULL,
    [TravelValidityFrom] DATETIME        NULL,
    [TravelValidityTo]   DATETIME        NULL,
    [SaleValidityFrom]   DATETIME        NULL,
    [SaleValidityTo]     DATETIME        NULL,
    [GroupType]          VARCHAR (50)    NULL,
    [Name]               VARCHAR (100)   NULL,
    [Flag]               BIT             NULL,
    [FareTypeRU]         VARCHAR (50)    NULL,
    [CalculationTypeRU]  VARCHAR (50)    NULL,
    [ValPerRU]           NUMERIC (18, 2) NULL,
    [FareTypeRP]         VARCHAR (50)    NULL,
    [CalculationTypeRP]  VARCHAR (50)    NULL,
    [ValPerRP]           NUMERIC (18, 2) NULL,
    [FareTypeM]          VARCHAR (50)    NULL,
    [CalculationTypeM]   VARCHAR (50)    NULL,
    [ValPerM]            NUMERIC (18, 2) NULL,
    [RUmaxAmt]           NUMERIC (18, 2) NULL,
    [RPmaxAmt]           NUMERIC (18, 2) NULL,
    [MmaxAmt]            NUMERIC (18, 2) NULL,
    [DisplayTypeRU]      INT             NULL,
    [DisplayTypeRP]      INT             NULL,
    [DisplayTypeM]       INT             NULL,
    [BookingTypeM]       INT             NULL,
    [BookingTypeRU]      INT             NULL,
    [BookingTypeRP]      INT             NULL,
    [UserType]           VARCHAR (50)    NULL,
    [AgencyId]           VARCHAR (MAX)   NULL,
    [AgentCategory]      VARCHAR (MAX)   NULL,
    [AgencyNames]        VARCHAR (MAX)   NULL,
    [UserID]             INT             NULL,
    [UpdatedDate]        DATETIME        CONSTRAINT [DF_Flight_MarkupTypeHistory_UpdatedDate] DEFAULT (getdate()) NULL,
    [RBD]                BIT             NULL,
    [RBDValue]           VARCHAR (MAX)   NULL,
    [FareBasis]          BIT             NULL,
    [FareBasisValue]     VARCHAR (MAX)   NULL,
    [FlightSeries]       BIT             NULL,
    [FlightSeriesValue]  VARCHAR (MAX)   NULL,
    [Origin]             BIT             NULL,
    [OriginValue]        VARCHAR (MAX)   NULL,
    [Destination]        BIT             NULL,
    [DestinationValue]   VARCHAR (MAX)   NULL,
    [FlightNo]           BIT             NULL,
    [FlightNoValue]      VARCHAR (MAX)   NULL,
    [Cabin]              VARCHAR (50)    NULL,
    [ExcelField]         VARCHAR (50)    NULL,
    [TransactionType]    VARCHAR (50)    NULL,
    [CRSType]            VARCHAR (50)    NULL,
    [AvailabilityPCC]    VARCHAR (50)    NULL,
    [OriginCountry]      VARCHAR (MAX)   NULL,
    [DestinationCountry] VARCHAR (MAX)   NULL,
    [Action]             VARCHAR (50)    NULL,
    CONSTRAINT [PK_MstDiscountH_Markup] PRIMARY KEY CLUSTERED ([ID] ASC)
);

