CREATE TABLE [dbo].[Flight_CommissionHistory] (
    [ID]                 INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ParentId]           INT             NOT NULL,
    [Action]             VARCHAR (20)    NOT NULL,
    [AgencyNames]        VARCHAR (MAX)   NULL,
    [Remark]             VARCHAR (MAX)   NULL,
    [TravelValidityFrom] DATETIME        NULL,
    [TravelValidityTo]   DATETIME        NULL,
    [SaleValidityFrom]   DATETIME        NULL,
    [SaleValidityTo]     DATETIME        NULL,
    [RBD]                BIT             CONSTRAINT [DF_Flight_CommissionHistory_RBD] DEFAULT ((0)) NULL,
    [RBDValue]           VARCHAR (MAX)   NULL,
    [FareBasis]          BIT             CONSTRAINT [DF_Flight_CommissionHistory_FareBasis] DEFAULT ((0)) NULL,
    [FareBasisValue]     VARCHAR (MAX)   NULL,
    [FlightSeries]       BIT             CONSTRAINT [DF_Flight_CommissionHistory_FlightSeries] DEFAULT ((0)) NULL,
    [FlightSeriesValue]  VARCHAR (MAX)   NULL,
    [Origin]             BIT             CONSTRAINT [DF_Flight_CommissionHistory_Origin] DEFAULT ((0)) NULL,
    [OriginValue]        VARCHAR (MAX)   NULL,
    [Destination]        BIT             CONSTRAINT [DF_Flight_CommissionHistory_Destination] DEFAULT ((0)) NULL,
    [DestinationValue]   VARCHAR (MAX)   NULL,
    [Flag]               BIT             CONSTRAINT [DF_Flight_CommissionHistory_Flag] DEFAULT ((1)) NULL,
    [FlightNo]           BIT             CONSTRAINT [DF_Flight_CommissionHistory_FlightNo] DEFAULT ((0)) NULL,
    [FlightNoValue]      VARCHAR (MAX)   NULL,
    [Cabin]              VARCHAR (50)    NULL,
    [PricingCode]        VARCHAR (MAX)   NULL,
    [TourCode]           VARCHAR (MAX)   NULL,
    [Commission]         DECIMAL (18, 2) NULL,
    [IATADealType]       NVARCHAR (10)   NULL,
    [IATADealPercent]    DECIMAL (18, 2) NULL,
    [PLBDealType]        NVARCHAR (10)   NULL,
    [PLBDealPercent]     DECIMAL (18, 2) NULL,
    [CRSType]            VARCHAR (50)    NULL,
    [AvailabilityPCC]    VARCHAR (50)    NULL,
    [PNRCreationPCC]     VARCHAR (50)    NULL,
    [TicketingPCC]       VARCHAR (50)    NULL,
    [IATADiscountType]   INT             NULL,
    [PLBDiscountType]    INT             NULL,
    [CardMapping1]       INT             NULL,
    [CardMapping2]       INT             NULL,
    [CardMapping3]       INT             NULL,
    [CardMapping4]       INT             NULL,
    [CardMapping5]       INT             NULL,
    [Endorsementline]    VARCHAR (50)    NULL,
    [FareType]           VARCHAR (50)    NULL,
    [MarkupType]         INT             NULL,
    [MarkupDealType]     INT             NULL,
    [MarkupAmount]       DECIMAL (18, 2) NULL,
    [PaxType]            VARCHAR (100)   NULL,
    [DropnetCommission]  DECIMAL (18, 2) NULL,
    [ModifiedBy]         INT             NULL,
    [ModifiedOn]         DATETIME        CONSTRAINT [DF_Flight_CommissionHistory_ModifiedOn] DEFAULT (getdate()) NOT NULL,
    [LoginID]            VARCHAR (MAX)   NULL,
    [gst]                DECIMAL (18)    NULL,
    [tds]                NCHAR (10)      NULL,
    [GDSDiscountType]    INT             NULL,
    [GDSDealType]        VARCHAR (50)    NULL,
    [GDSCommission]      DECIMAL (18)    NULL,
    [NetRemitCode]       VARCHAR (30)    NULL,
    [Queueno]            VARCHAR (500)   NULL,
    [EmailId]            VARCHAR (MAX)   NULL,
    [TicketingAccess]    BIT             CONSTRAINT [DF_Flight_CommissionHistory_TicketingAccess] DEFAULT ((0)) NULL,
    [OTP]                VARCHAR (20)    NULL,
    [OriginCountry]      VARCHAR (MAX)   NULL,
    [DestinationCountry] VARCHAR (MAX)   NULL,
    CONSTRAINT [PK_Flight_CommissionHistory] PRIMARY KEY CLUSTERED ([ID] ASC)
);

