CREATE TABLE [dbo].[Flight_Commission] (
    [Id]                 INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [MarketPoint]        VARCHAR (30)    NULL,
    [AirportType]        VARCHAR (50)    NULL,
    [AirlineType]        VARCHAR (MAX)   NULL,
    [UserType]           VARCHAR (10)    NULL,
    [AgencyId]           VARCHAR (MAX)   NULL,
    [AgentCategory]      VARCHAR (MAX)   NULL,
    [AgencyNames]        VARCHAR (MAX)   NULL,
    [Remark]             VARCHAR (MAX)   NULL,
    [TravelValidityFrom] DATETIME        NULL,
    [TravelValidityTo]   DATETIME        NULL,
    [SaleValidityFrom]   DATETIME        NULL,
    [SaleValidityTo]     DATETIME        NULL,
    [RBD]                BIT             CONSTRAINT [DF_Flight_Commission_RBD] DEFAULT ((0)) NULL,
    [RBDValue]           VARCHAR (MAX)   NULL,
    [FareBasis]          BIT             CONSTRAINT [DF_Flight_Commission_FareBasis] DEFAULT ((0)) NULL,
    [FareBasisValue]     VARCHAR (MAX)   NULL,
    [FlightSeries]       BIT             CONSTRAINT [DF_Flight_Commission_FlightSeries] DEFAULT ((0)) NULL,
    [FlightSeriesValue]  VARCHAR (MAX)   NULL,
    [Origin]             BIT             CONSTRAINT [DF_Flight_Commission_Origin] DEFAULT ((0)) NULL,
    [OriginValue]        VARCHAR (MAX)   NULL,
    [Destination]        BIT             CONSTRAINT [DF_Flight_Commission_Destination] DEFAULT ((0)) NULL,
    [DestinationValue]   VARCHAR (MAX)   NULL,
    [InsertedDate]       DATETIME        NULL,
    [Flag]               BIT             CONSTRAINT [DF_Flight_Commission_Flag] DEFAULT ((1)) NULL,
    [FlightNo]           BIT             CONSTRAINT [DF_Flight_Commission_FlightNo] DEFAULT ((0)) NULL,
    [FlightNoValue]      VARCHAR (MAX)   NULL,
    [Cabin]              VARCHAR (50)    NULL,
    [PricingCode]        VARCHAR (MAX)   NULL,
    [TourCode]           VARCHAR (MAX)   NULL,
    [Commission]         DECIMAL (18, 2) NULL,
    [IATADealType]       NVARCHAR (10)   NULL,
    [IATADealPercent]    DECIMAL (18, 2) NULL,
    [PLBDealType]        NVARCHAR (10)   NULL,
    [PLBDealPercent]     DECIMAL (18, 2) NULL,
    [CRSType]            VARCHAR (50)    NULL,
    [AvailabilityPCC]    VARCHAR (50)    NULL,
    [PNRCreationPCC]     VARCHAR (50)    NULL,
    [TicketingPCC]       VARCHAR (50)    NULL,
    [IATADiscountType]   INT             NULL,
    [PLBDiscountType]    INT             NULL,
    [CardMapping1]       INT             NULL,
    [CardMapping2]       INT             NULL,
    [CardMapping3]       INT             NULL,
    [CardMapping4]       INT             NULL,
    [CardMapping5]       INT             NULL,
    [Endorsementline]    VARCHAR (50)    NULL,
    [UserID]             INT             NULL,
    [UpdatedDate]        DATETIME        CONSTRAINT [DF_Flight_Commission_UpdatedDate] DEFAULT (getdate()) NULL,
    [FareType]           VARCHAR (50)    NULL,
    [MarkupType]         INT             NULL,
    [MarkupDealType]     INT             NULL,
    [MarkupAmount]       DECIMAL (18, 2) NULL,
    [PaxType]            VARCHAR (100)   NULL,
    [DropnetCommission]  DECIMAL (18, 2) NULL,
    [LoginID]            VARCHAR (MAX)   NULL,
    [gst]                DECIMAL (18)    NULL,
    [tds]                DECIMAL (18)    NULL,
    [GDSDealType]        VARCHAR (50)    NULL,
    [GDSDiscountType]    INT             NULL,
    [GDSCommission]      DECIMAL (18, 2) NULL,
    [NetRemitCode]       VARCHAR (30)    NULL,
    [Queueno]            VARCHAR (500)   NULL,
    [EmailId]            VARCHAR (MAX)   NULL,
    [TicketingAccess]    BIT             CONSTRAINT [DF_Flight_Commission_TicketingAccess] DEFAULT ((0)) NULL,
    [OTP]                VARCHAR (20)    NULL,
    [OriginCountry]      VARCHAR (MAX)   NULL,
    [DestinationCountry] VARCHAR (MAX)   NULL,
    CONSTRAINT [PK_Flight_Commission] PRIMARY KEY CLUSTERED ([Id] ASC)
);

