CREATE TABLE [dbo].[FlightCommissionHistory] (
    [ID]                 INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ParentId]           INT             NOT NULL,
    [Action]             VARCHAR (20)    NOT NULL,
    [AgencyNames]        VARCHAR (MAX)   NULL,
    [Remark]             VARCHAR (50)    NULL,
    [TravelValidityFrom] DATETIME        NULL,
    [TravelValidityTo]   DATETIME        NULL,
    [SaleValidityFrom]   DATETIME        NULL,
    [SaleValidityTo]     DATETIME        NULL,
    [RBD]                BIT             CONSTRAINT [DF_FlightCommissionHistory_RBD] DEFAULT ((0)) NULL,
    [RBDValue]           VARCHAR (MAX)   NULL,
    [FareBasis]          BIT             CONSTRAINT [DF_FlightCommissionHistory_FareBasis] DEFAULT ((0)) NULL,
    [FareBasisValue]     VARCHAR (MAX)   NULL,
    [FlightSeries]       BIT             CONSTRAINT [DF_FlightCommissionHistory_FlightSeries] DEFAULT ((0)) NULL,
    [FlightSeriesValue]  VARCHAR (MAX)   NULL,
    [Origin]             BIT             CONSTRAINT [DF_FlightCommissionHistory_Origin] DEFAULT ((0)) NULL,
    [OriginValue]        VARCHAR (MAX)   NULL,
    [Destination]        BIT             CONSTRAINT [DF_FlightCommissionHistory_Destination] DEFAULT ((0)) NULL,
    [DestinationValue]   VARCHAR (MAX)   NULL,
    [Flag]               BIT             CONSTRAINT [DF_FlightCommissionHistory_Flag] DEFAULT ((1)) NULL,
    [FlightNo]           BIT             CONSTRAINT [DF_FlightCommissionHistory_FlightNo] DEFAULT ((0)) NULL,
    [FlightNoValue]      VARCHAR (MAX)   NULL,
    [Cabin]              VARCHAR (50)    NULL,
    [PricingCode]        VARCHAR (MAX)   NULL,
    [TourCode]           VARCHAR (MAX)   NULL,
    [Commission]         DECIMAL (18, 2) NULL,
    [IATADealType]       NVARCHAR (10)   NULL,
    [IATADealPercent]    DECIMAL (18, 2) NULL,
    [PLBDealType]        NVARCHAR (10)   NULL,
    [PLBDealPercent]     DECIMAL (18, 2) NULL,
    [CRSType]            VARCHAR (50)    NULL,
    [AvailabilityPCC]    VARCHAR (50)    NULL,
    [PNRCreationPCC]     VARCHAR (50)    NULL,
    [TicketingPCC]       VARCHAR (50)    NULL,
    [IATADiscountType]   INT             NULL,
    [PLBDiscountType]    INT             NULL,
    [CardMapping1]       INT             NULL,
    [CardMapping2]       INT             NULL,
    [CardMapping3]       INT             NULL,
    [CardMapping4]       INT             NULL,
    [CardMapping5]       INT             NULL,
    [Endorsementline]    VARCHAR (50)    NULL,
    [FareType]           VARCHAR (50)    NULL,
    [MarkupType]         INT             NULL,
    [MarkupDealType]     INT             NULL,
    [MarkupAmount]       DECIMAL (18, 2) NULL,
    [PaxType]            VARCHAR (100)   NULL,
    [DropnetCommission]  DECIMAL (18, 2) NULL,
    [LoginId]            VARCHAR (MAX)   NULL,
    [ModifiedBy]         INT             NULL,
    [ModifiedOn]         DATETIME        CONSTRAINT [DF_FlightCommissionHistory_ModifiedOn] DEFAULT (getdate()) NOT NULL,
    [PayMode]            NVARCHAR (20)   NULL,
    [VirtualCardName]    VARCHAR (50)    NULL,
    [GST]                DECIMAL (18, 2) NULL,
    [TDS]                DECIMAL (18, 2) NULL,
    [GDSDiscountType]    INT             NULL,
    [GDSDealType]        VARCHAR (10)    NULL,
    [AdditionalAmount]   DECIMAL (18, 2) CONSTRAINT [DF_FlightCommissionHistory_AdditionalAmount] DEFAULT ((0.00)) NULL,
    [GDSCommission]      DECIMAL (18, 2) NULL,
    [AdditionalAmtType]  VARCHAR (30)    NULL,
    [NetRemitCode]       VARCHAR (30)    NULL,
    [UserType]           VARCHAR (10)    NULL,
    [AgencyId]           VARCHAR (MAX)   NULL,
    [AgentCategory]      VARCHAR (MAX)   NULL,
    [ConfigurationType]  VARCHAR (200)   NULL,
    [SOTO]               BIT             NULL,
    [UserID]             INT             NULL,
    [MarketPoint]        VARCHAR (30)    NULL,
    [AirportType]        VARCHAR (50)    NULL,
    [AirlineType]        VARCHAR (MAX)   NULL,
    [InsertedDate]       DATETIME        CONSTRAINT [DF_FlightCommissionHistory_InsertedDate] DEFAULT (getdate()) NULL,
    [Discounttype]       VARCHAR (500)   NULL,
    [Percentage]         DECIMAL (18, 2) NULL,
    [LimitValue]         DECIMAL (18, 2) NULL,
    [Currency]           VARCHAR (20)    NULL,
    [HUP_Amount]         DECIMAL (18, 2) NULL,
    [FromValue]          DECIMAL (18, 2) NULL,
    [ToValue]            DECIMAL (18, 2) NULL,
    [AutoTicketing]      BIT             CONSTRAINT [DF_FlightCommissionHistory_AutoTicketing] DEFAULT ((0)) NULL,
    [Queueno]            VARCHAR (500)   NULL,
    [EmailId]            VARCHAR (MAX)   NULL,
    [TicketingAccess]    BIT             CONSTRAINT [DF_FlightCommissionHistory_TicketingAccess] DEFAULT ((0)) NULL,
    [OTP]                VARCHAR (20)    NULL,
    [OriginCountry]      VARCHAR (MAX)   NULL,
    [DestinationCountry] VARCHAR (MAX)   NULL,
    [AgentLogin]         VARCHAR (100)   NULL,
    [Password]           VARCHAR (100)   NULL,
    [IATA]               VARCHAR (100)   NULL,
    [AgentIdentifier]    VARCHAR (100)   NULL,
    [ViaPoint]           BIT             NULL,
    [ViaPointValue]      VARCHAR (MAX)   NULL,
    CONSTRAINT [PK_FlightCommissionHistory] PRIMARY KEY CLUSTERED ([ID] ASC)
);

