CREATE TABLE [dbo].[FlightPromocode_Delete] (
    [ID]                 INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [MarketPoint]        VARCHAR (30)    NULL,
    [AirportType]        VARCHAR (50)    NULL,
    [AirlineType]        VARCHAR (50)    NULL,
    [PaxType]            VARCHAR (50)    NULL,
    [Remark]             VARCHAR (MAX)   NULL,
    [User]               VARCHAR (50)    NULL,
    [RestrictedUser]     VARCHAR (50)    NULL,
    [IncludeFlat]        VARCHAR (50)    NULL,
    [MinFareAmt]         NUMERIC (18, 2) NULL,
    [Discount]           NUMERIC (18, 2) NULL,
    [PromoCode]          VARCHAR (50)    NULL,
    [TravelValidityFrom] DATETIME        NULL,
    [TravelValidityTo]   DATETIME        NULL,
    [SaleValidityFrom]   DATETIME        NULL,
    [SaleValidityTo]     DATETIME        NULL,
    [InsertedDate]       DATETIME        NULL,
    [Flag]               BIT             NULL,
    [DeletedDate]        DATETIME        NULL,
    [DeletedBy]          VARCHAR (50)    NULL,
    [PromoID]            INT             NULL,
    [discounttype]       VARCHAR (50)    NULL,
    [cabin]              VARCHAR (50)    NULL,
    [Origin]             BIT             NULL,
    [OriginValue]        VARCHAR (MAX)   NULL,
    [Destination]        BIT             NULL,
    [DestinationValue]   VARCHAR (MAX)   NULL,
    [FlightSeries]       BIT             NULL,
    [FlightSeiresValue]  VARCHAR (MAX)   NULL,
    CONSTRAINT [PK_FlightPromocode_Delete] PRIMARY KEY CLUSTERED ([ID] ASC)
);

