CREATE TABLE [dbo].[Flight_PromoCode] (
    [ID]                 INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [MarketPoint]        VARCHAR (30)    NULL,
    [AirportType]        VARCHAR (50)    NULL,
    [AirlineType]        VARCHAR (MAX)   NULL,
    [PaxType]            VARCHAR (50)    NULL,
    [Remark]             VARCHAR (MAX)   NULL,
    [User]               VARCHAR (50)    NULL,
    [RestrictedUser]     VARCHAR (50)    NULL,
    [IncludeFlat]        VARCHAR (50)    NULL,
    [MinFareAmt]         NUMERIC (18, 2) NULL,
    [Discount]           NUMERIC (18, 2) NULL,
    [PromoCode]          VARCHAR (50)    NULL,
    [TravelValidityFrom] DATETIME        NULL,
    [TravelValidityTo]   DATETIME        NULL,
    [SaleValidityFrom]   DATETIME        NULL,
    [SaleValidityTo]     DATETIME        NULL,
    [InsertedDate]       DATETIME        NULL,
    [Flag]               BIT             NULL,
    [discounttype]       VARCHAR (20)    NULL,
    [cabin]              VARCHAR (60)    NULL,
    [Origin]             BIT             NULL,
    [OriginValue]        VARCHAR (MAX)   NULL,
    [Destination]        BIT             NULL,
    [DestinationValue]   VARCHAR (MAX)   NULL,
    [FlightSeries]       BIT             NULL,
    [FlightSeiresValue]  VARCHAR (MAX)   NULL,
    [MaxAmt]             NUMERIC (18, 2) NULL,
    [AirlineExclude]     VARCHAR (MAX)   NULL,
    [TC_Hyperlink]       NVARCHAR (200)  NULL,
    [BookingType]        SMALLINT        NULL,
    [UserType]           VARCHAR (50)    NULL,
    [AgencyId]           VARCHAR (MAX)   NULL,
    [AgentCategory]      VARCHAR (MAX)   NULL,
    [AgencyNames]        VARCHAR (MAX)   NULL,
    [UserID]             INT             NULL,
    [UpdatedDate]        DATETIME        CONSTRAINT [DF_Flight_PromoCode_UpdatedDate] DEFAULT (getdate()) NULL,
    [OriginCountry]      VARCHAR (MAX)   NULL,
    [DestinationCountry] VARCHAR (MAX)   NULL,
    [DiscountOn]         INT             NULL,
    CONSTRAINT [PK_MstDiscount_PromoCode] PRIMARY KEY CLUSTERED ([ID] ASC)
);

