CREATE TABLE [dbo].[FlightDeal_Delete] (
    [ID]                 INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [MarketPoint]        VARCHAR (30)    NULL,
    [AirportType]        VARCHAR (50)    NULL,
    [AirlineType]        VARCHAR (50)    NULL,
    [PaxType]            VARCHAR (50)    NULL,
    [Remark]             VARCHAR (MAX)   NULL,
    [DealType]           VARCHAR (30)    NULL,
    [DealValue]          NUMERIC (18, 2) NULL,
    [SOTO]               BIT             NULL,
    [TravelValidityFrom] DATETIME        NULL,
    [TravelValidityTo]   DATETIME        NULL,
    [SaleValidityFrom]   DATETIME        NULL,
    [SaleValidityTo]     DATETIME        NULL,
    [RBD]                BIT             NULL,
    [RBDValue]           VARCHAR (MAX)   NULL,
    [FareBasis]          BIT             NULL,
    [FareBasisValue]     VARCHAR (MAX)   NULL,
    [FlightSeries]       BIT             NULL,
    [FlightSeriesValue]  VARCHAR (MAX)   NULL,
    [Origin]             BIT             NULL,
    [OriginValue]        VARCHAR (MAX)   NULL,
    [Destination]        BIT             NULL,
    [DestinationValue]   VARCHAR (MAX)   NULL,
    [InsertedDate]       DATETIME        NULL,
    [GroupType]          VARCHAR (50)    NULL,
    [Name]               VARCHAR (100)   NULL,
    [DeletedDate]        DATETIME        NULL,
    [DeletedBy]          VARCHAR (50)    NULL,
    CONSTRAINT [PK_FlightDeal_Delete] PRIMARY KEY CLUSTERED ([ID] ASC)
);

