CREATE TABLE [dbo].[Flight_Deal] (
    [ID]                 INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [MarketPoint]        VARCHAR (30)    NULL,
    [AirportType]        VARCHAR (50)    NULL,
    [AirlineType]        VARCHAR (50)    NULL,
    [PaxType]            VARCHAR (50)    NULL,
    [Remark]             VARCHAR (MAX)   NULL,
    [DealType]           VARCHAR (30)    NULL,
    [DealValue]          NUMERIC (18, 2) CONSTRAINT [DF_Flight_Deal_DealValue] DEFAULT ((0)) NULL,
    [SOTO]               BIT             NULL,
    [TravelValidityFrom] DATETIME        NULL,
    [TravelValidityTo]   DATETIME        NULL,
    [SaleValidityFrom]   DATETIME        NULL,
    [SaleValidityTo]     DATETIME        NULL,
    [RBD]                BIT             NULL,
    [RBDValue]           VARCHAR (MAX)   NULL,
    [FareBasis]          BIT             NULL,
    [FareBasisValue]     VARCHAR (MAX)   NULL,
    [FlightSeries]       BIT             NULL,
    [FlightSeriesValue]  VARCHAR (MAX)   NULL,
    [Origin]             BIT             NULL,
    [OriginValue]        VARCHAR (MAX)   NULL,
    [Destination]        BIT             NULL,
    [DestinationValue]   VARCHAR (MAX)   NULL,
    [InsertedDate]       DATETIME        NULL,
    [GroupType]          VARCHAR (50)    NULL,
    [Name]               VARCHAR (100)   NULL,
    [Flag]               BIT             NULL,
    [IATA_DealType]      VARCHAR (50)    NULL,
    [IATA_DealValue]     NUMERIC (18, 2) CONSTRAINT [DF_Flight_Deal_IATA_DealValue] DEFAULT ((0)) NULL,
    [UserID]             INT             NULL,
    [UpdatedDate]        DATETIME        CONSTRAINT [DF_Flight_Deal_UpdatedDate] DEFAULT (getdate()) NULL,
    [OriginCountry]      VARCHAR (MAX)   NULL,
    [DestinationCountry] VARCHAR (MAX)   NULL,
    CONSTRAINT [PK_MstDiscount_Deal] PRIMARY KEY CLUSTERED ([ID] ASC)
);

