CREATE TABLE [dbo].[HolidayInquiry] (
    [HolidayInquiryIDP]      BIGINT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [AgentID]                INT            NULL,
    [MainAgentID]            INT            NULL,
    [AssignTMSUserID]        INT            NULL,
    [TMSEmployeeCode_Assign] VARCHAR (50)   NULL,
    [TMSUserID_Assign]       INT            NULL,
    [AgentName]              VARCHAR (50)   NULL,
    [AgentPhoneNo]           VARCHAR (50)   NULL,
    [AgentEmailID]           VARCHAR (150)  NULL,
    [FromCity]               VARCHAR (50)   NULL,
    [DestinationNames]       NVARCHAR (500) NULL,
    [TotalNoOfNights]        INT            NULL,
    [Adult]                  INT            NULL,
    [Child]                  INT            NULL,
    [ChildAge]               VARCHAR (50)   NULL,
    [PaxNationalityID]       INT            NULL,
    [FileName]               VARCHAR (50)   NULL,
    [HotelCategory]          VARCHAR (500)  NULL,
    [HotelRoomType]          VARCHAR (500)  NULL,
    [ServicesNames]          VARCHAR (500)  NULL,
    [ServiceIDs]             VARCHAR (500)  NULL,
    [Remarks]                NVARCHAR (MAX) NULL,
    [InquiryDateTime]        DATETIME       NULL,
    [WebsiteName]            VARCHAR (50)   NULL,
    [InquiryNumber]          VARCHAR (50)   NULL,
    [InquiryStatus]          VARCHAR (50)   CONSTRAINT [DF_HolidayInquiry_InquiryStatus] DEFAULT ('OPEN') NULL,
    [InquiryStatusIDTMS]     INT            NULL,
    [UpdatedAgentID]         INT            NULL,
    [UpdatedMainAgentID]     INT            NULL,
    [ClientFirstName]        VARCHAR (150)  NULL,
    [ClientLastName]         VARCHAR (150)  NULL,
    [ClientEmail]            VARCHAR (250)  NULL,
    [ClientMobile]           VARCHAR (50)   NULL,
    [TravelDateFrom]         DATETIME       NULL,
    [TravelDateTo]           DATETIME       NULL,
    [QueryType]              VARCHAR (10)   NULL,
    [SelfAssign]             VARCHAR (10)   NULL,
    [PackageIDF]             INT            NULL,
    [PackageName]            NVARCHAR (255) NULL,
    CONSTRAINT [PK_HolidayInquiry] PRIMARY KEY CLUSTERED ([HolidayInquiryIDP] ASC)
);

