CREATE TABLE [dbo].[Hotel_List_Master_Amadeus] (
    [Id]                    INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [PROPERTY_CODE]         NVARCHAR (50)  NULL,
    [CHAIN]                 NVARCHAR (50)  NULL,
    [CITY]                  NVARCHAR (50)  NULL,
    [PROPERTY_IDENTIFIER]   NVARCHAR (50)  NULL,
    [CHAIN_NAME]            NVARCHAR (50)  NULL,
    [PROPERTY_NAME]         NVARCHAR (50)  NULL,
    [LOCATION]              NVARCHAR (50)  NULL,
    [TRANSPORTATION]        NVARCHAR (50)  NULL,
    [ADRESS_LINE_1]         NVARCHAR (100) NULL,
    [ADRESS_LINE_2]         NVARCHAR (50)  NULL,
    [CITY2]                 NVARCHAR (50)  NULL,
    [STATE_CODE]            NVARCHAR (50)  NULL,
    [ZIP_CODE]              NVARCHAR (50)  NULL,
    [COUNTRY_NAME]          NVARCHAR (50)  NULL,
    [COUNTRY_CODE]          NVARCHAR (50)  NULL,
    [PHONE]                 NVARCHAR (50)  NULL,
    [FAX]                   NVARCHAR (50)  NULL,
    [LOCALRATING]           NVARCHAR (50)  NULL,
    [SELFRATING]            NVARCHAR (50)  NULL,
    [LATITUDE]              FLOAT (53)     NULL,
    [LONGITUDE]             FLOAT (53)     NULL,
    [DUPE_POOL_ID]          INT            NULL,
    [PROVIDER_VALUE]        NVARCHAR (50)  NULL,
    [LAST_UPDATE_TIMESTAMP] NVARCHAR (50)  NULL,
    [PROPERTY_THUMBNAIL]    NVARCHAR (300) NULL,
    [LAST_UPDATED_DATE]     SMALLDATETIME  NULL,
    [SHORT_DESCRIPTION]     VARCHAR (MAX)  NULL,
    CONSTRAINT [PK_Hotel_List_Master_Amadeus] PRIMARY KEY CLUSTERED ([Id] ASC)
);

