CREATE TABLE [dbo].[hotel_bookmaster_31March2022] (
    [pkId]                       BIGINT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [orderId]                    VARCHAR (30)    NULL,
    [expected_prize]             VARCHAR (20)    NULL,
    [searchApiId]                VARCHAR (50)    NOT NULL,
    [hotelId]                    VARCHAR (50)    NOT NULL,
    [section_unique_id]          VARCHAR (100)   NULL,
    [book_Id]                    VARCHAR (150)   NULL,
    [AgentId]                    VARCHAR (150)   NULL,
    [book_message]               VARCHAR (50)    NULL,
    [BookingReference]           VARCHAR (150)   NULL,
    [riyaPNR]                    VARCHAR (10)    NULL,
    [ConfirmationNumber]         VARCHAR (50)    NULL,
    [TotalCharges]               DECIMAL (10, 2) NULL,
    [LeaderTitle]                VARCHAR (6)     NULL,
    [LeaderFirstName]            VARCHAR (150)   NULL,
    [LeaderLastName]             VARCHAR (150)   NULL,
    [CurrencyCode]               VARCHAR (10)    NULL,
    [HotelName]                  VARCHAR (150)   NULL,
    [CountryName]                VARCHAR (150)   NULL,
    [CityId]                     VARCHAR (150)   NULL,
    [HotelAddress1]              VARCHAR (650)   NULL,
    [CurrentStatus]              VARCHAR (50)    NULL,
    [ExpirationDate]             DATETIME        NULL,
    [TotalAdults]                VARCHAR (10)    NULL,
    [TotalChildren]              VARCHAR (10)    NULL,
    [TotalRooms]                 VARCHAR (10)    NULL,
    [HotelAddress2]              VARCHAR (650)   NULL,
    [ServiceDate]                DATETIME        NULL,
    [CheckInDate]                DATETIME        NULL,
    [CheckOutDate]               DATETIME        NULL,
    [AgentRate]                  DECIMAL (10, 2) NULL,
    [HotelPhone]                 VARCHAR (50)    NULL,
    [HotelRating]                VARCHAR (20)    NULL,
    [SelectedNights]             VARCHAR (20)    NULL,
    [CancellationPolicy]         VARCHAR (620)   NULL,
    [AgentRefNo]                 VARCHAR (30)    NULL,
    [PassengerPhone]             VARCHAR (50)    NULL,
    [PassengerEmail]             VARCHAR (150)   NULL,
    [totalTax]                   DECIMAL (10, 2) NULL,
    [IsCancelled]                INT             NULL,
    [IsBooked]                   INT             NULL,
    [inserteddate]               DATETIME        NULL,
    [TotalDiscount]              DECIMAL (10, 2) NULL,
    [CancellationCharge]         DECIMAL (10, 2) NULL,
    [ServiceCharge]              DECIMAL (10, 2) NULL,
    [promoCode]                  VARCHAR (50)    NULL,
    [request]                    VARCHAR (1500)  NULL,
    [cityName]                   VARCHAR (100)   NULL,
    [CancelHours]                DECIMAL (18, 2) NULL,
    [IsRefunded]                 INT             NULL,
    [RefundedProcessRemark]      VARCHAR (50)    NULL,
    [aftermarkupcancelcharges]   NUMERIC (18, 2) NULL,
    [CancelDate]                 DATETIME        NULL,
    [ContractComment]            NVARCHAR (MAX)  NULL,
    [QtechCancelCharge]          NUMERIC (18, 2) NULL,
    [QtechTotalCharges]          NUMERIC (18, 2) NULL,
    [QtechAppliedAgentCharges]   NUMERIC (18, 2) NULL,
    [QtechAppliedAgentRate]      NUMERIC (18, 2) NULL,
    [BufferCancelDate]           DATETIME        NULL,
    [SupplierName]               VARCHAR (200)   NULL,
    [beforecancelcharge]         NUMERIC (18, 2) NULL,
    [AppliedAgentCharges]        DECIMAL (10, 2) NULL,
    [LoginID]                    VARCHAR (500)   NULL,
    [IsClosed]                   INT             NULL,
    [SupplierRate]               DECIMAL (10, 2) NULL,
    [SupplierCurrencyCode]       VARCHAR (10)    NULL,
    [ROEValue]                   DECIMAL (10, 2) NULL,
    [SupplierPhoneNo]            VARCHAR (100)   NULL,
    [SupplierReferenceNo]        VARCHAR (50)    NULL,
    [ClosedRemark]               VARCHAR (1000)  NULL,
    [FullRefund]                 BIT             NULL,
    [HotelConfNumber]            NVARCHAR (40)   NULL,
    [OfflineRemark]              VARCHAR (MAX)   NULL,
    [AddCancelCharge]            INT             NULL,
    [RiyaAgentID]                NVARCHAR (50)   NULL,
    [ERPStatus]                  BIT             NULL,
    [RoomType]                   NVARCHAR (500)  NULL,
    [AdminNote]                  NVARCHAR (500)  NULL,
    [HotelStaffName]             VARCHAR (100)   NULL,
    [ConfirmationRemark]         NVARCHAR (500)  NULL,
    [ConfirmationDate]           DATETIME        NULL,
    [VoucherNumber]              NVARCHAR (200)  NULL,
    [VoucherDate]                DATETIME        NULL,
    [B2BPaymentMode]             INT             NULL,
    [DisplayDiscountRate]        NVARCHAR (500)  NULL,
    [CancellationDeadLine]       NVARCHAR (500)  NULL,
    [MainAgentID]                BIGINT          NULL,
    [ISDCode]                    VARCHAR (50)    NULL,
    [AgentRemark]                NVARCHAR (500)  NULL,
    [SpecialRemark]              NVARCHAR (MAX)  NULL,
    [PolicyCode]                 VARCHAR (50)    NULL,
    [SB_ReversalStatus]          BIT             NULL,
    [AgentInvoiceNumber]         VARCHAR (50)    NULL,
    [InquiryNo]                  VARCHAR (50)    NULL,
    [FileNo]                     VARCHAR (50)    NULL,
    [PaymentRefNo]               VARCHAR (50)    NULL,
    [OBTCNo]                     VARCHAR (50)    NULL,
    [RTTRefNo]                   VARCHAR (50)    NULL,
    [OpsRemark]                  VARCHAR (50)    NULL,
    [AcctsRemark]                VARCHAR (50)    NULL,
    [MarkupAmount]               DECIMAL (10, 2) NULL,
    [MarkupCurrency]             VARCHAR (50)    NULL,
    [BranchCode]                 NVARCHAR (200)  NULL,
    [BookingCountry]             VARCHAR (50)    NULL,
    [BookingCountryPkid]         INT             NULL,
    [Meal]                       NVARCHAR (500)  NULL,
    [QutechHotelId]              NVARCHAR (500)  NULL,
    [QutechSearchUniqueId]       NVARCHAR (500)  NULL,
    [QutechSectionUniqueId]      NVARCHAR (500)  NULL,
    [SupplierUsername]           NVARCHAR (500)  NULL,
    [SupplierPassword]           NVARCHAR (500)  NULL,
    [MakePaymentReversalFlag]    VARCHAR (50)    NULL,
    [MakePaymentReversalStatus]  VARCHAR (50)    NULL,
    [MakePaymentReversalMessage] VARCHAR (MAX)   NULL,
    [AdOn_CancellationCharges]   NVARCHAR (100)  NULL,
    [LocalHotelId]               NVARCHAR (500)  NULL,
    [BookStatusSchedulerFlag]    BIT             NULL,
    [failurereason]              VARCHAR (MAX)   NULL,
    [CurrentDateSchedular]       VARCHAR (200)   NULL,
    [TotalRoomAmount]            VARCHAR (50)    NULL,
    [TotalSummaryAmount]         VARCHAR (50)    NULL,
    [AmountBeforePgCommission]   VARCHAR (50)    NULL,
    [AmountAfterPgCommision]     VARCHAR (50)    NULL,
    [PriceChangeOrderId]         VARCHAR (50)    NULL,
    [ispricechange]              VARCHAR (5)     NULL,
    [VendorBasicAmount]          VARCHAR (10)    NULL,
    [VendorBasicAmountBaseCur]   VARCHAR (20)    NULL,
    [ExpectedPriceBaseCur]       VARCHAR (20)    NULL,
    [RatePerNight]               VARCHAR (20)    NULL
);

