CREATE TABLE [dbo].[Hotel_BookMaster_22Jan2024] (
    [pkId]                        BIGINT          IDENTITY (1, 1) NOT NULL,
    [orderId]                     VARCHAR (30)    NULL,
    [expected_prize]              VARCHAR (20)    NULL,
    [searchApiId]                 VARCHAR (200)   NOT NULL,
    [hotelId]                     VARCHAR (50)    NOT NULL,
    [section_unique_id]           VARCHAR (100)   NULL,
    [book_Id]                     VARCHAR (150)   NULL,
    [AgentId]                     VARCHAR (150)   NULL,
    [book_message]                VARCHAR (50)    NULL,
    [BookingReference]            VARCHAR (150)   NULL,
    [riyaPNR]                     VARCHAR (10)    NULL,
    [ConfirmationNumber]          VARCHAR (50)    NULL,
    [TotalCharges]                DECIMAL (10, 2) NULL,
    [LeaderTitle]                 VARCHAR (6)     NULL,
    [LeaderFirstName]             VARCHAR (150)   NULL,
    [LeaderLastName]              VARCHAR (150)   NULL,
    [CurrencyCode]                VARCHAR (10)    NULL,
    [HotelName]                   VARCHAR (150)   NULL,
    [CountryName]                 VARCHAR (150)   NULL,
    [CityId]                      VARCHAR (150)   NULL,
    [HotelAddress1]               VARCHAR (650)   NULL,
    [CurrentStatus]               VARCHAR (50)    NULL,
    [ExpirationDate]              DATETIME        NULL,
    [TotalAdults]                 VARCHAR (10)    NULL,
    [TotalChildren]               VARCHAR (10)    NULL,
    [TotalRooms]                  VARCHAR (10)    NULL,
    [HotelAddress2]               VARCHAR (650)   NULL,
    [ServiceDate]                 DATETIME        NULL,
    [CheckInDate]                 DATETIME        NULL,
    [CheckOutDate]                DATETIME        NULL,
    [AgentRate]                   DECIMAL (10, 2) NULL,
    [HotelPhone]                  VARCHAR (50)    NULL,
    [HotelRating]                 VARCHAR (20)    NULL,
    [SelectedNights]              VARCHAR (20)    NULL,
    [CancellationPolicy]          VARCHAR (MAX)   NULL,
    [AgentRefNo]                  VARCHAR (30)    NULL,
    [PassengerPhone]              VARCHAR (50)    NULL,
    [PassengerEmail]              VARCHAR (150)   NULL,
    [totalTax]                    DECIMAL (10, 2) NULL,
    [IsCancelled]                 INT             NULL,
    [IsBooked]                    INT             NULL,
    [inserteddate]                DATETIME        NULL,
    [TotalDiscount]               DECIMAL (10, 2) NULL,
    [CancellationCharge]          DECIMAL (10, 2) NULL,
    [ServiceCharge]               DECIMAL (10, 2) NULL,
    [promoCode]                   VARCHAR (50)    NULL,
    [request]                     VARCHAR (1500)  NULL,
    [cityName]                    VARCHAR (100)   NULL,
    [CancelHours]                 DECIMAL (18, 2) NULL,
    [IsRefunded]                  INT             NULL,
    [RefundedProcessRemark]       VARCHAR (50)    NULL,
    [aftermarkupcancelcharges]    NUMERIC (18, 2) NULL,
    [CancelDate]                  DATETIME        NULL,
    [ContractComment]             NVARCHAR (MAX)  NULL,
    [QtechCancelCharge]           NUMERIC (18, 2) NULL,
    [QtechTotalCharges]           NUMERIC (18, 2) NULL,
    [QtechAppliedAgentCharges]    NUMERIC (18, 2) NULL,
    [QtechAppliedAgentRate]       NUMERIC (18, 2) NULL,
    [BufferCancelDate]            DATETIME        NULL,
    [SupplierName]                VARCHAR (200)   NULL,
    [beforecancelcharge]          NUMERIC (18, 2) NULL,
    [AppliedAgentCharges]         DECIMAL (10, 2) NULL,
    [LoginID]                     VARCHAR (500)   NULL,
    [IsClosed]                    INT             NULL,
    [SupplierRate]                DECIMAL (10, 2) NULL,
    [SupplierCurrencyCode]        VARCHAR (10)    NULL,
    [ROEValue]                    DECIMAL (18, 6) NULL,
    [SupplierPhoneNo]             VARCHAR (100)   NULL,
    [SupplierReferenceNo]         VARCHAR (200)   NULL,
    [ClosedRemark]                VARCHAR (1000)  NULL,
    [FullRefund]                  BIT             NULL,
    [HotelConfNumber]             VARCHAR (MAX)   NULL,
    [OfflineRemark]               VARCHAR (MAX)   NULL,
    [AddCancelCharge]             INT             NULL,
    [RiyaAgentID]                 NVARCHAR (50)   NULL,
    [ERPStatus]                   BIT             NULL,
    [RoomType]                    NVARCHAR (500)  NULL,
    [AdminNote]                   NVARCHAR (500)  NULL,
    [HotelStaffName]              VARCHAR (100)   NULL,
    [ConfirmationRemark]          NVARCHAR (500)  NULL,
    [ConfirmationDate]            DATETIME        NULL,
    [VoucherNumber]               NVARCHAR (200)  NULL,
    [VoucherDate]                 DATETIME        NULL,
    [B2BPaymentMode]              INT             NULL,
    [DisplayDiscountRate]         NVARCHAR (500)  NULL,
    [CancellationDeadLine]        NVARCHAR (500)  NULL,
    [MainAgentID]                 BIGINT          NULL,
    [ISDCode]                     VARCHAR (50)    NULL,
    [AgentRemark]                 NVARCHAR (500)  NULL,
    [SpecialRemark]               NVARCHAR (MAX)  NULL,
    [PolicyCode]                  VARCHAR (50)    NULL,
    [SB_ReversalStatus]           BIT             NULL,
    [AgentInvoiceNumber]          VARCHAR (50)    NULL,
    [InquiryNo]                   VARCHAR (50)    NULL,
    [FileNo]                      VARCHAR (50)    NULL,
    [PaymentRefNo]                VARCHAR (50)    NULL,
    [OBTCNo]                      VARCHAR (50)    NULL,
    [RTTRefNo]                    VARCHAR (50)    NULL,
    [OpsRemark]                   VARCHAR (50)    NULL,
    [AcctsRemark]                 VARCHAR (50)    NULL,
    [MarkupAmount]                DECIMAL (10, 2) NULL,
    [MarkupCurrency]              VARCHAR (50)    NULL,
    [BranchCode]                  NVARCHAR (200)  NULL,
    [BookingCountry]              VARCHAR (50)    NULL,
    [BookingCountryPkid]          INT             NULL,
    [Meal]                        NVARCHAR (500)  NULL,
    [QutechHotelId]               NVARCHAR (500)  NULL,
    [QutechSearchUniqueId]        NVARCHAR (500)  NULL,
    [QutechSectionUniqueId]       NVARCHAR (500)  NULL,
    [SupplierUsername]            NVARCHAR (500)  NULL,
    [SupplierPassword]            NVARCHAR (500)  NULL,
    [MakePaymentReversalFlag]     VARCHAR (50)    NULL,
    [MakePaymentReversalStatus]   VARCHAR (50)    NULL,
    [MakePaymentReversalMessage]  VARCHAR (MAX)   NULL,
    [AdOn_CancellationCharges]    NVARCHAR (100)  NULL,
    [LocalHotelId]                NVARCHAR (500)  NULL,
    [BookStatusSchedulerFlag]     BIT             NULL,
    [failurereason]               VARCHAR (MAX)   NULL,
    [CurrentDateSchedular]        VARCHAR (200)   NULL,
    [TotalRoomAmount]             VARCHAR (50)    NULL,
    [TotalSummaryAmount]          VARCHAR (50)    NULL,
    [AmountBeforePgCommission]    VARCHAR (50)    NULL,
    [AmountAfterPgCommision]      VARCHAR (50)    NULL,
    [PriceChangeOrderId]          VARCHAR (50)    NULL,
    [ispricechange]               VARCHAR (5)     NULL,
    [VendorBasicAmount]           VARCHAR (10)    NULL,
    [VendorBasicAmountBaseCur]    VARCHAR (20)    NULL,
    [ExpectedPriceBaseCur]        VARCHAR (20)    NULL,
    [RatePerNight]                VARCHAR (20)    NULL,
    [Hotel_ERPResponceID]         VARCHAR (500)   NULL,
    [Hotel_CanERPResponceID]      VARCHAR (500)   NULL,
    [Hotel_ERPPushStatus]         BIT             NULL,
    [Hotel_CanERPPushStatus]      BIT             NULL,
    [SuBMainAgentID]              BIGINT          NULL,
    [AlertEmail]                  VARCHAR (200)   NULL,
    [AgentTotalNetAmoun]          VARCHAR (20)    NULL,
    [RepriceId]                   VARCHAR (50)    NULL,
    [Isi2space]                   INT             NULL,
    [Refundable]                  BIT             NULL,
    [SubAgentId]                  INT             NULL,
    [UserIpAddrress]              VARCHAR (50)    NULL,
    [providerConfirmationNumber]  VARCHAR (200)   NULL,
    [cancellationToken]           VARCHAR (200)   NULL,
    [IsGSTRequired]               VARCHAR (50)    NULL,
    [IsPANCardRequired]           VARCHAR (50)    NULL,
    [LeaderMiddleName]            VARCHAR (150)   NULL,
    [CheckInTime]                 VARCHAR (50)    NULL,
    [CheckOutTime]                VARCHAR (50)    NULL,
    [PayAtHotel]                  BIT             NULL,
    [HotelTaxes]                  DECIMAL (18, 2) NULL,
    [HotelTotalGross]             DECIMAL (18, 2) NULL,
    [AgentCommission]             DECIMAL (18, 2) NULL,
    [HotelTDS]                    DECIMAL (18, 2) NULL,
    [BookingPortal]               VARCHAR (50)    NOT NULL,
    [ChannelId]                   VARCHAR (100)   NULL,
    [AccountId]                   VARCHAR (100)   NULL,
    [PGStatus]                    VARCHAR (100)   NULL,
    [PaybleAmountOld]             DECIMAL (18, 2) NULL,
    [SupplierBookingUrl]          VARCHAR (MAX)   NULL,
    [SupplierBookingPaymentDate]  VARCHAR (100)   NULL,
    [SupplierPkId]                BIGINT          NULL,
    [Post_addCancellationCharges] VARCHAR (50)    NULL,
    [Post_addCancellationRemarks] VARCHAR (500)   NULL,
    [GstOnServiceCharges]         DECIMAL (18, 2) NULL,
    [ServiceCharges]              DECIMAL (18, 2) NULL,
    [TotalServiceCharges]         DECIMAL (18, 2) NULL,
    [GstAmountOnServiceChagres]   DECIMAL (18, 2) NULL,
    [ReconStatus]                 VARCHAR (1)     NULL,
    [ReconDate]                   DATETIME        NULL,
    [ReconBy]                     INT             NULL,
    [ReconRemark]                 VARCHAR (MAX)   NULL,
    [FinalROE]                    DECIMAL (18, 5) NULL,
    [Lat]                         DECIMAL (18, 8) NULL,
    [Lang]                        DECIMAL (18, 8) NULL,
    [Nationalty]                  VARCHAR (100)   NULL,
    [SPublishedBaseRate]          DECIMAL (18, 2) NULL,
    [SPublishedRate]              DECIMAL (18, 2) NULL,
    [STotalRate]                  DECIMAL (18, 2) NULL,
    [SBaseRate]                   DECIMAL (18, 2) NULL,
    [SComission]                  DECIMAL (18, 2) NULL,
    [SCurrency]                   VARCHAR (50)    NULL,
    [IsApiOutBooking]             BIT             NULL,
    [RequestForCancelled]         VARCHAR (50)    NULL,
    [SupplierChargesPer]          DECIMAL (18, 2) NULL,
    [SupplierCharges]             DECIMAL (18, 6) NULL,
    [VccPer]                      DECIMAL (18, 2) NULL,
    [VccValue]                    DECIMAL (18, 4) NULL,
    [SupplierCommitionLocal]      DECIMAL (18, 2) NULL,
    [SINRCommissionAmount]        DECIMAL (18, 4) NULL,
    [SCommissionDiscription]      VARCHAR (500)   NULL,
    [agentCancellationCharges]    DECIMAL (18, 2) NULL,
    [SupplierCancellationCharges] DECIMAL (18, 2) NULL,
    [HotelIncludes]               VARCHAR (500)   NULL,
    [SupplierINRROEValue]         DECIMAL (18, 6) NULL,
    [ClientBookingId]             VARCHAR (200)   NULL,
    [MembershipNumber]            VARCHAR (50)    NULL,
    [ChainName]                   VARCHAR (150)   NULL,
    [CustomerId]                  VARCHAR (200)   NULL,
    [PanCardURL]                  VARCHAR (500)   NULL,
    [PayHotelPaymentStatus]       BIT             NULL,
    [BKCancellation]              DATETIME        NULL,
    [CancelledBy]                 INT             NULL,
    [ModeOfCancellation]          VARCHAR (20)    NULL,
    [CancellationDate]            DATETIME        NULL,
    [PaymentStatus]               VARCHAR (200)   NULL,
    [PaymentRemark]               VARCHAR (200)   NULL,
    [PNRofficeId]                 VARCHAR (20)    NULL,
    [PNRRateType]                 VARCHAR (100)   NULL,
    [FreeTextPNRInclusion]        VARCHAR (300)   NULL,
    [FreeTextPNRRoomCategory]     VARCHAR (300)   NULL,
    [AgentServiceFee]             DECIMAL (18, 2) NULL,
    [AgentServiceFeeRealTime]     DECIMAL (18, 2) NULL,
    [DestinationCountryCode]      VARCHAR (100)   NULL,
    [TdsDeductedAfterCancel]      DECIMAL (18, 2) NULL
);

