CREATE TABLE [dbo].[LCC] (
    [STATE]               NVARCHAR (255) NULL,
    [LEDGER CODE]         NVARCHAR (255) NULL,
    [CUST ID]             NVARCHAR (255) NULL,
    [Staff]               NVARCHAR (255) NULL,
    [OID]                 NVARCHAR (255) NULL,
    [Posting Date]        DATETIME       NULL,
    [Document Type]       NVARCHAR (255) NULL,
    [Invoice No]          NVARCHAR (255) NULL,
    [Product Type]        NVARCHAR (255) NULL,
    [Travel Start Date]   DATETIME       NULL,
    [Dep Time]            DATETIME       NULL,
    [Arr Time]            DATETIME       NULL,
    [Travel End Date]     DATETIME       NULL,
    [Dep Time1]           DATETIME       NULL,
    [Arr Time1]           DATETIME       NULL,
    [PNRNo]               NVARCHAR (255) NULL,
    [Supplier Code]       NVARCHAR (255) NULL,
    [Ticket No]           NVARCHAR (255) NULL,
    [Pax Name]            NVARCHAR (255) NULL,
    [Sector Name]         NVARCHAR (255) NULL,
    [Base Amount]         MONEY          NULL,
    [Tax Amount]          MONEY          NULL,
    [YQ Amount]           MONEY          NULL,
    [YR Amount]           MONEY          NULL,
    [IN Amount]           MONEY          NULL,
    [JN / K3 Amount]      MONEY          NULL,
    [XT Amount]           MONEY          NULL,
    [Extra Baggage Amt#]  MONEY          NULL,
    [Seat Pref# Chrgs#]   MONEY          NULL,
    [Meal Charges]        MONEY          NULL,
    [Wheel Chair Chrgs#]  MONEY          NULL,
    [SSR Comb Amt#]       MONEY          NULL,
    [Other Charges]       MONEY          NULL,
    [Mgmt# Fee]           MONEY          NULL,
    [PG Charges]          MONEY          NULL,
    [Gateway Charges]     MONEY          NULL,
    [Service Fee]         MONEY          NULL,
    [Discount Amount]     MONEY          NULL,
    [TDS Amount]          MONEY          NULL,
    [GST Amount]          MONEY          NULL,
    [Cancelaltion Fee]    MONEY          NULL,
    [Service Fee on Canx] MONEY          NULL,
    [UATP Amount]         MONEY          NULL,
    [Invoice Amount]      MONEY          NULL,
    [Net Amount]          MONEY          NULL,
    [UATP Sales]          NVARCHAR (255) NULL,
    [Entry Type]          NVARCHAR (255) NULL,
    [Sales Currency]      NVARCHAR (255) NULL,
    [Booking Class]       NVARCHAR (255) NULL,
    [Flight No]           NVARCHAR (255) NULL,
    [OBTC No#]            NVARCHAR (255) NULL,
    [Trip Type]           NVARCHAR (255) NULL,
    [IsPush]              BIT            NULL
);

