CREATE TABLE [dbo].[LFS_Log] (
    [Id]                        BIGINT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [OfficeId]                  NVARCHAR (50)  NULL,
    [IssuedOfficeId]            NVARCHAR (500) NULL,
    [PnrNo]                     NVARCHAR (50)  NULL,
    [InsertedOn]                DATETIME       NULL,
    [TourCode]                  NVARCHAR (100) NULL,
    [RMToEmailId]               NVARCHAR (MAX) NULL,
    [RMCcEmailId]               NVARCHAR (MAX) NULL,
    [currentFare]               DECIMAL (18)   NULL,
    [DescriptionText]           NVARCHAR (MAX) NULL,
    [LogId]                     NVARCHAR (50)  NULL,
    [foundLowerFare]            DECIMAL (18)   NULL,
    [BookingDate]               DATETIME       NULL,
    [IsTicketed]                BIT            NOT NULL,
    [CancellationCharges]       DECIMAL (18)   NULL,
    [PricingFullText]           NVARCHAR (500) NULL,
    [PricingCode]               NVARCHAR (500) NULL,
    [ValidatingCarrier]         NVARCHAR (500) NULL,
    [PassengerTatto]            NVARCHAR (500) NULL,
    [FullBaggage]               NVARCHAR (500) NULL,
    [FullBaggageLowFare]        NVARCHAR (500) NULL,
    [IsKLSegementStatusFounded] BIT            NOT NULL,
    [CurrentBaseFare]           DECIMAL (18)   NOT NULL,
    [travelDate]                DATETIME       NULL,
    [DepartmentID]              INT            NOT NULL,
    [BufferAmount]              DECIMAL (18)   NOT NULL,
    [FareType]                  VARCHAR (50)   NULL,
    CONSTRAINT [PK_LFS_Log] PRIMARY KEY CLUSTERED ([Id] ASC)
);

