CREATE TABLE [dbo].[mAirlinePopup] (
    [ID]             INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [UserType]       VARCHAR (10)  NOT NULL,
    [Country]        VARCHAR (10)  NOT NULL,
    [AgencyName]     VARCHAR (MAX) NULL,
    [AgencyId]       VARCHAR (MAX) NULL,
    [AirportType]    VARCHAR (10)  NULL,
    [AirlineName]    VARCHAR (MAX) NULL,
    [Vendor]         VARCHAR (MAX) NULL,
    [Cabin]          VARCHAR (50)  NULL,
    [FareType]       VARCHAR (50)  NULL,
    [FareIndicator]  VARCHAR (50)  NULL,
    [RBD]            VARCHAR (MAX) NULL,
    [FareBasis]      VARCHAR (MAX) NULL,
    [FlightNo]       VARCHAR (MAX) NULL,
    [Origin]         VARCHAR (MAX) NULL,
    [Destination]    VARCHAR (MAX) NULL,
    [FromDate]       DATETIME2 (7) NULL,
    [ToDate]         DATETIME2 (7) NULL,
    [DisplayMessage] VARCHAR (MAX) NULL,
    [Remark]         VARCHAR (MAX) NULL,
    [IsActive]       BIT           CONSTRAINT [DF_mAirlinePopup_IsActive] DEFAULT ((1)) NOT NULL,
    [IsBlocked]      BIT           CONSTRAINT [DF_mAirlinePopup_IsBlocked] DEFAULT ((0)) NOT NULL,
    [CreatedOn]      DATETIME2 (7) CONSTRAINT [DF_mAirlinePopup_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]      INT           NOT NULL,
    [ModifiedOn]     DATETIME2 (7) NULL,
    [ModifiedBy]     INT           NULL,
    CONSTRAINT [PK_mAirlinePopup] PRIMARY KEY CLUSTERED ([ID] ASC)
);

