CREATE TABLE [dbo].[mAttrributesDetails_27_9_2024] (
    [ID]                                  INT           IDENTITY (1, 1) NOT NULL,
    [OrderID]                             VARCHAR (50)  NULL,
    [GDSPNR]                              VARCHAR (50)  NULL,
    [JobCodeBookingGivenBy]               VARCHAR (50)  NULL,
    [VesselName]                          VARCHAR (50)  NULL,
    [ReasonofTravel]                      VARCHAR (300) NULL,
    [TravelRequestNumber]                 VARCHAR (15)  NULL,
    [CostCenter]                          VARCHAR (50)  NULL,
    [BudgetCode]                          VARCHAR (15)  NULL,
    [EmpDimession]                        VARCHAR (50)  NULL,
    [SwonNo]                              VARCHAR (15)  NULL,
    [TravelerType]                        VARCHAR (15)  NULL,
    [Location]                            VARCHAR (15)  NULL,
    [Department]                          VARCHAR (15)  NULL,
    [Grade]                               VARCHAR (15)  NULL,
    [Bookedby]                            VARCHAR (15)  NULL,
    [Designation]                         VARCHAR (15)  NULL,
    [Chargeability]                       VARCHAR (15)  NULL,
    [NameofApprover]                      VARCHAR (15)  NULL,
    [ReferenceNo]                         VARCHAR (15)  NULL,
    [TR_POName]                           VARCHAR (15)  NULL,
    [RankNo]                              VARCHAR (15)  NULL,
    [AType]                               VARCHAR (15)  NULL,
    [BookingReceivedDate]                 VARCHAR (50)  NULL,
    [CreatedOn]                           VARCHAR (30)  NULL,
    [CreatedBy]                           INT           NULL,
    [SeamanValue]                         TINYINT       NULL,
    [paxvisa]                             VARCHAR (30)  NULL,
    [OBTCno]                              VARCHAR (50)  NULL,
    [Changedcostno]                       VARCHAR (50)  NULL,
    [Travelduration]                      VARCHAR (50)  NULL,
    [TASreqno]                            VARCHAR (50)  NULL,
    [Companycodecc]                       VARCHAR (50)  NULL,
    [Projectcode]                         VARCHAR (50)  NULL,
    [Traveltype]                          VARCHAR (50)  NULL,
    [PanCardno]                           VARCHAR (50)  NULL,
    [DEVIATION_APPROVER_NAME_AND_EMPCODE] VARCHAR (255) NULL,
    [LOWEST_LOGICAL_FARE_1]               VARCHAR (50)  NULL,
    [LOWEST_LOGICAL_FARE_2]               VARCHAR (50)  NULL,
    [LOWEST_LOGICAL_FARE_3]               VARCHAR (50)  NULL,
    [CLIQCID]                             VARCHAR (100) NULL,
    [CLIQCONFIGID]                        VARCHAR (100) NULL,
    [TRVELKEYNO]                          VARCHAR (100) NULL,
    [NARRATION]                           VARCHAR (100) NULL,
    [OUNameIDF]                           INT           NULL,
    [RoleBand]                            VARCHAR (100) NULL,
    [EmpLocation]                         VARCHAR (100) NULL,
    [VerticalLocation]                    VARCHAR (100) NULL,
    [Horizontal]                          VARCHAR (100) NULL,
    [Vertical]                            VARCHAR (100) NULL,
    [BTANO]                               VARCHAR (50)  NULL,
    [RequestID]                           VARCHAR (50)  NULL,
    [fkPassengerid]                       BIGINT        NULL,
    [WinYatraPush]                        BIT           NULL,
    [PaxName]                             VARCHAR (255) NULL,
    [SectorNo]                            INT           NULL,
    [FileNo]                              VARCHAR (50)  NULL,
    [InquiryNo]                           VARCHAR (50)  NULL,
    [OPSRemark]                           VARCHAR (50)  NULL,
    [AcctsRemark]                         VARCHAR (50)  NULL,
    [FareType]                            VARCHAR (25)  NULL,
    [FareRule]                            VARCHAR (25)  NULL,
    [TravelOfficer]                       VARCHAR (200) NULL,
    [TravelTypeNew]                       VARCHAR (200) NULL,
    [GDS]                                 VARCHAR (200) NULL,
    [TripType]                            VARCHAR (200) NULL,
    [Remarks]                             VARCHAR (200) NULL,
    [CarbonFootprint]                     VARCHAR (200) NULL,
    [CurrencyConversionRate]              VARCHAR (50)  NULL,
    [PID]                                 VARCHAR (200) NULL,
    [Account]                             VARCHAR (200) NULL,
    [UID]                                 VARCHAR (200) NULL,
    [ProjectName]                         VARCHAR (200) NULL,
    [CostCentre]                          VARCHAR (200) NULL,
    [ConcurID]                            VARCHAR (50)  NULL,
    [ApproverName]                        VARCHAR (200) NULL
);

