CREATE TABLE [dbo].[mFareType_27aug2024] (
    [ID]                 INT           IDENTITY (1, 1) NOT NULL,
    [UserType]           VARCHAR (50)  NULL,
    [Country]            VARCHAR (10)  NULL,
    [Airline]            VARCHAR (MAX) NULL,
    [LoginId]            VARCHAR (MAX) NULL,
    [AirportType]        VARCHAR (10)  NULL,
    [AgencyId]           VARCHAR (MAX) NULL,
    [AgencyName]         VARCHAR (MAX) NULL,
    [Cabin]              VARCHAR (MAX) NULL,
    [IncludeFare]        VARCHAR (MAX) NULL,
    [ExcludeFare]        VARCHAR (MAX) NULL,
    [Origin]             BIT           NOT NULL,
    [OriginValue]        VARCHAR (MAX) NULL,
    [Destination]        BIT           NOT NULL,
    [DestinationValue]   VARCHAR (MAX) NULL,
    [RBD]                BIT           NOT NULL,
    [RBDValue]           VARCHAR (MAX) NULL,
    [TravelValidityFrom] DATETIME2 (7) NULL,
    [TravelValidityTo]   DATETIME2 (7) NULL,
    [SaleValidityFrom]   DATETIME2 (7) NULL,
    [SaleValidityTo]     DATETIME2 (7) NULL,
    [FareRuleInfo]       VARCHAR (MAX) NULL,
    [Blocked]            BIT           NOT NULL,
    [CreatedOn]          DATETIME2 (7) NOT NULL,
    [CreatedBy]          INT           NULL,
    [ModifiedBy]         INT           NULL,
    [ModifiedOn]         DATETIME2 (7) NULL,
    [IsActive]           BIT           NOT NULL,
    [ProductClass]       VARCHAR (100) NULL,
    [Source]             VARCHAR (20)  NULL
);

