CREATE TABLE [dbo].[mFareType] (
    [ID]                 INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [UserType]           VARCHAR (50)  NULL,
    [Country]            VARCHAR (10)  NULL,
    [Airline]            VARCHAR (MAX) NULL,
    [LoginId]            VARCHAR (MAX) NULL,
    [AirportType]        VARCHAR (10)  NULL,
    [AgencyId]           VARCHAR (MAX) NULL,
    [AgencyName]         VARCHAR (MAX) NULL,
    [Cabin]              VARCHAR (MAX) NULL,
    [IncludeFare]        VARCHAR (MAX) NULL,
    [ExcludeFare]        VARCHAR (MAX) NULL,
    [Origin]             BIT           CONSTRAINT [DF_mFareType_Origin] DEFAULT ((0)) NOT NULL,
    [OriginValue]        VARCHAR (MAX) NULL,
    [Destination]        BIT           CONSTRAINT [DF_mFareType_Destination] DEFAULT ((0)) NOT NULL,
    [DestinationValue]   VARCHAR (MAX) NULL,
    [RBD]                BIT           CONSTRAINT [DF_mFareType_RBD] DEFAULT ((0)) NOT NULL,
    [RBDValue]           VARCHAR (MAX) NULL,
    [TravelValidityFrom] DATETIME2 (7) NULL,
    [TravelValidityTo]   DATETIME2 (7) NULL,
    [SaleValidityFrom]   DATETIME2 (7) NULL,
    [SaleValidityTo]     DATETIME2 (7) NULL,
    [FareRuleInfo]       VARCHAR (MAX) NULL,
    [Blocked]            BIT           CONSTRAINT [DF_mFareType_Blocked] DEFAULT ((0)) NOT NULL,
    [CreatedOn]          DATETIME2 (7) CONSTRAINT [DF_mFareType_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]          INT           NULL,
    [ModifiedBy]         INT           NULL,
    [ModifiedOn]         DATETIME2 (7) NULL,
    [IsActive]           BIT           CONSTRAINT [DF_mFareType_IsActive] DEFAULT ((1)) NOT NULL,
    [ProductClass]       VARCHAR (100) NULL,
    [Source]             VARCHAR (20)  NULL,
    CONSTRAINT [PK_mFareType] PRIMARY KEY CLUSTERED ([ID] ASC)
);

