CREATE TABLE [dbo].[mROEUpdation] (
    [ID]             INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [UserTypeId]     INT             NOT NULL,
    [CountryId]      INT             NOT NULL,
    [ProductId]      INT             NOT NULL,
    [AirLineId]      INT             NULL,
    [BaseCurrencyId] INT             NOT NULL,
    [ToCurrencyId]   INT             NOT NULL,
    [ROE]            DECIMAL (18, 6) NOT NULL,
    [CreatedOn]      DATETIME        CONSTRAINT [DF_mROEUpdation_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]      INT             NOT NULL,
    [ModifiedBy]     INT             NULL,
    [ModifiedOn]     DATETIME        CONSTRAINT [DF_mROEUpdation_ModifiedOn] DEFAULT (getdate()) NULL,
    [IsActive]       BIT             CONSTRAINT [DF_mROEUpdation_IsActive] DEFAULT ((1)) NOT NULL,
    [GDSTypeID]      INT             NULL,
    [VendorId]       INT             NULL,
    [OfficeID]       INT             NULL,
    [OfficeIdText]   VARCHAR (100)   NULL,
    [State]          VARCHAR (MAX)   NULL,
    [Branch]         VARCHAR (MAX)   NULL,
    [Flag]           BIT             CONSTRAINT [DF_mROEUpdation_Flag] DEFAULT ((1)) NOT NULL,
    [MarkupType]     VARCHAR (50)    NULL,
    [MarkupData]     DECIMAL (18, 6) NULL,
    [IsAddSubtract]  INT             NULL,
    [IsROEMarkup]    BIT             NULL,
    [MarkupAmount]   DECIMAL (18, 6) NULL,
    [VendorROE]      DECIMAL (18, 6) NULL,
    CONSTRAINT [PK_mROEUpdation] PRIMARY KEY CLUSTERED ([ID] ASC)
);

