CREATE TABLE [dbo].[mROEUpdationHistory] (
    [ID]             INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Action]         VARCHAR (10)    NOT NULL,
    [ROEId]          INT             NULL,
    [UserTypeId]     INT             NOT NULL,
    [CountryId]      INT             NOT NULL,
    [ProductId]      INT             NOT NULL,
    [AirLineId]      VARCHAR (MAX)   NULL,
    [IsAllAirline]   BIT             CONSTRAINT [DF_mROEUpdationHistory_IsAllAirline] DEFAULT ((0)) NOT NULL,
    [AgencyId]       VARCHAR (MAX)   NULL,
    [IsAllAgency]    BIT             CONSTRAINT [DF_mROEUpdationHistory_IsAllAgency] DEFAULT ((0)) NOT NULL,
    [GDSTypeId]      INT             NULL,
    [VendorId]       INT             NULL,
    [OfficeId]       INT             NULL,
    [OfficeIdText]   VARCHAR (100)   NULL,
    [BaseCurrencyId] INT             NOT NULL,
    [ToCurrencyId]   INT             NOT NULL,
    [ROE]            DECIMAL (18, 6) NOT NULL,
    [ModifiedBy]     INT             NULL,
    [ModifiedOn]     DATETIME        CONSTRAINT [DF_mROEUpdationHistory_ModifiedOn] DEFAULT (getdate()) NULL,
    [StateId]        VARCHAR (MAX)   NULL,
    [BranchId]       VARCHAR (MAX)   NULL,
    [Flag]           BIT             CONSTRAINT [DF_mROEUpdationHistory_Flag] DEFAULT ((1)) NOT NULL,
    [MarkupType]     VARCHAR (50)    NULL,
    [MarkupData]     DECIMAL (18, 6) NULL,
    [IsAddSubtract]  INT             NULL,
    [IsROEMarkup]    BIT             NULL,
    [MarkupAmount]   DECIMAL (18, 6) NULL,
    [VendorROE]      DECIMAL (18, 6) NULL,
    CONSTRAINT [PK_mROEUpdationHistory] PRIMARY KEY CLUSTERED ([ID] ASC)
);

