CREATE TABLE [dbo].[muser_24Dec2024] (
    [ID]                 INT             IDENTITY (1, 1) NOT NULL,
    [FullName]           VARCHAR (50)    NULL,
    [UserName]           VARCHAR (100)   NULL,
    [Password]           VARCHAR (128)   NULL,
    [MobileNo]           VARCHAR (15)    NULL,
    [EmailID]            VARCHAR (100)   NULL,
    [LocationID]         INT             NULL,
    [DepartmentID]       INT             NULL,
    [CountryID]          INT             NULL,
    [EmployeeNo]         VARCHAR (20)    NULL,
    [RoleID]             INT             NULL,
    [CreatedOn]          DATETIME        NOT NULL,
    [CreatedBy]          INT             NOT NULL,
    [ModifiedOn]         DATETIME        NULL,
    [ModifiedBy]         INT             NULL,
    [isActive]           BIT             NOT NULL,
    [isResetPassword]    BIT             NOT NULL,
    [SessionID]          VARCHAR (50)    NULL,
    [UserTypeId]         INT             NULL,
    [AutoTicketing]      BIT             NULL,
    [AgentBalance]       DECIMAL (18, 3) NULL,
    [SelfBalance]        BIT             NULL,
    [CancelRequest]      BIT             NULL,
    [GhostTrack]         BIT             NOT NULL,
    [ConsoleSessionId]   VARCHAR (50)    NULL,
    [NewSelfBalance]     BIT             NOT NULL,
    [GroupId]            INT             NULL,
    [UserDeviceID]       VARCHAR (100)   NULL,
    [UserDeviceIDTime]   DATETIME        NULL,
    [OTPGenerated]       VARCHAR (100)   NULL,
    [OTPTime]            DATETIME        NULL,
    [LoginAttempt]       INT             NULL,
    [AttemptNo]          INT             NULL,
    [AttemptedDate]      DATETIME        NULL,
    [ContractCommission] BIT             NULL,
    [LastLoginDate]      DATETIME        NULL,
    [OTPRequired]        BIT             NULL,
    [LoginFromCountry]   VARCHAR (MAX)   NULL,
    [NewGroupid]         TEXT            NULL
);

