CREATE TABLE [dbo].[mUser] (
    [ID]                 INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [FullName]           VARCHAR (50)    NULL,
    [UserName]           VARCHAR (100)   NULL,
    [Password]           VARCHAR (128)   NULL,
    [MobileNo]           VARCHAR (15)    NULL,
    [EmailID]            VARCHAR (100)   NULL,
    [LocationID]         INT             NULL,
    [DepartmentID]       INT             NULL,
    [CountryID]          INT             NULL,
    [EmployeeNo]         VARCHAR (20)    NULL,
    [RoleID]             INT             NULL,
    [CreatedOn]          DATETIME        CONSTRAINT [DF_mUser_CreatedOn_Value] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]          INT             NOT NULL,
    [ModifiedOn]         DATETIME        CONSTRAINT [DF_mUser_ModifiedOn_Value] DEFAULT (getdate()) NULL,
    [ModifiedBy]         INT             NULL,
    [isActive]           BIT             CONSTRAINT [DF__mUser__isActive__1B5FA437] DEFAULT ((1)) NOT NULL,
    [isResetPassword]    BIT             CONSTRAINT [DF_mUser_isResetPassword] DEFAULT ((0)) NOT NULL,
    [SessionID]          VARCHAR (50)    NULL,
    [UserTypeId]         INT             NULL,
    [AutoTicketing]      BIT             NULL,
    [AgentBalance]       DECIMAL (18, 3) NULL,
    [SelfBalance]        BIT             CONSTRAINT [DF_mUser_SelfBalance] DEFAULT ((0)) NULL,
    [CancelRequest]      BIT             CONSTRAINT [DF_mUser_CancelRequest] DEFAULT ((0)) NULL,
    [GhostTrack]         BIT             CONSTRAINT [DF_mUser_GhostTrack] DEFAULT ((0)) NOT NULL,
    [ConsoleSessionId]   VARCHAR (50)    NULL,
    [NewSelfBalance]     BIT             NOT NULL,
    [GroupId]            INT             CONSTRAINT [DF_mUser_GroupId] DEFAULT ((1)) NULL,
    [UserDeviceID]       VARCHAR (100)   NULL,
    [UserDeviceIDTime]   DATETIME        NULL,
    [OTPGenerated]       VARCHAR (100)   CONSTRAINT [DF__mUser__OTPGenera__1C29AB3E] DEFAULT (NULL) NULL,
    [OTPTime]            DATETIME        CONSTRAINT [DF__mUser__OTPTime__1D1DCF77] DEFAULT (NULL) NULL,
    [LoginAttempt]       INT             NULL,
    [AttemptNo]          INT             NULL,
    [AttemptedDate]      DATETIME        NULL,
    [ContractCommission] BIT             NULL,
    [LastLoginDate]      DATETIME        CONSTRAINT [DF_mUser_LastLoginDate] DEFAULT (getdate()) NULL,
    [OTPRequired]        BIT             NULL,
    [LoginFromCountry]   VARCHAR (MAX)   NULL,
    [NewGroupid]         TEXT            NULL,
    CONSTRAINT [PK__mUser__1788CC4C90E6BB8A] PRIMARY KEY CLUSTERED ([ID] ASC)
);

