CREATE TABLE [dbo].[PNRRetrivalFromAudit] (
    [Id]                     INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [GDSPNR]                 VARCHAR (10)    NULL,
    [AirLineNumber]          VARCHAR (10)    NULL,
    [TicketNumber]           VARCHAR (50)    NULL,
    [OfficeID]               VARCHAR (20)    NULL,
    [ICust]                  VARCHAR (255)   NULL,
    [InsertedOn]             DATETIME        NULL,
    [IssueDate]              DATETIME        NULL,
    [IsBookMasterInserted]   INT             NULL,
    [IsBookMasterInsertedOn] DATETIME        NULL,
    [ErrorMessage]           VARCHAR (MAX)   NULL,
    [QueueNo]                VARCHAR (10)    NULL,
    [DayIndicator]           VARCHAR (10)    NULL,
    [Type]                   VARCHAR (20)    NULL,
    [APE]                    VARCHAR (MAX)   NULL,
    [LOWEST_LOGICAL_FARE_1]  VARCHAR (255)   NULL,
    [LOWEST_LOGICAL_FARE_2]  VARCHAR (255)   NULL,
    [LOWEST_LOGICAL_FARE_3]  VARCHAR (255)   NULL,
    [CRSType]                VARCHAR (50)    NULL,
    [TransactionCode]        VARCHAR (255)   NULL,
    [EmpID]                  VARCHAR (255)   NULL,
    [CLIQCID]                VARCHAR (255)   NULL,
    [CLIQCONFIGID]           VARCHAR (255)   NULL,
    [MainAgentId]            VARCHAR (50)    NULL,
    [passengerName]          VARCHAR (200)   NULL,
    [conjTicketNumber]       VARCHAR (20)    NULL,
    [totalFare]              VARCHAR (50)    NULL,
    [baseFare]               VARCHAR (50)    NULL,
    [ticketIssueDate]        DATE            NULL,
    [IATA_Number]            BIGINT          NULL,
    [Status]                 VARCHAR (50)    NULL,
    [TaxDesc]                VARCHAR (500)   NULL,
    [ReasonForIssuance]      VARCHAR (200)   NULL,
    [PassengerType]          VARCHAR (10)    NULL,
    [TicketingStatus]        VARCHAR (50)    NULL,
    [GuaranteedFare]         VARCHAR (50)    NULL,
    [FormOfPayment]          VARCHAR (50)    NULL,
    [TotalTax]               VARCHAR (50)    NULL,
    [CommissionRate]         DECIMAL (18, 3) NULL,
    [TourCode]               VARCHAR (15)    NULL,
    [EquivFare]              VARCHAR (50)    NULL,
    [CurrencyCode]           VARCHAR (5)     NULL,
    [yq]                     NVARCHAR (100)  NULL,
    [in]                     NVARCHAR (100)  NULL,
    [cpnStatus]              NVARCHAR (100)  NULL,
    [OB]                     NVARCHAR (200)  NULL,
    [OC]                     NVARCHAR (200)  NULL,
    [WO]                     NVARCHAR (200)  NULL,
    [JN]                     NVARCHAR (200)  NULL,
    [YM]                     NVARCHAR (200)  NULL,
    [F2]                     NVARCHAR (200)  NULL,
    [G1]                     NVARCHAR (200)  NULL,
    [K3]                     NVARCHAR (200)  NULL,
    [YR]                     NVARCHAR (200)  NULL,
    [XT]                     NVARCHAR (200)  NULL,
    [Fee]                    NVARCHAR (200)  NULL,
    [Product_Type]           NVARCHAR (200)  NULL,
    [SaveCoupon_Flag]        NVARCHAR (200)  NULL,
    [CRSCode]                NVARCHAR (200)  NULL,
    [PCCCode]                NVARCHAR (200)  NULL,
    [CreditCardNumber]       NVARCHAR (200)  NULL,
    [Commission_Amount]      DECIMAL (18, 2) NULL,
    [TicketType]             VARCHAR (100)   NULL,
    [OldTicketNo]            VARCHAR (100)   NULL,
    [Canfees]                DECIMAL (18, 2) NULL,
    [fop]                    VARCHAR (50)    NULL,
    [transactionType]        VARCHAR (100)   NULL,
    [CCExpiryDate]           VARCHAR (200)   NULL,
    [IsEmailSend]            BIT             NULL,
    CONSTRAINT [PK_PNRRetrivalFromAudit] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [Noncluster_CompositeIndex]
    ON [dbo].[PNRRetrivalFromAudit]([GDSPNR] ASC, [OfficeID] ASC, [ICust] ASC, [IsBookMasterInserted] ASC);

