CREATE TABLE [dbo].[tbl_ServiceFee_GST_QuatationDetails] (
    [Id]                 INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [MarketPoint]        VARCHAR (30)    NULL,
    [AirportType]        VARCHAR (50)    NULL,
    [AirlineType]        VARCHAR (MAX)   NULL,
    [UserType]           VARCHAR (10)    NULL,
    [GroupType]          VARCHAR (100)   NULL,
    [AgencyId]           VARCHAR (MAX)   NULL,
    [AgentCategory]      VARCHAR (MAX)   NULL,
    [AgencyNames]        VARCHAR (MAX)   NULL,
    [Remark]             VARCHAR (MAX)   NULL,
    [TravelValidityFrom] DATETIME        NULL,
    [TravelValidityTo]   DATETIME        NULL,
    [SaleValidityFrom]   DATETIME        NULL,
    [SaleValidityTo]     DATETIME        NULL,
    [RBD]                BIT             CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetails_RBD] DEFAULT ((0)) NULL,
    [RBDValue]           VARCHAR (MAX)   NULL,
    [FareBasis]          BIT             CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetails_FareBasis] DEFAULT ((0)) NULL,
    [FareBasisValue]     VARCHAR (MAX)   NULL,
    [FlightSeries]       BIT             CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetails_FlightSeries] DEFAULT ((0)) NULL,
    [FlightSeriesValue]  VARCHAR (MAX)   NULL,
    [Origin]             BIT             CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetails_Origin] DEFAULT ((0)) NULL,
    [OriginValue]        VARCHAR (MAX)   NULL,
    [Destination]        BIT             CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetails_Destination] DEFAULT ((0)) NULL,
    [DestinationValue]   VARCHAR (MAX)   NULL,
    [InsertedDate]       DATETIME        NULL,
    [Flag]               BIT             CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetails_Flag] DEFAULT ((1)) NULL,
    [FlightNo]           BIT             CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetails_FlightNo] DEFAULT ((0)) NULL,
    [FlightNoValue]      VARCHAR (MAX)   NULL,
    [Cabin]              VARCHAR (50)    NULL,
    [ServiceFee]         DECIMAL (18, 2) NULL,
    [GST]                INT             NULL,
    [Quatation]          INT             NULL,
    [UserID]             INT             NULL,
    [UpdatedDate]        DATETIME        CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetails_UpdatedDate] DEFAULT (getdate()) NULL,
    [BookingType]        INT             NULL,
    [Currency]           VARCHAR (10)    NULL,
    [TransactionType]    VARCHAR (50)    NULL,
    [CRSType]            VARCHAR (50)    NULL,
    [AvailabilityPCC]    VARCHAR (50)    NULL,
    [OriginCountry]      VARCHAR (MAX)   NULL,
    [DestinationCountry] VARCHAR (MAX)   NULL,
    CONSTRAINT [PK_tbl_ServiceFee_GST_QuatationDetails] PRIMARY KEY CLUSTERED ([Id] ASC)
);

