CREATE TABLE [dbo].[tbl_ServiceFee_GST_QuatationDetailsDelete] (
    [Id]                 INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [MarketPoint]        VARCHAR (30)    NULL,
    [AirportType]        VARCHAR (50)    NULL,
    [AirlineType]        VARCHAR (50)    NULL,
    [UserType]           VARCHAR (10)    NULL,
    [GroupType]          VARCHAR (100)   NULL,
    [AgencyId]           VARCHAR (MAX)   NULL,
    [AgentCategory]      VARCHAR (MAX)   NULL,
    [AgencyNames]        VARCHAR (MAX)   NULL,
    [Remark]             VARCHAR (MAX)   NULL,
    [TravelValidityFrom] DATETIME        NULL,
    [TravelValidityTo]   DATETIME        NULL,
    [SaleValidityFrom]   DATETIME        NULL,
    [SaleValidityTo]     DATETIME        NULL,
    [RBD]                BIT             CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetailsDelete_RBD] DEFAULT ((0)) NULL,
    [RBDValue]           VARCHAR (MAX)   NULL,
    [FareBasis]          BIT             CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetailsDelete_FareBasis] DEFAULT ((0)) NULL,
    [FareBasisValue]     VARCHAR (MAX)   NULL,
    [FlightSeries]       BIT             CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetailsDelete_FlightSeries] DEFAULT ((0)) NULL,
    [FlightSeriesValue]  VARCHAR (MAX)   NULL,
    [Origin]             BIT             CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetailsDelete_Origin] DEFAULT ((0)) NULL,
    [OriginValue]        VARCHAR (MAX)   NULL,
    [Destination]        BIT             CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetailsDelete_Destination] DEFAULT ((0)) NULL,
    [DestinationValue]   VARCHAR (MAX)   NULL,
    [InsertedDate]       DATETIME        NULL,
    [Flag]               BIT             CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetailsDelete_Flag] DEFAULT ((1)) NULL,
    [FlightNo]           BIT             CONSTRAINT [DF_tbl_ServiceFee_GST_QuatationDetailsDelete_FlightNo] DEFAULT ((0)) NULL,
    [FlightNoValue]      VARCHAR (MAX)   NULL,
    [Cabin]              VARCHAR (50)    NULL,
    [ServiceFee]         DECIMAL (18, 2) NULL,
    [GST]                INT             NULL,
    [Quatation]          INT             NULL,
    [DeletedBy]          VARCHAR (200)   NULL,
    [DeletedOn]          DATETIME        NULL,
    [Currency]           VARCHAR (10)    NULL,
    [Action]             VARCHAR (50)    NULL,
    CONSTRAINT [PK_tbl_ServiceFee_GST_QuatationDetailsDelete] PRIMARY KEY CLUSTERED ([Id] ASC)
);

