CREATE TABLE [dbo].[TblAirline] (
    [Id]                 INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [AirlineName]        NVARCHAR (50)  NULL,
    [ContinentAdjective] NVARCHAR (MAX) NULL,
    [AirlineImage]       NVARCHAR (MAX) NULL,
    [DelayedFlights]     FLOAT (53)     NULL,
    [Punctuality]        FLOAT (53)     NULL,
    [FlightsCancelled]   FLOAT (53)     NULL,
    [HandLuggage]        NVARCHAR (MAX) NULL,
    [CheckInLuggage]     NVARCHAR (MAX) NULL,
    [PopularDestination] NVARCHAR (MAX) NULL,
    [Urlstructure]       NVARCHAR (MAX) NULL,
    [GoogleAnalytics]    NVARCHAR (MAX) NULL,
    [IsActive]           BIT            NULL,
    [CurrentTimeStamp]   DATETIME       NULL,
    [U_id]               INT            NULL,
    [MetaTitle]          NVARCHAR (MAX) NULL,
    [MetaDescription]    NVARCHAR (MAX) NULL,
    [Keywords]           NVARCHAR (MAX) NULL,
    [QuickFacts]         NVARCHAR (MAX) NULL,
    [Description]        NVARCHAR (MAX) NULL,
    [BannerImage]        NVARCHAR (MAX) NULL,
    [SimilarAirline]     NVARCHAR (MAX) NULL,
    [LastModifiedDate]   DATETIME       NULL,
    [ModifiedBy]         INT            NULL,
    [AirlineType]        NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_TblAirline] PRIMARY KEY CLUSTERED ([Id] ASC)
);

