CREATE TABLE [dbo].[tblBookMasterHistory] (
    [pkId]                    BIGINT           NOT NULL,
    [orderId]                 VARCHAR (30)     NULL,
    [frmSector]               VARCHAR (50)     NOT NULL,
    [toSector]                VARCHAR (50)     NOT NULL,
    [fromAirport]             VARCHAR (150)    NULL,
    [toAirport]               VARCHAR (150)    NULL,
    [airName]                 VARCHAR (150)    NULL,
    [operatingCarrier]        VARCHAR (50)     NULL,
    [airCode]                 VARCHAR (10)     NULL,
    [equipment]               VARCHAR (100)    NULL,
    [flightNo]                VARCHAR (10)     NULL,
    [isReturnJourney]         BIT              CONSTRAINT [DF_tblBookMasterHistory_isReturnJourney] DEFAULT ((0)) NULL,
    [depDate]                 DATE             NULL,
    [arrivalDate]             DATE             NULL,
    [riyaPNR]                 VARCHAR (10)     NULL,
    [taxDesc]                 VARCHAR (1000)   NULL,
    [totalFare]               DECIMAL (18, 2)  NULL,
    [totalTax]                DECIMAL (18, 2)  NULL,
    [basicFare]               DECIMAL (18, 2)  NULL,
    [deptTime]                DATETIME         NULL,
    [canceledDate]            DATETIME         NULL,
    [arrivalTime]             DATETIME         NULL,
    [GDSPNR]                  VARCHAR (30)     NULL,
    [IsBooked]                BIT              CONSTRAINT [DF_tblBookMasterHistory_IsBooked] DEFAULT ((0)) NULL,
    [inserteddate]            DATETIME         CONSTRAINT [DF_tblBookMasterHistory_inserteddate] DEFAULT (getdate()) NULL,
    [IP]                      VARCHAR (50)     NULL,
    [TotalDiscount]           DECIMAL (18, 2)  NULL,
    [FlatDiscount]            DECIMAL (18, 2)  NULL,
    [CancellationCharge]      DECIMAL (18, 2)  NULL,
    [ServiceCharge]           DECIMAL (18, 2)  NULL,
    [promoCode]               VARCHAR (50)     NULL,
    [GovtTax]                 DECIMAL (18, 2)  NULL,
    [mobileNo]                VARCHAR (20)     NULL,
    [emailId]                 VARCHAR (50)     NULL,
    [returnFlag]              BIT              CONSTRAINT [DF_tblBookMasterHistory_returnFlag] DEFAULT ((0)) NULL,
    [travClass]               VARCHAR (50)     NULL,
    [fromTerminal]            VARCHAR (20)     NULL,
    [toTerminal]              VARCHAR (20)     NULL,
    [TotalTime]               VARCHAR (10)     NULL,
    [CounterCloseTime]        INT              NULL,
    [Remarks]                 VARCHAR (1000)   NULL,
    [YRTax]                   DECIMAL (18, 2)  NULL,
    [INTax]                   DECIMAL (18, 2)  NULL,
    [JNTax]                   DECIMAL (18, 2)  NULL,
    [OCTax]                   DECIMAL (18, 2)  NULL,
    [ExtraTax]                DECIMAL (18, 2)  NULL,
    [YQTax]                   DECIMAL (18, 2)  NULL,
    [UserID]                  BIGINT           NULL,
    [CommissionType]          INT              NULL,
    [ServiceChargeType]       INT              NULL,
    [FlatDiscountType]        INT              NULL,
    [CancellationChargeType]  INT              NULL,
    [FareSellKey]             VARCHAR (100)    NULL,
    [JourneySellKey]          VARCHAR (100)    NULL,
    [IATACommission]          DECIMAL (18, 2)  NULL,
    [PLBCommission]           DECIMAL (18, 2)  NULL,
    [IATAPercent]             DECIMAL (18, 2)  NULL,
    [PLBPercent]              DECIMAL (18, 2)  NULL,
    [VendorCommissionPercent] NVARCHAR (50)    NULL,
    [VendorCommissionText]    VARCHAR (50)     NULL,
    [IsIATAOnBasic]           BIT              NULL,
    [IsPLBOnBasic]            BIT              NULL,
    [GovtTaxPercent]          DECIMAL (18, 2)  NULL,
    [UniqueID]                UNIQUEIDENTIFIER NULL,
    [BookingSource]           VARCHAR (50)     NULL,
    [SessionId]               VARCHAR (150)    NULL,
    [LoginEmailID]            VARCHAR (50)     NULL,
    [RegistrationNumber]      VARCHAR (50)     NULL,
    [CompanyName]             VARCHAR (50)     NULL,
    [CAddress]                VARCHAR (50)     NULL,
    [CState]                  VARCHAR (50)     NULL,
    [CContactNo]              VARCHAR (50)     NULL,
    [CEmailID]                VARCHAR (50)     NULL,
    [PromoDiscount]           DECIMAL (18, 2)  NULL,
    [TicketIssuanceError]     VARCHAR (2000)   NULL,
    [OfficeID]                VARCHAR (50)     NULL,
    [Country]                 VARCHAR (2)      NULL,
    [ROE]                     DECIMAL (18, 10) NULL,
    [AgentID]                 VARCHAR (50)     NULL,
    [AgentAction]             INT              NULL,
    [AgentDealDiscount]       NUMERIC (18, 2)  NULL,
    [TicketIssue]             BIT              NULL,
    [SupplierCode]            VARCHAR (5)      NULL,
    [VendorCode]              VARCHAR (15)     NULL,
    [TotalMarkup]             DECIMAL (18, 2)  CONSTRAINT [DF_tblBookMasterHistory_TotalMarkup] DEFAULT ((0)) NULL,
    [BookingType]             INT              NULL,
    [DisplayType]             INT              NULL,
    [CalculationType]         INT              NULL,
    [AgentMarkup]             DECIMAL (18, 2)  CONSTRAINT [DF_tblBookMasterHistory_AgentMarkup] DEFAULT ((0)) NULL,
    [TicketMail]              BIT              NULL,
    [journey]                 CHAR (1)         NULL,
    [inserteddate_old]        DATETIME         NULL,
    [TrackID]                 NVARCHAR (100)   NULL,
    [Vendor_No]               NVARCHAR (50)    NULL,
    [IATA]                    NVARCHAR (50)    NULL,
    [FareType]                VARCHAR (50)     NULL,
    CONSTRAINT [PK_tblBookMasterHistory] PRIMARY KEY CLUSTERED ([pkId] ASC)
);

