CREATE TABLE [dbo].[TblCity] (
    [ID]               INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CityName]         NVARCHAR (MAX) NULL,
    [CityAdjective]    NVARCHAR (MAX) NULL,
    [CountryName]      NVARCHAR (MAX) NULL,
    [Rate]             FLOAT (53)     NULL,
    [CityImage]        NVARCHAR (MAX) NULL,
    [AirportName]      NVARCHAR (MAX) NULL,
    [AirportImage]     NVARCHAR (MAX) NULL,
    [Routs]            NVARCHAR (MAX) NULL,
    [Price]            FLOAT (53)     NULL,
    [BannerImage]      NVARCHAR (MAX) NULL,
    [UrlStructure]     NVARCHAR (MAX) NULL,
    [MetaTitle]        NVARCHAR (MAX) NULL,
    [MetaDescription]  NVARCHAR (MAX) NULL,
    [Keywords]         NVARCHAR (MAX) NULL,
    [IsActive]         BIT            CONSTRAINT [DF__TblCity__IsActiv__106D1478] DEFAULT ((0)) NULL,
    [GoogleAnalytics]  NVARCHAR (MAX) NULL,
    [IsTrendingCity]   BIT            CONSTRAINT [DF__TblCity__IsTrend__1DC70F96] DEFAULT ((0)) NULL,
    [Inclusive]        BIT            CONSTRAINT [DF__TblCity__Inclusi__1EBB33CF] DEFAULT ((0)) NULL,
    [CurrentTimeStamp] DATETIME       NULL,
    [U_id]             INT            NULL,
    [Currency]         NVARCHAR (MAX) NULL,
    [Timezone]         NVARCHAR (MAX) NULL,
    [Temperature]      NVARCHAR (100) NULL,
    [Precipitaion]     NVARCHAR (MAX) NULL,
    [Description]      NVARCHAR (MAX) NULL,
    [LastModifiedDate] DATETIME       CONSTRAINT [DF_TblCity_LastModifiedDate] DEFAULT (NULL) NULL,
    [ModifiedBy]       INT            NULL,
    [AltTag]           NVARCHAR (MAX) NULL,
    [DisplayOrder]     INT            NULL,
    CONSTRAINT [PK__TblCity__3214EC27BE327A1D] PRIMARY KEY CLUSTERED ([ID] ASC)
);

