CREATE TABLE [dbo].[tblInsPassengerDetails] (
    [pkid]                           INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [fkInsBookmaster]                BIGINT          NOT NULL,
    [orderID]                        VARCHAR (50)    NULL,
    [paxTitle]                       VARCHAR (10)    NULL,
    [paxFname]                       VARCHAR (50)    NULL,
    [paxMname]                       VARCHAR (50)    NULL,
    [paxLname]                       VARCHAR (50)    NULL,
    [paxDOB]                         VARCHAR (50)    NULL,
    [policyNumber]                   VARCHAR (50)    NULL,
    [orderNumber]                    VARCHAR (50)    NULL,
    [policyUniqueId]                 VARCHAR (50)    NULL,
    [individualPolicyFulfillmentUrl] NVARCHAR (MAX)  NULL,
    [PaxStatus]                      INT             NULL,
    [individualTripCost]             DECIMAL (18, 2) NULL,
    [totalFare]                      DECIMAL (18, 2) NULL,
    [age]                            INT             NULL,
    [BookingStatus]                  INT             NULL,
    [ManagementMarkupAmt]            DECIMAL (18, 2) NULL,
    [insertedDate]                   DATETIME        NULL,
    [insertedBy]                     VARCHAR (50)    NULL,
    [ERPResponseID]                  VARCHAR (200)   NULL,
    [ERPPuststatus]                  BIT             DEFAULT ((0)) NULL,
    [CanERPResponseID]               VARCHAR (100)   NULL,
    [CanERPPushStatus]               BIT             DEFAULT ((0)) NOT NULL,
    [basePremium]                    DECIMAL (18, 2) NULL,
    [serviceTax]                     DECIMAL (18, 2) NULL,
    [Discount]                       DECIMAL (18, 2) NULL,
    [Servicefee]                     DECIMAL (18, 2) NULL,
    [GST]                            DECIMAL (18, 2) NULL,
    [paxType]                        VARCHAR (10)    NULL,
    [airportType]                    VARCHAR (1)     NULL,
    [PassportNo]                     VARCHAR (50)    NULL,
    CONSTRAINT [PK__tblInsPa__40A64C0B8C2E411E] PRIMARY KEY CLUSTERED ([pkid] ASC)
);

