CREATE TABLE [dbo].[tblICust] (
    [PKID]                          INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ICust]                         NVARCHAR (255)  NULL,
    [Code]                          NVARCHAR (255)  NULL,
    [Name]                          NVARCHAR (255)  NULL,
    [DivisionCode]                  NVARCHAR (255)  NULL,
    [City]                          NVARCHAR (255)  NULL,
    [E-Mail]                        NVARCHAR (255)  NULL,
    [CustomerPostingGroup]          NVARCHAR (255)  NULL,
    [CustomerType]                  NVARCHAR (255)  NULL,
    [PANNo]                         NVARCHAR (255)  NULL,
    [NameAsOnPANCard]               NVARCHAR (255)  NULL,
    [AgentID]                       NVARCHAR (255)  NULL,
    [SurchargeGroup]                NVARCHAR (255)  NULL,
    [TopUp]                         VARCHAR (50)    NULL,
    [BTACustomer]                   VARCHAR (50)    NULL,
    [SupplierCode]                  NVARCHAR (255)  NULL,
    [Blocked]                       VARCHAR (255)   NULL,
    [State (Place of Supply)]       NVARCHAR (50)   NULL,
    [LocationCode]                  NVARCHAR (255)  NULL,
    [BranchCode]                    NVARCHAR (255)  NULL,
    [SalesPersonCode]               VARCHAR (255)   NULL,
    [OldCustomerNo]                 NVARCHAR (255)  NULL,
    [GSTRegistrationNo]             NVARCHAR (255)  NULL,
    [GSTCustomerType]               NVARCHAR (255)  NULL,
    [IATACode]                      NVARCHAR (255)  NULL,
    [Incl. Ser/Mgt Fee]             VARCHAR (50)    NULL,
    [InvoicingMethod]               NVARCHAR (255)  NULL,
    [[GSTEffectivDate]              DATETIME        NULL,
    [CommisionPost]                 NVARCHAR (50)   NULL,
    [ActualLocationRC]              NVARCHAR (255)  NULL,
    [AccountHandlingPerson]         NVARCHAR (255)  NULL,
    [CurrencyCode]                  NVARCHAR (255)  NULL,
    [SEZ]                           VARCHAR (50)    NULL,
    [SEZwithGST]                    VARCHAR (50)    NULL,
    [Balance]                       DECIMAL (38, 2) NULL,
    [Balance(LCY)]                  DECIMAL (38, 2) NULL,
    [Open Credits Amount (LCY)]     DECIMAL (38, 2) NULL,
    [Open CXL Credits Amount (LCY)] DECIMAL (38, 2) NULL,
    [AutoBilling]                   VARCHAR (50)    NULL,
    [DateofJoining]                 VARCHAR (255)   NULL,
    [<Credit Limit (LCY)>]          DECIMAL (38, 2) NULL,
    [AutoInvoiceForRC]              VARCHAR (50)    NULL,
    [Federal Virtual Acc No./ IFSC] NVARCHAR (255)  NULL,
    [AIExpAgentId]                  NVARCHAR (255)  NULL,
    [<Remaining Credit Limit>]      DECIMAL (38, 2) NULL,
    [Address2]                      NVARCHAR (500)  NULL,
    [Contact]                       NVARCHAR (255)  NULL,
    [Country/Region Code]           NVARCHAR (50)   NULL,
    [Address]                       NVARCHAR (MAX)  NULL,
    [FaxNo]                         NVARCHAR (255)  NULL,
    [PhoneNo]                       NVARCHAR (255)  NULL,
    [PostCode]                      INT             NULL,
    [IsDone]                        INT             NULL,
    CONSTRAINT [PK_tblICust_] PRIMARY KEY CLUSTERED ([PKID] ASC)
);

