CREATE TABLE [dbo].[tblInsBookMaster] (
    [pkid]                            INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [planName]                        VARCHAR (50)    NULL,
    [orderID]                         VARCHAR (50)    NOT NULL,
    [planId]                          VARCHAR (50)    NULL,
    [RiyaPNR]                         VARCHAR (50)    NULL,
    [totalfare]                       DECIMAL (18, 2) NULL,
    [optionalCoveragesTotal]          VARCHAR (50)    NULL,
    [token]                           NVARCHAR (MAX)  NULL,
    [address1]                        VARCHAR (250)   NULL,
    [address2]                        VARCHAR (250)   NULL,
    [postalCode]                      VARCHAR (50)    NULL,
    [cityName]                        VARCHAR (50)    NULL,
    [cityCode]                        VARCHAR (50)    NULL,
    [stateName]                       VARCHAR (50)    NULL,
    [stateCode]                       VARCHAR (50)    NULL,
    [countryName]                     VARCHAR (50)    NULL,
    [countryCode]                     VARCHAR (50)    NULL,
    [phoneNumber]                     VARCHAR (50)    NULL,
    [emailAddress]                    VARCHAR (150)   NULL,
    [contactType]                     VARCHAR (50)    NULL,
    [effectiveDate]                   DATETIME        NULL,
    [expirationDate]                  DATETIME        NULL,
    [depositDate]                     DATETIME        NULL,
    [totalTripCost]                   DECIMAL (18, 2) NULL,
    [insertedDate]                    DATETIME        NULL,
    [BookedBy]                        INT             NULL,
    [CancelledDate]                   DATETIME        NULL,
    [Cancelledby]                     INT             NULL,
    [CancellationCharge]              DECIMAL (18, 2) NULL,
    [IPaddress]                       VARCHAR (50)    NULL,
    [Bookingstatus]                   INT             NOT NULL,
    [userID]                          INT             NULL,
    [AgentROE]                        DECIMAL (18, 2) NULL,
    [ROE]                             DECIMAL (18, 2) NULL,
    [AgentID]                         VARCHAR (50)    NULL,
    [AgentMarkup]                     DECIMAL (18, 2) NULL,
    [NoofDays]                        INT             NULL,
    [Noofpax]                         INT             NULL,
    [Remarks]                         NVARCHAR (MAX)  NULL,
    [orderNumber]                     VARCHAR (50)    NULL,
    [orderUniqueId]                   NVARCHAR (MAX)  NULL,
    [orderConfirmationFulfillmentUrl] NVARCHAR (MAX)  NULL,
    [invoiceNumber]                   VARCHAR (50)    NULL,
    [invoiceDate]                     VARCHAR (50)    NULL,
    [ManagementFees]                  DECIMAL (18, 2) NULL,
    [ManagementMarkupFlat]            DECIMAL (18, 2) NULL,
    [ManagementMarkupPerc]            DECIMAL (18, 2) NULL,
    [ManagementMarkupBookingType]     INT             NULL,
    [MainAgentID]                     INT             NULL,
    [VendorName]                      VARCHAR (25)    NULL,
    [AgentCurrency]                   VARCHAR (30)    NULL,
    [VendorCurrency]                  VARCHAR (30)    NULL,
    [VendorLoginID]                   VARCHAR (50)    NULL,
    [IssueBy]                         VARCHAR (50)    NULL,
    [updatedDate]                     DATETIME        NULL,
    [planType]                        VARCHAR (50)    NULL,
    [airportType]                     VARCHAR (1)     NULL,
    [GeographicalCover]               VARCHAR (70)    NULL,
    [DiscountFlatValue]               VARCHAR (70)    NULL,
    [DiscountPercentageValue]         DECIMAL (18, 2) NULL,
    [TotalDiscount]                   DECIMAL (18, 2) NULL,
    [TotalServicefee]                 VARCHAR (10)    NULL,
    [GST]                             DECIMAL (18, 2) NULL,
    [basePremium]                     DECIMAL (18, 2) NULL,
    [serviceTax]                      DECIMAL (18, 2) NULL,
    [PassportFileNo]                  VARCHAR (50)    NULL,
    [VendorBookingError]              VARCHAR (MAX)   NULL,
    CONSTRAINT [PK__tblInsBo__40A64C0BEBF03674] PRIMARY KEY CLUSTERED ([pkid] ASC)
);

