CREATE TABLE [dbo].[tblPassengerBookDetailsHistory] (
    [pid]                        BIGINT          NOT NULL,
    [fkBookMaster]               BIGINT          NULL,
    [paxType]                    VARCHAR (50)    NULL,
    [paxFName]                   VARCHAR (50)    NULL,
    [paxLName]                   VARCHAR (50)    NULL,
    [passportNum]                VARCHAR (30)    NULL,
    [passportIssueCountry]       VARCHAR (100)   NULL,
    [passexp]                    DATE            NULL,
    [inserteddate]               DATETIME        CONSTRAINT [DF_tblPassengerBookDetailsHistory_inserteddate] DEFAULT (getdate()) NULL,
    [status]                     BIT             CONSTRAINT [DF_tblPassegnerMasterHistory_status] DEFAULT ((0)) NULL,
    [title]                      VARCHAR (10)    NULL,
    [dateOfBirth]                DATETIME        NULL,
    [nationality]                VARCHAR (50)    CONSTRAINT [DF_tblPassengerBookDetailsHistory_nationality] DEFAULT ('India') NULL,
    [gender]                     VARCHAR (20)    NULL,
    [ticketNum]                  VARCHAR (200)   NULL,
    [Isrescheduled]              BIT             NULL,
    [Iscancelled]                BIT             CONSTRAINT [DF_tblPassengerBookDetailsHistory_Iscancelled] DEFAULT ((0)) NULL,
    [YQ]                         VARCHAR (50)    NULL,
    [TDSamount]                  INT             NULL,
    [serviceCharge]              INT             NULL,
    [managementfees]             INT             NULL,
    [airlineCancellationPanelty] VARCHAR (500)   NULL,
    [riyaCancellationCharges]    INT             NULL,
    [RemainingRefund]            INT             NULL,
    [RefundAmount]               INT             NULL,
    [IsRefunded]                 BIT             CONSTRAINT [DF_tblPassengerBookDetailsHistory_IsRefunded] DEFAULT ((0)) NULL,
    [RefundedDate]               DATETIME        NULL,
    [reScheduleCharge]           INT             NULL,
    [airPNR]                     VARCHAR (50)    NULL,
    [cancellationRemark]         VARCHAR (500)   NULL,
    [fflyer]                     VARCHAR (100)   NULL,
    [baggage]                    VARCHAR (100)   NULL,
    [totalFare]                  INT             NULL,
    [basicFare]                  INT             NULL,
    [totalTax]                   INT             NULL,
    [isReturn]                   BIT             CONSTRAINT [DF_tblPassengerBookDetailsHistory_isReturnJourney] DEFAULT ((0)) NULL,
    [Discount]                   INT             NULL,
    [FlatDiscount]               INT             NULL,
    [GovtTax]                    INT             NULL,
    [CancellationCharge]         INT             NULL,
    [Panelty]                    DECIMAL (18)    NULL,
    [YRTax]                      DECIMAL (18, 2) NULL,
    [INTax]                      DECIMAL (18, 2) NULL,
    [JNTax]                      DECIMAL (18, 2) NULL,
    [OCTax]                      DECIMAL (18, 2) NULL,
    [ExtraTax]                   DECIMAL (18, 2) NULL,
    [DiscriptionTax]             VARCHAR (1000)  NULL,
    [isProcessRefund]            BIT             CONSTRAINT [DF_tblPassengerBookDetailsHistory_isProcessRefund] DEFAULT ((0)) NULL,
    [CancelledDate]              DATETIME        NULL,
    [CommissionType]             INT             NULL,
    [ServiceChargeType]          INT             NULL,
    [FlatDiscountType]           INT             NULL,
    [CancellationChargeType]     INT             NULL,
    [IATACommission]             INT             NULL,
    [PLBCommission]              INT             NULL,
    [GovtTaxPercent]             DECIMAL (18, 2) NULL,
    [IATAPercent]                DECIMAL (18, 2) NULL,
    [PLBPercent]                 DECIMAL (18, 2) NULL,
    [IsIATAOnBasic]              BIT             NULL,
    [IsPLBOnBasic]               BIT             NULL,
    [CancelClosed]               BIT             CONSTRAINT [DF_tblPassengerBookDetailsHistory_CancelClosed] DEFAULT ((0)) NULL,
    [Markup]                     DECIMAL (18, 2) CONSTRAINT [DF_tblPassengerBookDetailsHistory_Markup] DEFAULT ((0)) NULL,
    [ERPkey]                     NVARCHAR (50)   NULL,
    [FailedFlag]                 INT             NULL,
    [PassIssue]                  DATE            NULL,
    CONSTRAINT [PK_tblPassengerBookDetailsHistory] PRIMARY KEY CLUSTERED ([pid] ASC)
);

