CREATE TABLE [dbo].[tblReissueUploaderDetails] (
    [ID]                            BIGINT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [TopUpCr]                       NVARCHAR (255)  NULL,
    [Issue Date]                    NVARCHAR (255)  NULL,
    [Customer No]                   NVARCHAR (255)  NULL,
    [Ship-to Customer No]           NVARCHAR (255)  NULL,
    [Customer Location Code]        NVARCHAR (255)  NULL,
    [Booking No]                    NVARCHAR (255)  NULL,
    [Ticket Type]                   NVARCHAR (255)  NULL,
    [Agent ID]                      NVARCHAR (255)  NULL,
    [PNR No]                        NVARCHAR (255)  NULL,
    [Airline Code]                  NVARCHAR (255)  NULL,
    [Vendor No]                     NVARCHAR (255)  NULL,
    [Pay-to Vendor No]              NVARCHAR (255)  NULL,
    [Ticket No]                     NVARCHAR (MAX)  NULL,
    [Pax Type]                      NVARCHAR (255)  NULL,
    [First Name]                    NVARCHAR (255)  NULL,
    [Last Name]                     NVARCHAR (255)  NULL,
    [Currency Code]                 NVARCHAR (255)  NULL,
    [Basic Fare]                    DECIMAL (18, 2) NULL,
    [Tax YR]                        DECIMAL (18, 2) NULL,
    [Tax YQ]                        DECIMAL (18, 2) NULL,
    [Tax IN]                        DECIMAL (18, 2) NULL,
    [Tax K3]                        DECIMAL (18, 2) NULL,
    [Tax AF]                        DECIMAL (18, 2) NULL,
    [Tax P2]                        DECIMAL (18, 2) NULL,
    [Tax WO]                        DECIMAL (18, 2) NULL,
    [GB Tax]                        DECIMAL (18, 2) NULL,
    [CP Tax]                        DECIMAL (18, 2) NULL,
    [UB Tax]                        DECIMAL (18, 2) NULL,
    [CMF Tax]                       DECIMAL (18, 2) NULL,
    [COMM Tax]                      DECIMAL (18, 2) NULL,
    [COMMBF Tax]                    DECIMAL (18, 2) NULL,
    [RCS Tax]                       DECIMAL (18, 2) NULL,
    [RCF Tax]                       DECIMAL (18, 2) NULL,
    [RF Tax]                        DECIMAL (18, 2) NULL,
    [Tax XT]                        DECIMAL (18, 2) NULL,
    [Tax Total]                     DECIMAL (18, 2) NULL,
    [Tax Q]                         DECIMAL (18, 2) NULL,
    [Total Fare]                    DECIMAL (18, 2) NULL,
    [Cust IATA Comm Amount]         DECIMAL (18, 2) NULL,
    [Cust Add Comm Amount]          DECIMAL (18, 2) NULL,
    [Cust PLB Amount]               DECIMAL (18, 2) NULL,
    [Cust Flown Commission]         DECIMAL (18, 2) NULL,
    [Cust Boarding Commission]      DECIMAL (18, 2) NULL,
    [Vend IATA Comm Amount]         DECIMAL (18, 2) NULL,
    [Vend Add Comm Amount]          DECIMAL (18, 2) NULL,
    [Vend PLB Amount]               DECIMAL (18, 2) NULL,
    [Vend Flown Commission]         DECIMAL (18, 2) NULL,
    [Vend Boarding Commission]      DECIMAL (18, 2) NULL,
    [Net Fare]                      DECIMAL (18, 2) NULL,
    [FOP]                           NVARCHAR (255)  NULL,
    [Markup Base]                   DECIMAL (18, 2) NULL,
    [Markup Tax]                    DECIMAL (18, 2) NULL,
    [Service Charge]                DECIMAL (18, 2) NULL,
    [Vendor Ser Fee]                DECIMAL (18, 2) NULL,
    [Management Fee]                DECIMAL (18, 2) NULL,
    [Issue In Exchange]             NVARCHAR (255)  NULL,
    [Tour Code/Deal Code]           NVARCHAR (255)  NULL,
    [Purchase Currency]             NVARCHAR (255)  NULL,
    [EQ Fare]                       DECIMAL (18, 2) NULL,
    [Fare Basis]                    DECIMAL (18, 2) NULL,
    [FC String]                     NVARCHAR (255)  NULL,
    [Sector Name]                   NVARCHAR (255)  NULL,
    [Flight No]                     NVARCHAR (255)  NULL,
    [Class]                         NVARCHAR (MAX)  NULL,
    [Date Of Travel]                NVARCHAR (MAX)  NULL,
    [BookingIdentification]         NVARCHAR (255)  NULL,
    [FromCity]                      NVARCHAR (255)  NULL,
    [ToCity]                        NVARCHAR (255)  NULL,
    [Penalty Amount]                DECIMAL (18, 2) NULL,
    [Markup On Cancellation]        DECIMAL (18, 2) NULL,
    [Service Fee On Cancellation]   DECIMAL (18, 2) NULL,
    [Mgmt Fee On Cancellation]      DECIMAL (18, 2) NULL,
    [No Show Charge]                NVARCHAR (255)  NULL,
    [No Show Airline]               NVARCHAR (255)  NULL,
    [AdditionalCxlBase]             DECIMAL (18, 2) NULL,
    [AdditionalCxlTax]              DECIMAL (18, 2) NULL,
    [VMPD/Exo No]                   NVARCHAR (255)  NULL,
    [Employee Dimension Code]       NVARCHAR (255)  NULL,
    [TR/PO No]                      NVARCHAR (255)  NULL,
    [CardType]                      NVARCHAR (255)  NULL,
    [IATA Code]                     NVARCHAR (255)  NULL,
    [Cancellation Type]             NVARCHAR (255)  NULL,
    [Booking Source Type]           NVARCHAR (255)  NULL,
    [BTA Sales]                     NVARCHAR (255)  NULL,
    [Vessel Name]                   NVARCHAR (255)  NULL,
    [Narration 1]                   NVARCHAR (255)  NULL,
    [Narration 2]                   NVARCHAR (255)  NULL,
    [EMD/SSR Ticket Type]           NVARCHAR (255)  NULL,
    [Cust Info1]                    NVARCHAR (255)  NULL,
    [Cust Info2]                    NVARCHAR (255)  NULL,
    [Cust Info3]                    NVARCHAR (255)  NULL,
    [Cust Info4]                    NVARCHAR (255)  NULL,
    [Cust Info5]                    NVARCHAR (255)  NULL,
    [Approved By]                   NVARCHAR (255)  NULL,
    [Travel End Date]               NVARCHAR (255)  NULL,
    [Promotion Code]                NVARCHAR (255)  NULL,
    [MO Document No]                NVARCHAR (255)  NULL,
    [Extra Baggage Amount]          DECIMAL (18, 2) NULL,
    [Seat Pref Charges]             DECIMAL (18, 2) NULL,
    [Meal Charges]                  DECIMAL (18, 2) NULL,
    [Wheel Chair Charges]           DECIMAL (18, 2) NULL,
    [SSR Comb Amount]               DECIMAL (18, 2) NULL,
    [PG Charges]                    DECIMAL (18, 2) NULL,
    [Surcharge Amount]              DECIMAL (18, 2) NULL,
    [Vendor Markup]                 DECIMAL (18, 2) NULL,
    [Vendor Markup on Cancellation] DECIMAL (18, 2) NULL,
    [Global Dimension 2 Code]       NVARCHAR (255)  NULL,
    [Cust Info6]                    NVARCHAR (255)  NULL,
    [Cust Info7]                    NVARCHAR (255)  NULL,
    [Cust Info8]                    NVARCHAR (255)  NULL,
    [Sales Exchange Rate]           DECIMAL (18, 2) NULL,
    [Purch Exchange Rate]           DECIMAL (18, 2) NULL,
    [Purchase Currency1]            NVARCHAR (255)  NULL,
    [Created Date]                  NVARCHAR (255)  CONSTRAINT [DF__tblReissu__Creat__1B8A8CC0] DEFAULT (getdate()) NULL,
    [Created By]                    NVARCHAR (255)  NULL,
    CONSTRAINT [PK__tblReiss__3214EC276AF856E6] PRIMARY KEY CLUSTERED ([ID] ASC)
);

