CREATE TABLE [dbo].[Temptable_1] (
    [Document Type]              NUMERIC (18)  NULL,
    [Document No_]               VARCHAR (20)  NOT NULL,
    [Air Line No_]               INT           NULL,
    [Line No_]                   INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [PNR No_]                    VARCHAR (10)  NULL,
    [Airline PNR No_]            VARCHAR (10)  NULL,
    [From City]                  VARCHAR (10)  NULL,
    [To City]                    VARCHAR (10)  NULL,
    [Departure Date]             VARCHAR (20)  NULL,
    [Departure Time]             VARCHAR (20)  NULL,
    [Arrival Date]               VARCHAR (20)  NULL,
    [Arrival Time]               VARCHAR (20)  NULL,
    [Flight No_]                 VARCHAR (10)  NULL,
    [Terminal No_]               VARCHAR (10)  NULL,
    [Class]                      VARCHAR (10)  NULL,
    [Airline Code]               VARCHAR (10)  NULL,
    [Cabin]                      INT           NULL,
    [Aircraft Type]              VARCHAR (10)  NULL,
    [Booking Status]             VARCHAR (10)  NULL,
    [Adult Baggage]              VARCHAR (30)  NULL,
    [Child Baggage]              VARCHAR (30)  NULL,
    [Infant Baggage]             VARCHAR (30)  NULL,
    [No_ of Stops]               INT           NULL,
    [Adult Fare Basis Code]      VARCHAR (20)  NULL,
    [Child Fare Basis Code]      VARCHAR (20)  NULL,
    [Infant Fare Basis Code]     VARCHAR (20)  NULL,
    [CRS Code]                   VARCHAR (10)  NULL,
    [International]              TINYINT       NULL,
    [Non-Integrated Filght No_]  VARCHAR (250) NULL,
    [Non-Integrated Travel Date] VARCHAR (250) NULL,
    [Non-Integrated Class]       VARCHAR (100) NULL,
    [Itinerary Id]               VARCHAR (100) NULL,
    [US Sector]                  TINYINT       NULL,
    [Company ID]                 INT           NULL
);

