CREATE TABLE [dbo].[TRVLNXT_Tickets_ERPStatus] (
    [ID]                   BIGINT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [UserTypeID]           INT             NULL,
    [Country]              VARCHAR (50)    NULL,
    [TransactionType]      VARCHAR (50)    NULL,
    [CancellationPenalty]  DECIMAL (18, 2) NULL,
    [CancellationCharges]  DECIMAL (18, 2) NULL,
    [AgentID]              VARCHAR (50)    NULL,
    [ERPPuststatus]        BIT             CONSTRAINT [DF_TRVLNXT_Tickets_ERP_ERPPuststatus] DEFAULT ((0)) NULL,
    [ERPResponseID]        VARCHAR (200)   NULL,
    [SetID]                VARCHAR (200)   NULL,
    [MasterInvoiceNo]      VARCHAR (100)   NULL,
    [ERPExceptions]        VARCHAR (MAX)   NULL,
    [MoDocumentNo]         BIGINT          NULL,
    [RiyaPNR]              VARCHAR (20)    NULL,
    [TicketNumber]         VARCHAR (50)    NULL,
    [AirLineCode]          VARCHAR (10)    NULL,
    [AirLineNumber]        VARCHAR (50)    NULL,
    [OldTicketNumber]      VARCHAR (50)    NULL,
    [OfficeID]             VARCHAR (50)    NULL,
    [PostingDate]          DATETIME        NULL,
    [BookingDate]          DATETIME        NULL,
    [TravelStartDate]      DATETIME        NULL,
    [TravelEndDate]        DATETIME        NULL,
    [ProductType]          VARCHAR (20)    NULL,
    [CustomerNumber]       VARCHAR (50)    NULL,
    [PayToVendor]          VARCHAR (50)    NULL,
    [BTASales]             VARCHAR (20)    NULL,
    [GDSPNR]               VARCHAR (50)    NULL,
    [AirlinePNR]           VARCHAR (50)    NULL,
    [PaxType]              VARCHAR (50)    NULL,
    [Salutation]           VARCHAR (10)    NULL,
    [PaxName]              VARCHAR (100)   NULL,
    [EmployeeCode]         VARCHAR (50)    NULL,
    [SalesCurrencyCode]    VARCHAR (50)    NULL,
    [SalesCurrencyFactor]  VARCHAR (50)    NULL,
    [SalesExchangeRate]    VARCHAR (50)    NULL,
    [BaseAmount]           DECIMAL (18, 2) NULL,
    [TaxAmount]            DECIMAL (18, 2) NULL,
    [TotalAmount]          DECIMAL (18, 2) NULL,
    [PromoDiscountAmount]  DECIMAL (18, 2) NULL,
    [ServiceFee]           DECIMAL (18, 2) NULL,
    [ManagementFee]        DECIMAL (18, 2) NULL,
    [SurchargeAmount]      DECIMAL (18, 2) NULL,
    [VendCommAmount]       DECIMAL (18, 2) NULL,
    [DateChangePenalty]    DECIMAL (18, 2) NULL,
    [CustIATACommAmount]   DECIMAL (18, 2) NULL,
    [CustPLBAmount]        DECIMAL (18, 2) NULL,
    [VendIATACommAmount]   DECIMAL (18, 2) NULL,
    [QTax]                 DECIMAL (18, 2) NULL,
    [MCO]                  VARCHAR (50)    NULL,
    [UATP_MCOSales]        BIT             CONSTRAINT [DF_TRVLNXT_Tickets_ERP_UATP_MCOSales] DEFAULT ((0)) NULL,
    [MarkupOnBaseFare]     DECIMAL (18, 2) NULL,
    [MarkupOnTaxFare]      DECIMAL (18, 2) NULL,
    [MarkupOnCancellation] DECIMAL (18, 2) NULL,
    [UATP]                 VARCHAR (20)    NULL,
    [CardType]             VARCHAR (20)    NULL,
    [CardNumber]           VARCHAR (50)    NULL,
    [OBTaxAmount]          DECIMAL (18, 2) NULL,
    [OCTaxAmount]          DECIMAL (18, 2) NULL,
    [YQTaxAmount]          DECIMAL (18, 2) NULL,
    [YRTaxAmount]          DECIMAL (18, 2) NULL,
    [K3TaxAmount]          DECIMAL (18, 2) NULL,
    [XTTaxAmount]          DECIMAL (18, 2) NULL,
    [INTaxAmount]          DECIMAL (18, 2) NULL,
    [YMTaxAmount]          DECIMAL (18, 2) NULL,
    [WOTaxAmount]          DECIMAL (18, 2) NULL,
    [PHFTaxAmount]         DECIMAL (18, 2) NULL,
    [TTFTaxAmount]         DECIMAL (18, 2) NULL,
    [TRFTaxAmount]         DECIMAL (18, 2) NULL,
    [CMFTaxAmount]         DECIMAL (18, 2) NULL,
    [COMMTaxAmount]        DECIMAL (18, 2) NULL,
    [COMMBFTaxAmount]      DECIMAL (18, 2) NULL,
    [RCSTaxAmount]         DECIMAL (18, 2) NULL,
    [RCFTaxAmount]         DECIMAL (18, 2) NULL,
    [RFTaxAmount]          DECIMAL (18, 2) NULL,
    [ExtraBaggageAmount]   DECIMAL (18, 2) NULL,
    [PaymentMode]          VARCHAR (50)    NULL,
    [TicketingUserID]      VARCHAR (50)    NULL,
    [Narration]            VARCHAR (200)   NULL,
    [PromotionCode]        VARCHAR (50)    NULL,
    [IATACode]             VARCHAR (50)    NULL,
    [BookingUserID]        VARCHAR (50)    NULL,
    [OrderID]              VARCHAR (50)    NULL,
    [ProductCode]          VARCHAR (50)    NULL,
    [DealCode]             VARCHAR (50)    NULL,
    [CrsCode]              VARCHAR (50)    NULL,
    [CreatedDate]          DATETIME        CONSTRAINT [DF_TRVLNXT_Tickets_ERP_CreatedDate] DEFAULT (getdate()) NULL,
    [ERPPushDate]          DATETIME        NULL,
    [ERPPushCounter]       INT             NULL,
    [RequestXML]           VARCHAR (MAX)   NULL,
    [ResponseXML]          VARCHAR (MAX)   NULL,
    [dummy1]               VARCHAR (50)    NULL,
    [dummy2]               VARCHAR (50)    NULL,
    [dummy3]               VARCHAR (200)   NULL,
    [dummy4]               VARCHAR (250)   NULL,
    [dummy5]               VARCHAR (MAX)   NULL,
    [BMPkId]               INT             NULL,
    [EDVendorCode]         VARCHAR (50)    NULL,
    [CounterCloseTime]     INT             NULL,
    [TravelStartTime]      DATETIME        NULL,
    [TravelEndTime]        DATETIME        NULL,
    [FromCity]             VARCHAR (50)    NULL,
    [ToCity]               VARCHAR (50)    NULL,
    [FlightNo]             VARCHAR (50)    NULL,
    [BMtravClass]          VARCHAR (50)    NULL,
    [BMfromTerminal]       VARCHAR (50)    NULL,
    [BMtoTerminal]         VARCHAR (50)    NULL,
    [BMEquipment]          VARCHAR (50)    NULL,
    [PurchCurr]            VARCHAR (50)    NULL,
    [PurchCurrROE]         VARCHAR (50)    NULL,
    [PBPId]                INT             NULL,
    [AirLineType]          VARCHAR (50)    NULL,
    [BMTotalDiscount]      DECIMAL (18, 2) NULL,
    [PREmpCode]            VARCHAR (50)    NULL,
    [BIfarebasis]          VARCHAR (50)    NULL,
    [BookingStatus]        INT             NULL,
    [IsBooked]             BIT             DEFAULT ((0)) NOT NULL,
    [BMRegistrationNumber] VARCHAR (100)   NULL,
    [BMVendor_No]          VARCHAR (50)    NULL,
    [PBB2bMarkup]          DECIMAL (18, 2) DEFAULT ((0.00)) NOT NULL,
    [PBBFC]                INT             NULL,
    [PBBaggage]            VARCHAR (50)    NULL,
    [PM_Mer_Amount]        DECIMAL (18, 2) DEFAULT ((0.00)) NOT NULL,
    [PM_Billing_Address]   VARCHAR (200)   NULL,
    [PM_Billing_Name]      VARCHAR (200)   NULL,
    [PM_Tracking_id]       VARCHAR (200)   NULL,
    [BICabin]              VARCHAR (100)   NULL,
    [ATT_VesselName]       VARCHAR (100)   NULL,
    [ATT_TR_POName]        VARCHAR (100)   NULL,
    [ATT_Bookedby]         VARCHAR (100)   NULL,
    [ATT_AType]            VARCHAR (100)   NULL,
    [ATT_RankNo]           VARCHAR (100)   NULL,
    [BMAgentMarkup]        DECIMAL (18, 2) DEFAULT ((0.00)) NULL,
    [PBRFTax]              DECIMAL (18, 2) DEFAULT ((0.00)) NULL,
    [airCode]              VARCHAR (50)    NULL,
    [BMVendorName]         VARCHAR (50)    NULL,
    [B2bFareType]          INT             DEFAULT ((0)) NULL,
    [BMB2bFareType]        INT             DEFAULT ((0)) NULL,
    [PBMarkup]             DECIMAL (18, 2) DEFAULT ((0.00)) NULL,
    [CancERPResponseID]    VARCHAR (MAX)   NULL,
    [CancERPPuststatus]    INT             DEFAULT ((0)) NULL,
    [MainAgentId]          INT             DEFAULT ((0)) NULL,
    [PBBaggageFare]        DECIMAL (18, 2) NULL,
    [MCOAmount]            DECIMAL (18, 2) NULL,
    [MCOTicketNo]          VARCHAR (50)    NULL,
    [McoCommissionAmount]  DECIMAL (18, 2) NULL,
    [ERPMcoResponseID]     VARCHAR (MAX)   NULL,
    [ERPMcoPushStatus]     INT             NULL,
    [LocationCode]         VARCHAR (50)    NULL,
    [BranchCode]           VARCHAR (50)    NULL,
    [DivisionCode]         VARCHAR (50)    NULL,
    [ATTOBTCno]            VARCHAR (50)    NULL,
    [FormOfPayment]        VARCHAR (50)    NULL,
    [Meal_Charges]         DECIMAL (18, 2) DEFAULT ((0.00)) NULL,
    [AMStatus]             VARCHAR (50)    NULL,
    [Traveltype]           VARCHAR (50)    NULL,
    [FareType]             VARCHAR (50)    NULL,
    CONSTRAINT [PK_TRVLNXT_Tickets_ERP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

