CREATE TABLE [dbo].[UserLogin] (
    [UserID]             BIGINT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [UserCode]           VARCHAR (10)  NULL,
    [UserName]           VARCHAR (500) NOT NULL,
    [Password]           VARCHAR (300) NULL,
    [FirstName]          VARCHAR (150) NULL,
    [LastName]           VARCHAR (150) NULL,
    [InsertedDate]       DATETIME      CONSTRAINT [DF_UserLogin_InsertedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]           TINYINT       NULL,
    [MobileNumber]       VARCHAR (20)  NULL,
    [NewsLetter]         TINYINT       CONSTRAINT [DF_UserLogin_NewsLetter] DEFAULT ((1)) NULL,
    [Address]            VARCHAR (500) NULL,
    [City]               VARCHAR (100) NULL,
    [Country]            VARCHAR (100) NULL,
    [Pincode]            VARCHAR (10)  NULL,
    [DrivingLicenceNo]   VARCHAR (20)  NULL,
    [HomeNo]             VARCHAR (20)  NULL,
    [IsB2BAgent]         BIT           NULL,
    [Province]           VARCHAR (50)  NULL,
    [BookingCountry]     VARCHAR (2)   NULL,
    [AgentApproved]      BIT           NULL,
    [SessionID]          VARCHAR (50)  NULL,
    [AgentBalance]       MONEY         NULL,
    [Title]              VARCHAR (20)  NULL,
    [AlternateEmailID]   VARCHAR (50)  NULL,
    [Address1]           VARCHAR (50)  NULL,
    [DateOfBirth]        DATETIME      NULL,
    [PassportNumber]     VARCHAR (50)  NULL,
    [IssuingCountry]     VARCHAR (50)  NULL,
    [PassportExpiryDate] DATETIME      NULL,
    [NewsLetters1]       BIT           NULL,
    [NewsLetters2]       BIT           NULL,
    [MiddleName]         VARCHAR (150) NULL,
    [NickName]           VARCHAR (150) NULL,
    [IsSSOUser]          BIT           CONSTRAINT [DF_UserLogin_IsSSOUser] DEFAULT ((1)) NULL,
    [Branch]             VARCHAR (200) NULL,
    [Department]         VARCHAR (200) NULL,
    [SubDept]            VARCHAR (200) NULL,
    [Designation]        VARCHAR (200) NULL,
    [OfficialEmail]      VARCHAR (200) NULL,
    [OfficailMobile]     VARCHAR (200) NULL,
    [PersonalMobile]     VARCHAR (200) NULL,
    [PersonalEmail]      VARCHAR (200) NULL,
    [TokenNo]            VARCHAR (150) NULL,
    CONSTRAINT [PK_UserLogin] PRIMARY KEY CLUSTERED ([UserID] ASC)
);

