CREATE TABLE [Insurance].[tbl_Insurance_Markup_Comm] (
    [PKID]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [UserTypeId]         INT             NOT NULL,
    [MarketPoint]        CHAR (2)        NOT NULL,
    [AgentId]            VARCHAR (MAX)   NOT NULL,
    [ServicetypeId]      INT             NOT NULL,
    [SupplierId]         INT             NOT NULL,
    [PlanIds]            VARCHAR (500)   NULL,
    [TravelValidityFrom] DATETIME        NOT NULL,
    [TravelValidityTo]   DATETIME        NOT NULL,
    [SalesValidityFrom]  DATETIME        NOT NULL,
    [SalesValidityTo]    DATETIME        NOT NULL,
    [Origin]             VARCHAR (MAX)   NULL,
    [Destination]        VARCHAR (MAX)   NULL,
    [Currency]           VARCHAR (50)    NOT NULL,
    [BookingTypeIds]     VARCHAR (500)   NOT NULL,
    [GST]                DECIMAL (18, 2) NULL,
    [TDS]                DECIMAL (18, 2) NULL,
    [CommissionPer]      DECIMAL (18, 2) NULL,
    [MarkupFrom]         DECIMAL (18, 2) NULL,
    [MarkupTo]           DECIMAL (18, 2) NULL,
    [Markupamt]          DECIMAL (18, 2) NULL,
    [MarkupPercentage]   DECIMAL (18, 2) NULL,
    [InsertedOn]         DATETIME        CONSTRAINT [DF_Table_1_Inserteddatetime] DEFAULT (getdate()) NOT NULL,
    [InsertedBy]         INT             NOT NULL,
    [ModifiedOn]         DATETIME        NULL,
    [ModifiedBy]         INT             NULL,
    [Status]             BIT             CONSTRAINT [DF_tbl_Insurance_Markup_Comm_Status] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_tbl_Insurance_Markup_Comm] PRIMARY KEY CLUSTERED ([PKID] ASC)
);

