CREATE TABLE [Insurance].[tbl_Insurance_Discount2] (
    [Id]                        INT            IDENTITY (1, 1) NOT NULL,
    [MarketPoint]               VARCHAR (30)   NULL,
    [UserType]                  VARCHAR (30)   NULL,
    [ServiceType]               VARCHAR (50)   NULL,
    [AgencyName]                VARCHAR (1000) NULL,
    [AgentId]                   NVARCHAR (300) NULL,
    [SupplierType]              NVARCHAR (50)  NULL,
    [TravelValidityFrom]        DATETIME       NULL,
    [TravelValidityTo]          DATETIME       NULL,
    [SaleValidityFrom]          DATETIME       NULL,
    [SaleValidityTo]            DATETIME       NULL,
    [InsuranceType]             VARCHAR (100)  NULL,
    [ServiceFee]                VARCHAR (50)   NULL,
    [GST]                       VARCHAR (50)   NULL,
    [MarkupCalculationTyp]      VARCHAR (20)   NULL,
    [MarkupVal]                 VARCHAR (10)   NULL,
    [DiscountTyp]               VARCHAR (20)   NULL,
    [DiscountVal]               VARCHAR (10)   NULL,
    [Currency]                  VARCHAR (10)   NULL,
    [isActive]                  BIT            NULL,
    [CreatedDate]               DATETIME       NULL,
    [ModifiedDate]              DATETIME       NULL,
    [CreatedBy]                 NVARCHAR (50)  NULL,
    [ModifyBy]                  NVARCHAR (50)  NULL,
    [CommissionType]            VARCHAR (50)   NULL,
    [CalculationTypeCommission] VARCHAR (50)   NULL
);

