 -- [dbo].[Proc_GetRBTReport] 47208,1171,'2024-01-15','2024-01-15'        
CREATE PROCEDURE [dbo].[Proc_GetRBTReportbkp]        
@AgentId int = 0 ,                                  
@MainAgentId int = 0,                              
@FromDate varchar(100)='',                              
@ToDate varchar(100)=''              
AS         
BEGIN         
 IF @ToDate IN ('',NULL)         
  SET @ToDate = DATEADD(DAY,1,@FromDate)                                                                                      
 ELSE                         
  SET @ToDate = DATEADD(DAY,1,@ToDate)           
  ---- Voucher Condition--  
  select       
'Hotel' as ProductType,      
'' as TripID,      
MAG.GroupName as GroupName,      
B2B.AgencyName as CorporateName,      
'Corporate' as CorporateType,      
'' as CorporateID,      
HB.PassengerEmail as EmployeeEmailID,      
HB.PassengerPhone as EmployeeMobileNo,      
'' as EmployeeCode,      
'' as TravellerType,      
'' as BookingType,      
HB.LeaderTitle as Title,      
HB.LeaderFirstName as FirstName,      
HB.LeaderLastName as LastName,      
HM.status AS Status,        
'' as BookAppType,      
'' as StockType,      
HB.B2BPaymentMode as PaymentMode,      
'' as RequestedDate,      
'' as ApprovedDate,      
HH.CreateDate as BookedDate,      
'' as ApproveByOREApproverBookedBy,      
'' as BookedBy,      
HB.BookingCountry as CountryCode,      
'' as CountryName,      
--HB.cityName AS CityName,      
HB.HotelName as HotelName,      
ISNULL(HB.HotelAddress1,HB.HotelAddress2) AS AccommodationAddress,      
HB.HotelIncludes +''+HB.Meal AS Inclusion,        
HB.CheckInDate AS CheckInDate,        
HB.CheckOutDate AS CheckOutDate,      
HB.CheckInTime as CheckInTime,      
HB.CheckOutTime AS CheckOutTime,      
HB.SelectedNights AS RoomNight,      
CASE WHEN HB.BookingCountry='IN' THEN 'Domestic' Else 'International' END  AS TravelScope,      
HB.BookingReference AS RIYAPNR,      
ISNULL(HB.HotelConfNumber,'') as BookingRef,      
ISNULL(HB.providerConfirmationNumber,'') as GDSRef,      
'' as PassiveSegRef,      
'' AS RateType,      
HB.TotalRoomAmount as BaseFare,      
HB.HotelTaxes as TotalTax,      
0 as Markup,      
HB.AgentCommission as Discount,      
HB.agentCancellationCharges as Penalty,      
0 as CancellationMarkup,      
0 as Breakupoftaxes,      
bc.GSTAmount as GST,      
HB.AgentServiceFee as serviceFee,      
0 as GSTonSF,      
bc.TDSDeductedAmount as TDS,      
ISNULL(B2BMC.TotalCommission,0) as PGCharges,      
0 as GSTonPG,      
HB.agentCancellationCharges as CancelCharges,      
0 as RescheduleCharges,      
HB.STotalRate as NetAmount,      
hb.HotelTotalGross as GrossAmount,      
(cast(HB.DisplayDiscountRate as float) / cast(HB.SelectedNights as float)) as PerNightRate,      
'' as CappingLimit,      
'' as  SuggestedLowestRate,      
'' as L1Hotel,      
'' as L1Rate,      
'' as L2Hotel,      
'' as L2Rate,      
'' as L3Hotel,      
'' as L3Rate,      
0 as MissedSavings,      
hb.ROEValue as ROE,      
'' as ROECurrency,      
isnull(gst.GstNumber,'') as GSTNo,      
isnull(gst.Address,'') as GSTAddress,      
isnull(gst.EmailId,'') as GSTMailID,      
isnull(gst.MobileNo,'') as GSTPhoneNo,      
--case when HAT.AttributeId=4 Then HAT.AttributesValue Else '' END as CostCentre,   
''  as CostCentre,  
'' as DebitCostCenter,      
'' as ComplainceOrNonComplaince,      
'' as TravelPolicies,      
'' as ReferenceID,      
''  as CompanycodeOrNonBillable,      
'' as Durationoftravel,      
'' as EmployeeWorkingLocation,      
'' as Natureoftravel,      
'' as ProjectCode,      
'' as ReasonForNotSelectingLowestPreferredHotel,      
'' as RequestNo,      
'' as SAPCode,      
'' as LOCATIONCODE,      
'' as 'FUNCTION',      
'' as Activity,      
'' as DEPARTMENT,      
'' as SubDepartment,      
'' as JOBBAND,      
'' as LOCATION,      
'' as COSTCENTERDESCRIPTION,      
'' as CITY,      
'' as DEPARTMENTCODE,      
'' as SBUCODE,      
'' as CORPORATE,      
'' as VERTICALNAME,      
'' as ZONE,      
'' as BRANCH,      
'' as DIVISION,      
'' as BANDCODE,      
'' as title,      
'' as COMPANYCODE,      
'' as FUSIONID,      
'' as BUSINESSUNIT,      
'' as COSTCODE,      
'' as COSTCENTER,      
'' as ENTITYCODE,      
'' as TRAVELCLASS,      
'' as GRADE,      
'' as STATE,      
'' as TravellerRemarks,      
'' as ApproverRemarks,      
'' as BookingRemarks,      
'' as DESIGNATION  
from Hotel_BookMaster HB      
 join Hotel_Status_History HH on HB.pkId = HH.FKHotelBookingId and  HH.FkStatusId=4  
 join Hotel_Status_Master HM on HH.FkStatusId = HM.Id                                                                                                             
 left join B2BHotel_Commission BC on BC.Fk_BookId = hb.pkId                                                                   
 left join tblSelfBalance tbs on tbs.BookingRef = HB.orderId and tbs.UserID = HB.MainAgentID                             
 left join tblAgentBalance tbla on tbla.BookingRef = HB.orderId  and  tbla.AgentNo = HB.RiyaAgentID    
 left join B2BMakepaymentCommission B2BMC on B2BMC.FkBookId=HB.pkId  
 left join B2BRegistration B2B on B2B.FKUserID=HB.RiyaAgentID  
 left join agentLogin AL on AL.UserID=B2B.FKUserID  
 left join mAgentGroup MAG on MAG.Id=AL.GroupId  
 left join Hotel_BookingGSTDetails gst on gst.PKID=HB.pkId or gst.OrderId=HB.orderId  
 --left join Hotel_AttributesData HAT on HAT.FKBookId=HB.pkId  
where (HB.RiyaAgentID = @AgentId or (HB.MainAgentID = @MainAgentId and HB.MainAgentID > 0))                                  
  and HB.BookingPortal in('TNH','TNHAPI')           
  and HB.RiyaAgentID is not null                                                                                                                                     
  and ((Convert(date,HH.CreateDate) >= Convert(date,@FromDate) and Convert(date,HH.CreateDate) < @ToDate) or @FromDate='')              
  
  Union  
  
  ---- Hold(confirmed) Condition--  
  select       
'Hotel' as ProductType,      
'' as TripID,      
MAG.GroupName as GroupName,      
B2B.AgencyName as CorporateName,      
'Corporate' as CorporateType,      
'' as CorporateID,      
HB.PassengerEmail as EmployeeEmailID,      
HB.PassengerPhone as EmployeeMobileNo,        
'' as EmployeeCode,      
'' as TravellerType,      
'' as BookingType,      
HB.LeaderTitle as Title,      
HB.LeaderFirstName as FirstName,      
HB.LeaderLastName as LastName,      
HM.status AS Status,        
'' as BookAppType,      
'' as StockType,      
HB.B2BPaymentMode as PaymentMode,      
'' as RequestedDate,      
'' as ApprovedDate,      
HH.CreateDate as BookedDate,      
'' as ApproveByOREApproverBookedBy,      
'' as BookedBy,      
HB.BookingCountry as CountryCode,      
'' as CountryName,      
--HB.cityName AS CityName,      
HB.HotelName as HotelName,      
ISNULL(HB.HotelAddress1,HB.HotelAddress2) AS AccommodationAddress,      
HB.HotelIncludes +''+HB.Meal AS Inclusion,        
HB.CheckInDate AS CheckInDate,        
HB.CheckOutDate AS CheckOutDate,      
HB.CheckInTime as CheckInTime,      
HB.CheckOutTime AS CheckOutTime,      
HB.SelectedNights AS RoomNight,      
CASE WHEN HB.BookingCountry='IN' THEN 'Domestic' Else 'International' END  AS TravelScope,      
HB.BookingReference AS RIYAPNR,      
ISNULL(HB.HotelConfNumber,'') as BookingRef,      
ISNULL(HB.providerConfirmationNumber,'')  as GDSRef,      
'' as PassiveSegRef,      
'' AS RateType,      
HB.TotalRoomAmount as BaseFare,      
HB.HotelTaxes as TotalTax,      
0 as Markup,      
HB.AgentCommission as Discount,      
HB.agentCancellationCharges as Penalty,      
0 as CancellationMarkup,      
0 as Breakupoftaxes,      
bc.GSTAmount as GST,      
HB.AgentServiceFee as serviceFee,      
0 as GSTonSF,      
bc.TDSDeductedAmount as TDS,      
ISNULL(B2BMC.TotalCommission,0) as PGCharges,      
0 as GSTonPG,      
HB.agentCancellationCharges as CancelCharges,      
0 as RescheduleCharges,      
HB.STotalRate as NetAmount,      
hb.HotelTotalGross as GrossAmount,      
(cast(HB.DisplayDiscountRate as float) / cast(HB.SelectedNights as float)) as PerNightRate,   
'' as CappingLimit,      
'' as  SuggestedLowestRate,     
'' as L1Hotel,      
'' as L1Rate,      
'' as L2Hotel,      
'' as L2Rate,      
'' as L3Hotel,      
'' as L3Rate,      
0 as MissedSavings,      
hb.ROEValue as ROE,      
'' as ROECurrency,      
isnull(gst.GstNumber,'') as GSTNo,      
isnull(gst.Address,'') as GSTAddress,      
isnull(gst.EmailId,'') as GSTMailID,      
isnull(gst.MobileNo,'') as GSTPhoneNo,   
--case when HAT.AttributeId=4 Then HAT.AttributesValue Else '' END as CostCentre,  
''  as CostCentre,  
'' as DebitCostCenter,      
'' as ComplainceOrNonComplaince,      
'' as TravelPolicies,      
'' as ReferenceID,      
''  as CompanycodeOrNonBillable,      
'' as Durationoftravel,      
'' as EmployeeWorkingLocation,      
'' as Natureoftravel,      
'' as ProjectCode,      
'' as ReasonForNotSelectingLowestPreferredHotel,      
'' as RequestNo,      
'' as SAPCode,      
'' as LOCATIONCODE,      
'' as 'FUNCTION',      
'' as Activity,      
'' as DEPARTMENT,      
'' as SubDepartment,      
'' as JOBBAND,      
'' as LOCATION,      
'' as COSTCENTERDESCRIPTION,      
'' as CITY,      
'' as DEPARTMENTCODE,      
'' as SBUCODE,      
'' as CORPORATE,      
'' as VERTICALNAME,      
'' as ZONE,      
'' as BRANCH,      
'' as DIVISION,      
'' as BANDCODE,      
'' as title,      
'' as COMPANYCODE,      
'' as FUSIONID,      
'' as BUSINESSUNIT,      
'' as COSTCODE,      
'' as COSTCENTER,      
'' as ENTITYCODE,      
'' as TRAVELCLASS,      
'' as GRADE,      
'' as STATE,      
'' as TravellerRemarks,      
'' as ApproverRemarks,      
'' as BookingRemarks,  
'' as DESIGNATION  
      
from Hotel_BookMaster HB      
 join Hotel_Status_History HH on HB.pkId = HH.FKHotelBookingId and  HH.FkStatusId=3  
 join Hotel_Status_Master HM on HH.FkStatusId = HM.Id                                                                                                             
 left join B2BHotel_Commission BC on BC.Fk_BookId = hb.pkId                                                                   
 left join tblSelfBalance tbs on tbs.BookingRef = HB.orderId and tbs.UserID = HB.MainAgentID                             
 left join tblAgentBalance tbla on tbla.BookingRef = HB.orderId  and  tbla.AgentNo = HB.RiyaAgentID   
 left join B2BMakepaymentCommission B2BMC on B2BMC.FkBookId=HB.pkId  
 left join B2BRegistration B2B on B2B.FKUserID=HB.RiyaAgentID  
 left join agentLogin AL on AL.UserID=B2B.FKUserID  
 left join mAgentGroup MAG on MAG.Id=AL.GroupId  
 left join Hotel_BookingGSTDetails gst on gst.PKID=HB.pkId or gst.OrderId=HB.orderId  
 --left join Hotel_AttributesData HAT on HAT.FKBookId=HB.pkId  
where (HB.RiyaAgentID = @AgentId or (HB.MainAgentID = @MainAgentId and HB.MainAgentID > 0))                                  
  and HB.BookingPortal in('TNH','TNHAPI')           
  and HB.RiyaAgentID is not null                                                                                                                                     
  and ((Convert(date,HH.CreateDate) >= Convert(date,@FromDate) and Convert(date,HH.CreateDate) < @ToDate) or @FromDate='')    
    
  UNION  
  
  ---- Cancelled Condition--  
  select       
'Hotel' as ProductType,      
'' as TripID,      
MAG.GroupName as GroupName,      
B2B.AgencyName as CorporateName,      
'Corporate' as CorporateType,      
'' as CorporateID,      
HB.PassengerEmail as EmployeeEmailID,      
HB.PassengerPhone as EmployeeMobileNo,      
'' as EmployeeCode,      
'' as TravellerType,      
'' as BookingType,      
HB.LeaderTitle as Title,      
HB.LeaderFirstName as FirstName,      
HB.LeaderLastName as LastName,      
HM.status AS Status,        
'' as BookAppType,      
'' as StockType,      
HB.B2BPaymentMode as PaymentMode,      
'' as RequestedDate,      
'' as ApprovedDate,      
HH.CreateDate as BookedDate,      
'' as ApproveByOREApproverBookedBy,      
'' as BookedBy,      
HB.BookingCountry as CountryCode,      
'' as CountryName,      
--HB.cityName AS CityName,      
HB.HotelName as HotelName,      
ISNULL(HB.HotelAddress1,HB.HotelAddress2) AS AccommodationAddress,      
HB.HotelIncludes +''+HB.Meal AS Inclusion,        
HB.CheckInDate AS CheckInDate,        
HB.CheckOutDate AS CheckOutDate,      
HB.CheckInTime as CheckInTime,      
HB.CheckOutTime AS CheckOutTime,      
HB.SelectedNights AS RoomNight,      
CASE WHEN HB.BookingCountry='IN' THEN 'Domestic' Else 'International' END  AS TravelScope,      
HB.BookingReference AS RIYAPNR,      
ISNULL(HB.HotelConfNumber,'') as BookingRef,      
ISNULL(HB.providerConfirmationNumber,'')  as GDSRef,      
'' as PassiveSegRef,      
'' AS RateType,      
HB.TotalRoomAmount as BaseFare,      
HB.HotelTaxes as TotalTax,      
0 as Markup,      
HB.AgentCommission as Discount,      
HB.agentCancellationCharges as Penalty,      
0 as CancellationMarkup,      
0 as Breakupoftaxes,      
bc.GSTAmount as GST,      
HB.AgentServiceFee as serviceFee,      
0 as GSTonSF,      
bc.TDSDeductedAmount as TDS,      
ISNULL(B2BMC.TotalCommission,0) as PGCharges,      
0 as GSTonPG,      
HB.agentCancellationCharges as CancelCharges,      
0 as RescheduleCharges,      
HB.STotalRate as NetAmount,      
hb.HotelTotalGross as GrossAmount,      
(cast(HB.DisplayDiscountRate as float) / cast(HB.SelectedNights as float)) as PerNightRate,  
'' as CappingLimit,      
'' as  SuggestedLowestRate,      
'' as L1Hotel,      
'' as L1Rate,      
'' as L2Hotel,      
'' as L2Rate,      
'' as L3Hotel,      
'' as L3Rate,      
0 as MissedSavings,      
hb.ROEValue as ROE,      
'' as ROECurrency,      
isnull(gst.GstNumber,'') as GSTNo,      
isnull(gst.Address,'') as GSTAddress,      
isnull(gst.EmailId,'') as GSTMailID,      
isnull(gst.MobileNo,'') as GSTPhoneNo,        
--case when HAT.AttributeId=4 Then HAT.AttributesValue Else '' END as CostCentre,   
''  as CostCentre,  
'' as DebitCostCenter,      
'' as ComplainceOrNonComplaince,      
'' as TravelPolicies,      
'' as ReferenceID,      
''  as CompanycodeOrNonBillable,      
'' as Durationoftravel,      
'' as EmployeeWorkingLocation,      
'' as Natureoftravel,      
'' as ProjectCode,      
'' as ReasonForNotSelectingLowestPreferredHotel,      
'' as RequestNo,      
'' as SAPCode,      
'' as LOCATIONCODE,      
'' as 'FUNCTION',      
'' as Activity,      
'' as DEPARTMENT,      
'' as SubDepartment,      
'' as JOBBAND,      
'' as LOCATION,      
'' as COSTCENTERDESCRIPTION,      
'' as CITY,      
'' as DEPARTMENTCODE,      
'' as SBUCODE,      
'' as CORPORATE,      
'' as VERTICALNAME,      
'' as ZONE,      
'' as BRANCH,      
'' as DIVISION,      
'' as BANDCODE,      
'' as title,      
'' as COMPANYCODE,      
'' as FUSIONID,      
'' as BUSINESSUNIT,      
'' as COSTCODE,      
'' as COSTCENTER,      
'' as ENTITYCODE,      
'' as TRAVELCLASS,      
'' as GRADE,      
'' as STATE,      
'' as TravellerRemarks,      
'' as ApproverRemarks,      
'' as BookingRemarks,  
'' as DESIGNATION  
      
from Hotel_BookMaster HB      
 join Hotel_Status_History HH on HB.pkId = HH.FKHotelBookingId and  HH.FkStatusId=7  
 join Hotel_Status_Master HM on HH.FkStatusId = HM.Id                                                                                                             
 left join B2BHotel_Commission BC on BC.Fk_BookId = hb.pkId                                                                   
 left join tblSelfBalance tbs on tbs.BookingRef = HB.orderId and tbs.UserID = HB.MainAgentID                             
 left join tblAgentBalance tbla on tbla.BookingRef = HB.orderId  and  tbla.AgentNo = HB.RiyaAgentID   
 left join B2BMakepaymentCommission B2BMC on B2BMC.FkBookId=HB.pkId  
  left join B2BRegistration B2B on B2B.FKUserID=HB.RiyaAgentID  
 left join agentLogin AL on AL.UserID=B2B.FKUserID  
 left join mAgentGroup MAG on MAG.Id=AL.GroupId  
 left join Hotel_BookingGSTDetails gst on gst.PKID=HB.pkId or gst.OrderId=HB.orderId  
 left join Hotel_AttributesData HAT on HAT.FKBookId=HB.pkId  
where (HB.RiyaAgentID = @AgentId or (HB.MainAgentID = @MainAgentId and HB.MainAgentID > 0))                                  
  and HB.BookingPortal in('TNH','TNHAPI')           
  and HB.RiyaAgentID is not null                                                                                                   
  and ((Convert(date,HH.CreateDate) >= Convert(date,@FromDate) and Convert(date,HH.CreateDate) < @ToDate) or @FromDate='')      
  
  UNION  
  
   ---- Pending Condition--  
  select       
'Hotel' as ProductType,      
'' as TripID,      
MAG.GroupName as GroupName,      
B2B.AgencyName as CorporateName,      
'Corporate' as CorporateType,      
'' as CorporateID,      
HB.PassengerEmail as EmployeeEmailID,      
HB.PassengerPhone as EmployeeMobileNo,       
'' as EmployeeCode,      
'' as TravellerType,      
'' as BookingType,      
HB.LeaderTitle as Title,      
HB.LeaderFirstName as FirstName,      
HB.LeaderLastName as LastName,      
HM.status AS Status,        
'' as BookAppType,      
'' as StockType,      
HB.B2BPaymentMode as PaymentMode,      
'' as RequestedDate,      
'' as ApprovedDate,      
HH.CreateDate as BookedDate,      
'' as ApproveByOREApproverBookedBy,      
'' as BookedBy,      
HB.BookingCountry as CountryCode,      
'' as CountryName,      
--HB.cityName AS CityName,      
HB.HotelName as HotelName,      
ISNULL(HB.HotelAddress1,HB.HotelAddress2) AS AccommodationAddress,      
HB.HotelIncludes +''+HB.Meal AS Inclusion,        
HB.CheckInDate AS CheckInDate,        
HB.CheckOutDate AS CheckOutDate,      
HB.CheckInTime as CheckInTime,      
HB.CheckOutTime AS CheckOutTime,      
HB.SelectedNights AS RoomNight,      
CASE WHEN HB.BookingCountry='IN' THEN 'Domestic' Else 'International' END  AS TravelScope,      
HB.BookingReference AS RIYAPNR,      
ISNULL(HB.HotelConfNumber,'') as BookingRef,      
ISNULL(HB.providerConfirmationNumber,'')  as GDSRef,      
'' as PassiveSegRef,      
'' AS RateType,      
HB.TotalRoomAmount as BaseFare,      
HB.HotelTaxes as TotalTax,      
0 as Markup,      
HB.AgentCommission as Discount,      
HB.agentCancellationCharges as Penalty,      
0 as CancellationMarkup,      
0 as Breakupoftaxes,      
0 as GST,      
HB.AgentServiceFee as serviceFee,      
0 as GSTonSF,      
0 as TDS,      
0 as PGCharges,      
0 as GSTonPG,      
0 as CancelCharges,      
0 as RescheduleCharges,      
HB.STotalRate as NetAmount,      
hb.HotelTotalGross as GrossAmount,      
0 as PerNightRate,      
'' as CappingLimit,      
'' as  SuggestedLowestRate,      
'' as L1Hotel,      
'' as L1Rate,      
'' as L2Hotel,      
'' as L2Rate,      
'' as L3Hotel,      
'' as L3Rate,      
0 as MissedSavings,      
hb.ROEValue as ROE,      
'' as ROECurrency,      
'' as GSTNo,      
'' as GSTAddress,      
'' as GSTMailID,      
'' as GSTPhoneNo,      
'' as CostCentre,      
'' as DebitCostCenter,      
'' as ComplainceOrNonComplaince,      
'' as TravelPolicies,      
'' as ReferenceID,      
''  as CompanycodeOrNonBillable,      
'' as Durationoftravel,      
'' as EmployeeWorkingLocation,      
'' as Natureoftravel,      
'' as ProjectCode,      
'' as ReasonForNotSelectingLowestPreferredHotel,      
'' as RequestNo,      
'' as SAPCode,      
'' as LOCATIONCODE,      
'' as 'FUNCTION',      
'' as Activity,      
'' as DEPARTMENT,      
'' as SubDepartment,      
'' as JOBBAND,      
'' as LOCATION,      
'' as COSTCENTERDESCRIPTION,      
'' as CITY,      
'' as DEPARTMENTCODE,      
'' as SBUCODE,      
'' as CORPORATE,      
'' as VERTICALNAME,      
'' as ZONE,      
'' as BRANCH,      
'' as DIVISION,      
'' as BANDCODE,      
'' as title,      
'' as COMPANYCODE,      
'' as FUSIONID,      
'' as BUSINESSUNIT,      
'' as COSTCODE,      
'' as COSTCENTER,      
'' as ENTITYCODE,      
'' as TRAVELCLASS,      
'' as GRADE,      
'' as STATE,      
'' as TravellerRemarks,      
'' as ApproverRemarks,      
'' as BookingRemarks,  
'' as DESIGNATION  
      
from Hotel_BookMaster HB      
 join Hotel_Status_History HH on HB.pkId = HH.FKHotelBookingId and  HH.FkStatusId=9  
 join Hotel_Status_Master HM on HH.FkStatusId = HM.Id                                                                                                             
 --left join B2BHotel_Commission BC on BC.Fk_BookId = hb.pkId                                                 
 --left join tblSelfBalance tbs on tbs.BookingRef = HB.orderId and tbs.UserID = HB.MainAgentID                             
 --left join tblAgentBalance tbla on tbla.BookingRef = HB.orderId  and  tbla.AgentNo = HB.RiyaAgentID    
 left join B2BRegistration B2B on B2B.FKUserID=HB.RiyaAgentID  
 left join agentLogin AL on AL.UserID=B2B.FKUserID  
 left join mAgentGroup MAG on MAG.Id=AL.GroupId  
where (HB.RiyaAgentID = @AgentId or (HB.MainAgentID = @MainAgentId and HB.MainAgentID > 0))                                  
  and HB.BookingPortal in('TNH','TNHAPI')           
  and HB.RiyaAgentID is not null                                                                                                                                     
  and ((Convert(date,HH.CreateDate) >= Convert(date,@FromDate) and Convert(date,HH.CreateDate) < @ToDate) or @FromDate='')      
  order by HH.CreateDate desc     
END        
         
        
         