CREATE TABLE [Invoice].[Outstanding_Ageing] (
    [Id]            BIGINT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [BW_CUS_CODE]   VARCHAR (MAX)   NULL,
    [BW_OB_BAL]     VARCHAR (MAX)   NULL,
    [BW_PARTY_NAME] VARCHAR (MAX)   NULL,
    [BW_PARTY_ADD]  VARCHAR (MAX)   NULL,
    [BW_PARTY_ADD1] VARCHAR (MAX)   NULL,
    [BW_SALES_REP]  VARCHAR (MAX)   NULL,
    [BW_SREP_NAME]  VARCHAR (MAX)   NULL,
    [BW_PHONE]      VARCHAR (MAX)   NULL,
    [BW_TYPE]       VARCHAR (50)    NULL,
    [BW_VOUCHNO]    VARCHAR (100)   NULL,
    [BW_VOUCHDT]    DATETIME        NULL,
    [BW_DAYS]       INT             NULL,
    [BW_DESCRIP]    VARCHAR (MAX)   NULL,
    [BW_PAY_TO]     VARCHAR (MAX)   NULL,
    [BW_DR_AMT]     NUMERIC (19, 2) NULL,
    [BW_CR_AMT]     NUMERIC (19, 2) NULL,
    [BW_BIL_BAL]    NUMERIC (19, 2) NULL,
    [BW_BLIV_NO]    VARCHAR (100)   NULL,
    [BW_BLIV_DT]    DATETIME        NULL,
    [BW_CRN_NO]     VARCHAR (MAX)   NULL,
    [BW_CUR_COD]    VARCHAR (50)    NULL,
    [BW_CRN_DTE]    VARCHAR (MAX)   NULL,
    [BW_CHEQ_NO]    VARCHAR (100)   NULL,
    [BW_REC_NUMBER] INT             NULL,
    [BW_INV_TYP]    INT             NULL,
    [RUNTOT]        NUMERIC (19, 2) NULL,
    CONSTRAINT [PK_Outstanding_Ageing] PRIMARY KEY CLUSTERED ([Id] ASC)
);

