CREATE TABLE [TR].[TR_BookingMasterQuickModify] (
    [Id]                     INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [FkBookingId]            INT           NULL,
    [BookingRefId]           VARCHAR (50)  NULL,
    [BookingStatus]          VARCHAR (50)  NULL,
    [creationDate]           DATETIME      NULL,
    [CancellationDeadline]   DATETIME      NULL,
    [TripStartDate]          DATETIME      NULL,
    [PickupLocation]         VARCHAR (100) NULL,
    [DropOffLocation]        VARCHAR (100) NULL,
    [RoundTrip]              INT           NULL,
    [CountryCode]            VARCHAR (100) NULL,
    [CityName]               VARCHAR (50)  NULL,
    [OBTCNo]                 VARCHAR (50)  NULL,
    [CategoryVehicleType]    VARCHAR (50)  NULL,
    [CarName]                VARCHAR (100) NULL,
    [EstimatedTime]          VARCHAR (50)  NULL,
    [FlightCode]             VARCHAR (500) NULL,
    [FlightArrivalTime]      VARCHAR (500) NULL,
    [Remark]                 VARCHAR (500) NULL,
    [CancellationRemark]     VARCHAR (400) NULL,
    [CancellationPolicyText] TEXT          NULL,
    [Titel]                  VARCHAR (10)  NULL,
    [PassengerName]          VARCHAR (50)  NULL,
    [Nationality]            VARCHAR (500) NULL,
    [TotalPax]               INT           NULL,
    [Contact]                VARCHAR (50)  NULL,
    [Email]                  VARCHAR (500) NULL,
    [PassportNumber]         VARCHAR (50)  NULL,
    [PancardNo]              VARCHAR (50)  NULL,
    [PanCardName]            VARCHAR (50)  NULL,
    [TripStartTime]          VARCHAR (100) NULL,
    [Luggage]                INT           NULL,
    [modifiedDate]           DATETIME      NULL,
    [ModifyBy]               VARCHAR (100) NULL,
    [IsActive]               BIT           NULL
);

