CREATE TABLE [TR].[TR_BookingMaster] (
    [BookingId]                        INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [BookingRefId]                     VARCHAR (50)    NULL,
    [CorrelationId]                    VARCHAR (MAX)   NULL,
    [ProviderConfirmationNumber]       VARCHAR (50)    NULL,
    [TripStartDate]                    DATETIME        NULL,
    [TripEndDate]                      DATETIME        NULL,
    [PickupLocation]                   VARCHAR (100)   NULL,
    [DropOffLocation]                  VARCHAR (100)   NULL,
    [RoundTrip]                        INT             NULL,
    [ChannelId]                        VARCHAR (50)    NULL,
    [accountId]                        VARCHAR (50)    NULL,
    [providerName]                     VARCHAR (50)    NULL,
    [providerId]                       VARCHAR (50)    NULL,
    [ProviderCancellationNumber]       VARCHAR (50)    NULL,
    [creationDate]                     DATETIME        CONSTRAINT [DF_TR_BookingMaster_creationDate] DEFAULT (getdate()) NULL,
    [modifiedDate]                     DATETIME        NULL,
    [SupplierCurrency]                 VARCHAR (50)    NULL,
    [BookingRate]                      FLOAT (53)      NULL,
    [BookingCurrency]                  VARCHAR (50)    NULL,
    [AgentID]                          INT             NULL,
    [MainAgentID]                      INT             NULL,
    [SubMainAgntId]                    INT             NULL,
    [PaymentMode]                      INT             NULL,
    [CityName]                         VARCHAR (50)    NULL,
    [Cust_Id]                          VARCHAR (50)    NULL,
    [BookingStatus]                    VARCHAR (50)    NULL,
    [PGStatus]                         VARCHAR (50)    NULL,
    [VoucherUrl]                       VARCHAR (MAX)   NULL,
    [ReversalStatus]                   BIT             NULL,
    [MakePaymentReversalFlag]          VARCHAR (200)   NULL,
    [MakePaymentReversalStatus]        VARCHAR (200)   NULL,
    [MakePaymentReversalMessage]       VARCHAR (MAX)   NULL,
    [CancellationDate]                 DATETIME        NULL,
    [EstimatedTime]                    VARCHAR (50)    NULL,
    [CategoryVehicleType]              VARCHAR (50)    NULL,
    [Remark]                           VARCHAR (500)   NULL,
    [CancellationDeadline]             DATETIME        NULL,
    [SupplierCancellationDate]         DATETIME        NULL,
    [CityCode]                         VARCHAR (50)    NULL,
    [CountryCode]                      VARCHAR (50)    NULL,
    [ROEValue]                         FLOAT (53)      NULL,
    [Markup]                           VARCHAR (50)    NULL,
    [AgentCanxCharges]                 DECIMAL (18, 2) NULL,
    [SupplierCanxCharges]              DECIMAL (18, 2) NULL,
    [CancellationRemark]               VARCHAR (400)   NULL,
    [CancellationPolicyText]           TEXT            NULL,
    [SupplierCanxAgentChrge]           DECIMAL (18, 2) NULL,
    [PostCancellationCharges]          VARCHAR (100)   NULL,
    [FinalROE]                         FLOAT (53)      NULL,
    [ServiceCharges]                   FLOAT (53)      NULL,
    [TotalServiceCharges]              FLOAT (53)      NULL,
    [SupplierChargesPer]               FLOAT (53)      NULL,
    [SupplierCharges]                  FLOAT (53)      NULL,
    [ModeOfCancellation]               VARCHAR (50)    NULL,
    [CancelledBy]                      VARCHAR (50)    NULL,
    [GSTAmountOnServiceCharges]        FLOAT (53)      NULL,
    [GSTOnServiceCharges]              FLOAT (53)      NULL,
    [FinalRoeMarkup]                   VARCHAR (50)    NULL,
    [FileNo]                           VARCHAR (50)    NULL,
    [OBTCNo]                           VARCHAR (50)    NULL,
    [InquiryNo]                        VARCHAR (50)    NULL,
    [AccRemark]                        VARCHAR (50)    NULL,
    [OpsRemark]                        VARCHAR (50)    NULL,
    [TotalAdult]                       INT             NULL,
    [TotalChildren]                    INT             NULL,
    [ProviderContactNumber]            VARCHAR (20)    NULL,
    [Transfer_ERPPushStatus]           BIT             NULL,
    [BillingSettledBy]                 VARCHAR (50)    NULL,
    [CorporatePANVerificatioStatus]    VARCHAR (50)    NULL,
    [DocumentURL]                      VARCHAR (MAX)   NULL,
    [Transfer_ERPCanResponseID]        VARCHAR (MAX)   NULL,
    [Transfer_ERPCanPushStatus]        BIT             NULL,
    [FlightCode]                       VARCHAR (500)   NULL,
    [SpecialRequests]                  VARCHAR (500)   NULL,
    [FlightArrivalTime]                VARCHAR (500)   NULL,
    [AmountBeforePgCommission]         DECIMAL (10, 2) NULL,
    [AmountAfterPgCommision]           DECIMAL (10, 2) NULL,
    [TripStartTime]                    VARCHAR (100)   NULL,
    [SupplierRate]                     DECIMAL (10, 2) NULL,
    [PickInfo]                         VARCHAR (MAX)   NULL,
    [Luggage]                          INT             NULL,
    [Distance]                         DECIMAL (10, 2) NULL,
    [Refundable]                       BIT             NULL,
    [JourneyStartTime]                 VARCHAR (100)   NULL,
    [IsModify]                         INT             NULL,
    [AgentDiscountPrice]               DECIMAL (10, 2) NULL,
    [AgentCurrencyCode]                VARCHAR (50)    NULL,
    [AgentROE]                         VARCHAR (50)    NULL,
    [AgentFinalROE]                    VARCHAR (50)    NULL,
    [ROEMarkup]                        VARCHAR (50)    NULL,
    [CommissionPercent]                DECIMAL (10, 2) NULL,
    [CommissionAmount]                 DECIMAL (10, 2) NULL,
    [SupplierDiscountPrice]            DECIMAL (10, 2) NULL,
    [SupplierToInrRoe]                 VARCHAR (50)    NULL,
    [SupplierToFinalRoe]               VARCHAR (50)    NULL,
    [RoeMarkupInr]                     VARCHAR (50)    NULL,
    [PricingProfile]                   DECIMAL (10, 2) NULL,
    [ServiceCharge]                    DECIMAL (10, 2) NULL,
    [SupplierCharge]                   DECIMAL (10, 2) NULL,
    [GSTServiceCharge]                 DECIMAL (10, 2) NULL,
    [ChildSeat]                        INT             NULL,
    [Children1Age]                     INT             NULL,
    [Children2Age]                     INT             NULL,
    [ChildAge]                         VARCHAR (MAX)   NULL,
    [AgentServiceFee]                  DECIMAL (18, 2) NULL,
    [AgentServiceFeeRealTime]          DECIMAL (18, 2) NULL,
    [RiyaUserRealTimeServiceFee]       DECIMAL (18, 2) NULL,
    [GSTOnRiyaUsereRealTimeServiceFee] DECIMAL (18, 2) NULL,
    [IsRetrieveAPI]                    BIT             CONSTRAINT [DF_TR_BookingMaster_IsRetrieveAPI] DEFAULT ((0)) NULL,
    [ClientIP]                         VARCHAR (100)   NULL,
    [DriverFirstName]                  VARCHAR (50)    NULL,
    [DriverLastName]                   VARCHAR (50)    NULL,
    [DriverMobileNo]                   VARCHAR (50)    NULL,
    [RequestForCancelled]              VARCHAR (50)    NULL,
    [ExpirationDate]                   DATETIME        NULL,
    [AgentToInrRoe]                    VARCHAR (50)    NULL,
    [AgentToInrFinalRoe]               VARCHAR (50)    NULL,
    [Transfer_ERPPushResponseID]       VARCHAR (MAX)   NULL,
    [InrToSupplierRoe]                 VARCHAR (50)    NULL,
    [InrToSupplierFinalRoe]            VARCHAR (50)    NULL,
    [mustCheckPickupTime]              BIT             DEFAULT ((0)) NULL,
    [CheckPickupURL]                   NVARCHAR (200)  NULL,
    [hoursBeforeConsulting]            INT             DEFAULT ((0)) NULL,
    [SupplierEmergencyNumber]          NVARCHAR (20)   NULL,
    [Flight_direction]                 VARCHAR (50)    NULL,
    [Dest_CancellationDateTime]        DATETIME        NULL,
    [PickupDateTime_Frm_Response]      DATETIME        NULL,
    CONSTRAINT [PK_SS_BookingMaster] PRIMARY KEY CLUSTERED ([BookingId] ASC)
);

