CREATE TABLE [TR].[Transfer_AgentSupplierProfileMapper] (
    [Id]                        INT             IDENTITY (1, 1) NOT NULL,
    [AgentId]                   INT             NULL,
    [SupplierId]                INT             NULL,
    [ProfileId]                 INT             NULL,
    [CancellationHours]         INT             NULL,
    [PriceOptimizationOn]       VARCHAR (100)   NULL,
    [CreateDate]                DATETIME        NULL,
    [IsActive]                  BIT             CONSTRAINT [DF_Transfer_AgentSupplierProfileMapper_IsActive] DEFAULT ((0)) NULL,
    [CorporateCode]             VARCHAR (20)    NULL,
    [IsActiveCorporateCode]     BIT             NULL,
    [Channelid]                 VARCHAR (50)    NULL,
    [IsGSTRequired]             BIT             NULL,
    [IsPanRequired]             BIT             NULL,
    [ServiceCharge]             FLOAT (53)      NULL,
    [ServiceChargeAmt]          FLOAT (53)      CONSTRAINT [DF_Transfer_AgentSupplierProfileMapper_ServiceChargeAmt] DEFAULT ((0.00)) NULL,
    [GSTOnServiceCharge]        FLOAT (53)      NULL,
    [RateCode]                  VARCHAR (MAX)   NULL,
    [ModifiedDate]              DATETIME        NULL,
    [ModifiedBy]                VARCHAR (200)   NULL,
    [ServicePercent]            FLOAT (53)      NULL,
    [IATA]                      VARCHAR (50)    NULL,
    [PCC]                       VARCHAR (50)    NULL,
    [Service_charge_onAgent]    DECIMAL (18, 2) NULL,
    [GstService_charge_onAgent] DECIMAL (18, 2) NULL,
    [AgentCurrency]             VARCHAR (10)    NULL,
    [RateCodeid]                INT             NULL,
    [IsRateCodeRequired]        BIT             CONSTRAINT [DF_Transfer_AgentSupplierProfileMapper_IsRateCodeRequired] DEFAULT ((0)) NULL,
    [IsPccRequired]             BIT             CONSTRAINT [DF_Transfer_AgentSupplierProfileMapper_IsPccRequired] DEFAULT ((0)) NULL,
    [CreatedBy]                 INT             NULL,
    CONSTRAINT [PK_AgentSupplierProfileMapper] PRIMARY KEY CLUSTERED ([Id] ASC)
);

