CREATE TABLE [Rail].[Bookings] (
    [Id]                    BIGINT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [BookingId]             VARCHAR (500)   NULL,
    [BookingReference]      VARCHAR (100)   NULL,
    [CorrelationId]         VARCHAR (500)   NULL,
    [creationDate]          SMALLDATETIME   NULL,
    [expirationDate]        SMALLDATETIME   NULL,
    [Currency]              VARCHAR (50)    NULL,
    [AgentCurrency]         VARCHAR (50)    NULL,
    [totalbillingsGross]    DECIMAL (18, 2) NULL,
    [totalbillingsNet]      DECIMAL (18, 2) NULL,
    [bookingStatus]         VARCHAR (100)   NULL,
    [overviewStatus]        VARCHAR (100)   NULL,
    [AgentId]               BIGINT          NULL,
    [RiyaUserId]            BIGINT          NULL,
    [AmountPaidbyAgent]     DECIMAL (18, 2) NULL,
    [MarkUpOnBookingFee]    DECIMAL (18, 2) NULL,
    [ReservationFee]        DECIMAL (18, 2) NULL,
    [BookingFee]            DECIMAL (18, 2) NULL,
    [TaxOnBookingFee]       DECIMAL (18, 2) NULL,
    [PaymentType]           VARCHAR (100)   NULL,
    [PaymentMode]           VARCHAR (100)   NULL,
    [ROE]                   FLOAT (53)      NULL,
    [CreatedDate]           DATETIME        CONSTRAINT [DF_Bookings_CreatedDate] DEFAULT (getdate()) NULL,
    [ModifiedDate]          DATETIME        NULL,
    [Request]               VARCHAR (MAX)   NULL,
    [Response]              VARCHAR (MAX)   NULL,
    [AgentInvoiceNumber]    VARCHAR (100)   NULL,
    [InquiryNo]             VARCHAR (100)   NULL,
    [FileNo]                VARCHAR (100)   NULL,
    [PaymentRefNo]          VARCHAR (100)   NULL,
    [OBTCNo]                VARCHAR (100)   NULL,
    [RTTRefNo]              VARCHAR (100)   NULL,
    [OpsRemark]             VARCHAR (100)   NULL,
    [AcctsRemark]           VARCHAR (100)   NULL,
    [SB_ReversalStatus]     BIT             NULL,
    [IsActive]              BIT             NULL,
    [BFCurrency]            VARCHAR (50)    NULL,
    [BFROE]                 FLOAT (53)      NULL,
    [BFroeMarkup]           VARCHAR (100)   NULL,
    [BFFinalROE]            FLOAT (53)      NULL,
    [RiyaPnr]               VARCHAR (100)   NULL,
    [Supplier]              VARCHAR (100)   NULL,
    [IsRetrievePnr]         BIT             NULL,
    [BFToInrROE]            FLOAT (53)      NULL,
    [BFToInrMarkup]         VARCHAR (100)   NULL,
    [BFToInrFinal]          FLOAT (53)      NULL,
    [AmountPaidbyAgentInr]  DECIMAL (18, 2) NULL,
    [BookingDate]           DATETIME        NULL,
    [Rail_ERPResponceID]    VARCHAR (500)   NULL,
    [Rail_CanERPResponceID] VARCHAR (500)   NULL,
    [Rail_ERPPushStatus]    INT             CONSTRAINT [DF__Bookings__Rail_E__704F21B3] DEFAULT ((0)) NOT NULL,
    [Rail_CanERPPushStatus] INT             CONSTRAINT [DF_Bookings_Rail_CanERPPushStatus] DEFAULT ((0)) NOT NULL,
    [PaymentgatewayFees]    DECIMAL (18, 2) CONSTRAINT [DF_Bookings_PaymentgatewayFees] DEFAULT ((0)) NULL,
    [CurrentTotal]          DECIMAL (18, 2) NULL,
    [ServiceFeesType]       VARCHAR (100)   NULL,
    [ServiceFees]           DECIMAL (18, 2) NULL,
    [ServiceFeesGST]        DECIMAL (18, 2) NULL,
    [TotalServiceFees]      DECIMAL (18, 2) NULL,
    [TotalBookingFee]       DECIMAL (18, 2) NULL,
    [IsApiBooking]          BIT             NULL,
    [orderId]               VARCHAR (100)   NULL,
    [IsOfflineBooking]      BIT             CONSTRAINT [DF__Bookings__IsOffl__6E5A559B] DEFAULT ((0)) NULL,
    [IsPaymentSuccessful]   BIT             CONSTRAINT [DF__Bookings__IsPaym__6F4E79D4] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_Bookings_1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

