CREATE TABLE [Rail].[BookingItems] (
    [Id]                          BIGINT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [fk_bookingId]                BIGINT          NULL,
    [bookingId]                   VARCHAR (500)   NULL,
    [bookingReference]            VARCHAR (500)   NULL,
    [bookingItemId]               VARCHAR (500)   NULL,
    [CorrelationId]               VARCHAR (500)   NULL,
    [Type]                        VARCHAR (50)    NULL,
    [PNR]                         VARCHAR (100)   NULL,
    [Origin]                      VARCHAR (100)   NULL,
    [Destination]                 VARCHAR (100)   NULL,
    [isDirect]                    INT             NULL,
    [isRoundTrip]                 BIT             NULL,
    [isInBound]                   BIT             NULL,
    [Departure]                   SMALLDATETIME   NULL,
    [Arrival]                     SMALLDATETIME   NULL,
    [Duration]                    VARCHAR (50)    NULL,
    [Country]                     VARCHAR (100)   NULL,
    [Comfort]                     VARCHAR (50)    NULL,
    [Flexibility]                 VARCHAR (100)   NULL,
    [numberOfTravelDays]          VARCHAR (50)    NULL,
    [expirationDate]              SMALLDATETIME   NULL,
    [activationPeriodStart]       SMALLDATETIME   NULL,
    [activationPeriodEnd]         SMALLDATETIME   NULL,
    [validityPeriodStart]         SMALLDATETIME   NULL,
    [validityPeriodEnd]           SMALLDATETIME   NULL,
    [Title]                       VARCHAR (500)   NULL,
    [Conditions]                  VARCHAR (MAX)   NULL,
    [PaxDetails]                  VARCHAR (MAX)   NULL,
    [PaxPricing]                  VARCHAR (MAX)   NULL,
    [Currency]                    VARCHAR (50)    NULL,
    [AgentCurrency]               VARCHAR (50)    NULL,
    [RiyaCommission]              DECIMAL (18, 2) NULL,
    [RiyaAmount]                  DECIMAL (18, 2) NULL,
    [AgentCommission]             DECIMAL (18, 2) NULL,
    [AgentAmount]                 DECIMAL (18, 2) NULL,
    [ReservationFee]              DECIMAL (18, 2) NULL,
    [Location]                    VARCHAR (500)   NULL,
    [ProductName]                 VARCHAR (100)   NULL,
    [AgentId]                     BIGINT          NULL,
    [RiyaUserId]                  BIGINT          NULL,
    [DeviceId]                    VARCHAR (MAX)   NULL,
    [CancellationEligible]        BIT             NULL,
    [PartialCancellationEligible] BIT             NULL,
    [Status]                      VARCHAR (100)   NULL,
    [ParentId]                    BIGINT          NULL,
    [CreatedDate]                 DATETIME        CONSTRAINT [DF_BookingItems_CreatedDate] DEFAULT (getdate()) NULL,
    [ModifiedDate]                DATETIME        NULL,
    [ROE]                         FLOAT (53)      NULL,
    [roeMarkup]                   VARCHAR (500)   NULL,
    [FinalROE]                    FLOAT (53)      NULL,
    [SupplierId]                  VARCHAR (100)   NULL,
    [Response]                    VARCHAR (MAX)   NULL,
    [ServiceFeesAppliedId]        INT             NULL,
    [SupplierToInrROE]            FLOAT (53)      NULL,
    [SupplierToInrMarkup]         VARCHAR (100)   NULL,
    [SupplierToInrFinal]          FLOAT (53)      NULL,
    [AgentToInrROE]               FLOAT (53)      NULL,
    [AgentToInrMarkup]            VARCHAR (100)   NULL,
    [AgentToInrFinal]             FLOAT (53)      NULL,
    [Rail_ERPResponceID]          VARCHAR (500)   NULL,
    [Rail_CanERPResponceID]       VARCHAR (500)   NULL,
    [Rail_ERPPushStatus]          INT             DEFAULT ((0)) NOT NULL,
    [CurrentAmount]               DECIMAL (18, 2) NULL,
    [AccommodationResponse]       VARCHAR (MAX)   NULL,
    [Accommodation]               VARCHAR (MAX)   NULL,
    [IsOldCommission]             BIT             NULL,
    [CommissionAfterGst]          DECIMAL (18, 2) NULL,
    [ServiceFees]                 DECIMAL (18, 2) NULL,
    [ServiceFeesGST]              DECIMAL (18, 2) NULL,
    [TotalServiceFees]            DECIMAL (18, 2) NULL,
    [TDSOnCommission]             DECIMAL (18, 2) NULL,
    [AgentToSupplierROE]          FLOAT (53)      NULL,
    [AgentToSupplierMarkup]       VARCHAR (100)   NULL,
    [AgentToSupplierFinal]        FLOAT (53)      NULL,
    [PolicyHtml]                  VARCHAR (MAX)   NULL,
    CONSTRAINT [PK_BookingItems] PRIMARY KEY CLUSTERED ([Id] ASC)
);

