CREATE TABLE [Rail].[PaxDetails] (
    [Id]                 BIGINT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [fk_ItemId]          BIGINT          NULL,
    [bookingId]          VARCHAR (500)   NULL,
    [bookingReference]   VARCHAR (100)   NULL,
    [bookingItemId]      VARCHAR (500)   NULL,
    [PaxId]              VARCHAR (500)   NULL,
    [type]               VARCHAR (50)    NULL,
    [leadTraveler]       BIT             NULL,
    [age]                INT             NULL,
    [emailAddress]       VARCHAR (100)   NULL,
    [phoneNumber]        VARCHAR (100)   NULL,
    [title]              VARCHAR (50)    NULL,
    [firstName]          VARCHAR (100)   NULL,
    [lastName]           VARCHAR (100)   NULL,
    [dateOfBirth]        DATETIME        NULL,
    [Pan]                VARCHAR (100)   NULL,
    [PanName]            VARCHAR (500)   NULL,
    [Nationality]        VARCHAR (100)   NULL,
    [countryOfResidence] VARCHAR (100)   NULL,
    [PassportNumber]     VARCHAR (500)   NULL,
    [IssueDate]          DATETIME        NULL,
    [ExpiryDate]         DATETIME        NULL,
    [CreatedDate]        DATETIME        CONSTRAINT [DF_PaxDetails_CreatedDate] DEFAULT (getdate()) NULL,
    [ModifiedDate]       DATETIME        NULL,
    [Request]            VARCHAR (MAX)   NULL,
    [Response]           VARCHAR (MAX)   NULL,
    [CountryCode]        VARCHAR (50)    NULL,
    [ConfirmPan]         VARCHAR (100)   NULL,
    [CardCode]           VARCHAR (50)    NULL,
    [CardType]           VARCHAR (50)    NULL,
    [Number]             VARCHAR (50)    NULL,
    [ConfirmPanName]     VARCHAR (100)   NULL,
    [Amount]             DECIMAL (18, 2) NULL,
    [IsCancelled]        BIT             NULL,
    CONSTRAINT [PK_PaxDetails] PRIMARY KEY CLUSTERED ([Id] ASC)
);

