CREATE TABLE [Rail].[tbl_Discount] (
    [Id]                 INT             NOT NULL,
    [MarketPoint]        VARCHAR (30)    NULL,
    [UserType]           VARCHAR (30)    NULL,
    [TravelValidityFrom] SMALLDATETIME   NULL,
    [TravelValidityTo]   SMALLDATETIME   NULL,
    [SaleValidityFrom]   SMALLDATETIME   NULL,
    [SaleValidityTo]     SMALLDATETIME   NULL,
    [Origin]             VARCHAR (30)    NULL,
    [Destination]        VARCHAR (30)    NULL,
    [GST]                VARCHAR (30)    NULL,
    [BookingType]        INT             NULL,
    [Cabin]              VARCHAR (50)    NULL,
    [Deck]               VARCHAR (50)    NULL,
    [Room]               VARCHAR (50)    NULL,
    [Currency]           VARCHAR (10)    NULL,
    [ServiceType]        VARCHAR (50)    NULL,
    [isActive]           BIT             NULL,
    [CreatedDate]        SMALLDATETIME   NULL,
    [ModifiedDate]       SMALLDATETIME   NULL,
    [CreatedBy]          NVARCHAR (50)   NULL,
    [ModifyBy]           NVARCHAR (50)   NULL,
    [SupplierType]       NVARCHAR (50)   NULL,
    [AgentId]            NVARCHAR (300)  NULL,
    [TDS]                DECIMAL (18, 2) NULL
);

