CREATE TABLE [Cruise].[BookedPaxDetails] (
    [Id]               BIGINT        IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [FkBookingId]      BIGINT        NOT NULL,
    [PaxRoomDetailsId] VARCHAR (100) NULL,
    [PaxType]          VARCHAR (100) NULL,
    [FirstName]        VARCHAR (100) NULL,
    [LastName]         VARCHAR (100) NULL,
    [Gender]           VARCHAR (10)  NULL,
    [Email]            VARCHAR (100) NULL,
    [Phone]            VARCHAR (50)  NULL,
    [DateOfBirth]      DATETIME      NULL,
    [Country]          VARCHAR (70)  NULL,
    [State]            VARCHAR (70)  NULL,
    [City]             VARCHAR (70)  NULL,
    [Citizenship]      VARCHAR (70)  NULL,
    [IsNri]            BIT           NULL,
    [IsPrimaryPax]     BIT           NULL,
    [RoomType]         VARCHAR (100) NULL,
    [RoomCode]         VARCHAR (100) NULL,
    [Meal]             VARCHAR (100) NULL,
    [Deck]             VARCHAR (10)  NULL,
    [RoomNo]           INT           NULL,
    [CreatedOn]        DATETIME      NULL,
    [Pan]              VARCHAR (100) NULL,
    [PanName]          VARCHAR (500) NULL,
    [PassportNumber]   VARCHAR (100) NULL,
    [IssueDate]        DATETIME      NULL,
    [ExpiryDate]       DATETIME      NULL,
    [Address]          VARCHAR (MAX) NULL,
    CONSTRAINT [PK_BookedPaxDetails] PRIMARY KEY CLUSTERED ([Id] ASC)
);

