CREATE TABLE [Cruise].[Bookings] (
    [Id]                   BIGINT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [OrderId]              VARCHAR (500)   NULL,
    [BookingId]            VARCHAR (100)   NULL,
    [BookingReferenceid]   VARCHAR (100)   NULL,
    [ItineraryId]          VARCHAR (100)   NULL,
    [AgentId]              VARCHAR (50)    NULL,
    [RiyaUserId]           VARCHAR (50)    NULL,
    [IPAddress]            VARCHAR (100)   NULL,
    [CancellationPolicy]   VARCHAR (MAX)   NULL,
    [Status]               INT             NULL,
    [IsConfirmed]          BIT             NULL,
    [IsCancelled]          BIT             NULL,
    [IsPaymentDone]        BIT             NULL,
    [IsERPPush]            BIT             NULL,
    [RouteId]              VARCHAR (100)   NULL,
    [StartingPort]         VARCHAR (50)    NULL,
    [Ports]                VARCHAR (500)   NULL,
    [DestinationPort]      VARCHAR (100)   NULL,
    [Available]            VARCHAR (50)    NULL,
    [BasePrice]            DECIMAL (18, 2) NULL,
    [PortCharges]          VARCHAR (50)    NULL,
    [Gratuity]             VARCHAR (50)    NULL,
    [FuelSurcharge]        VARCHAR (50)    NULL,
    [Insurance]            VARCHAR (50)    NULL,
    [Discount]             VARCHAR (50)    NULL,
    [Tax]                  DECIMAL (18, 2) NULL,
    [TcsTax]               DECIMAL (18, 2) NULL,
    [TcsTaxPct]            DECIMAL (18, 2) NULL,
    [AgentCommissionPct]   VARCHAR (50)    NULL,
    [AgentCommission]      VARCHAR (50)    NULL,
    [RiyaCommissionPct]    VARCHAR (50)    NULL,
    [RiyaCommission]       VARCHAR (50)    NULL,
    [ExcursionTotalPrice]  DECIMAL (18, 2) NULL,
    [TotalPrice]           DECIMAL (18, 2) NULL,
    [GrossPrice]           DECIMAL (18, 2) NULL,
    [GrossTax]             DECIMAL (18, 2) NULL,
    [ChargeType]           VARCHAR (50)    NULL,
    [CalculationType]      VARCHAR (50)    NULL,
    [AgentCharge]          DECIMAL (18, 2) NULL,
    [AgentTaxCharge]       DECIMAL (18, 2) NULL,
    [AppliedServiceFeesId] INT             NULL,
    [AmountPaidbyAgent]    DECIMAL (18, 2) NULL,
    [Invoice]              VARCHAR (500)   NULL,
    [Voucher]              VARCHAR (500)   NULL,
    [Request]              VARCHAR (MAX)   NULL,
    [Response]             VARCHAR (MAX)   NULL,
    [PaymentMode]          VARCHAR (50)    NULL,
    [PaymentType]          VARCHAR (50)    NULL,
    [AgentInvoiceNumber]   VARCHAR (100)   NULL,
    [InquiryNo]            VARCHAR (100)   NULL,
    [FileNo]               VARCHAR (100)   NULL,
    [PaymentRefNo]         VARCHAR (100)   NULL,
    [OBTCNo]               VARCHAR (100)   NULL,
    [RTTRefNo]             VARCHAR (100)   NULL,
    [OpsRemark]            VARCHAR (100)   NULL,
    [AcctsRemark]          VARCHAR (100)   NULL,
    [SB_ReversalStatus]    BIT             NULL,
    [Supplier]             VARCHAR (100)   NULL,
    [IsActive]             BIT             NULL,
    [CreatedOn]            DATETIME        CONSTRAINT [DF_Bookings_CreatedOn] DEFAULT (getdate()) NULL,
    [ModifiedOn]           DATETIME        NULL,
    CONSTRAINT [PK_Bookings] PRIMARY KEY CLUSTERED ([Id] ASC)
);

